### PR TITLE
more efficient modularity

### PR DESCRIPTION
**Pull request by afternone**
The `modularity` function in `src/community/modularity.jl` is very time-consuming for large networks. Because it has `N^2` loops. I update the function to make it fast for large networks. Below is the benchmark.
```
julia> g = barabasi_albert(100000,3)
{100000, 299991} undirected graph

julia> c = label_propagation(g)[1]
100000-element Array{Int64,1}:
    1
    2
    3
    ⋮
 2771
 3260
 3505

julia> @time LightGraphs.modularity(g,c)
 16.693947 seconds (22.58 M allocations: 517.595 MB, 0.45% gc time)
0.32058762903587995

julia> # the new function
julia> @time LightGraphs.modularity1(g,c)
  0.050851 seconds (300.15 k allocations: 10.182 MB)
0.3205876290359057
```

### CODE REVIEW

**Comment by CarloLucibello** [comment]
very nice! looks good to me.

One minor note: I don't know if it is performance-wise relevant, but may you want to fill the dict `a`, `e` with zeros, and avoid using get in the innerr cycle. But, as I said, maybe this is irrelevant and you can leave the function as it is

I wonder why codecov is complaing, probably some of the if branch you added is not covered by any test

**Comment by sbromberger** [comment]
This looks good, but could you run another benchmark with a dense graph (say, {5000, 15m}) and compare the performance?

**Comment by afternone** [comment]
@sbromberger  Only sparse networks (E~N) have so called community structures. In a real world situation, we often encounter computing modularity values for sparse networks.  Whatever, benchmarks on dense graphs are presented below.
```
julia> g = erdos_renyi(5000, 12497500) # full graph, there are at most 12497500 edges for a graph with 5000 nodes
{5000, 12497500} undirected graph

julia> c = rand(1:100, 5000); # partition just for test

julia> @time modularity(g,c) # old function
  0.241184 seconds (481.20 k allocations: 11.211 MB)
-0.00019801120224044802

julia> @time modularity1(g,c) # new function
  2.375612 seconds (12.50 M allocations: 381.412 MB, 3.10% gc time)
-0.00019801120224044832

julia> g = erdos_renyi(5000, 1249750) # less edges
{5000, 1249750} undirected graph

julia> @time modularity(g,c) # old function
  0.199229 seconds (480.51 k allocations: 11.201 MB)
-0.0002424599538031237

julia> @time modularity1(g,c) # new function
  0.240754 seconds (1.25 M allocations: 38.158 MB, 4.45% gc time)
-0.000242459953803123

julia> g = erdos_renyi(5000, 124975) # less edges
{5000, 124975} undirected graph

julia> @time modularity(g,c) # old function
  0.158727 seconds (480.66 k allocations: 11.203 MB)
-0.00029624706297530674

julia> @time modularity1(g,c) # new function
  0.024049 seconds (125.05 k allocations: 3.833 MB)
-0.0002962470629753074

julia> g = erdos_renyi(5000, 12497) # less edges
{5000, 12497} undirected graph

julia> @time modularity(g,c) # old function
  0.148612 seconds (482.01 k allocations: 11.224 MB, 4.29% gc time)
-0.0011887017083507916

julia> @time modularity1(g,c) # new function
  0.003234 seconds (12.57 k allocations: 410.000 KB)
-0.00118870170835079

```

**Comment by sbromberger** [comment]
Ah, ok - so if the primary use case for this is sparse graphs, then this is great. Thanks. We need to figure out what's going on w/ codecov before I can merge it though.

**Comment by afternone** [comment]
The latest benchmarks:
```
julia> g = erdos_renyi(5000, 12497500) # full graph
{5000, 12497500} undirected graph

julia> c = rand(1:200, 5000); # partition just for test

julia> @time modularity(g,c) # new function
  0.183727 seconds (246.06 k allocations: 5.735 MB)
-0.00019900148029605973

julia> @time modularity4(g,c) # new function
  0.114786 seconds (9 allocations: 78.422 KB)
-0.00019900148029605922

julia> ####################################################
julia> g = erdos_renyi(10_000, 10_000_000) # large graph
{10000, 10000000} undirected graph

julia> c = rand(1:200, 10000); # partition just for test

julia> @time modularity(g,c) # old function
  0.733763 seconds (996.14 k allocations: 23.000 MB, 0.74% gc time)
-7.666561404000034e-5

julia> @time modularity4(g,c) # new function
  0.096177 seconds (9 allocations: 156.547 KB)
-7.666561404e-5

julia> #######################################################
julia> g = erdos_renyi(100_000, 10_000_000) # large dense graph
{100000, 10000000} undirected graph

julia> c = rand(1:1000, 100_000); # partition just for test

julia> @time modularity(g,c) # old function
 44.571594 seconds (20.15 M allocations: 461.652 MB, 0.22% gc time)
-4.840593594999856e-6

julia> @time modularity4(g,c) # new function
  0.189681 seconds (9 allocations: 1.526 MB)
-4.840593595e-6

julia> ########################################################
julia> g = barabasi_albert(100_000, 3) # large sparse graph
{100000, 499975} undirected graph

julia> c = label_propagation(g)[1]
100000-element Array{Int64,1}:
    1
    2
    3
    4
    5
    6
    7
    8
    9
   10
    ⋮
 1428
 2540
    1
  534
  600
 4529
 4147
    1
 3683
   27

julia> @time modularity(g,c) # old function
 49.911724 seconds (20.19 M allocations: 462.922 MB, 0.29% gc time)
0.32023045011657736

julia> @time modularity4(g,c) # new function
  0.031980 seconds (9 allocations: 1.526 MB)
0.3202304501165774
```

**Comment by sbromberger** [comment]
Whatever you did appears to have fixed codecov. Merging :)

Thank you!

**Pull request merged**
