### PR TITLE
fixing (height) count in push_relabel algorithm

### PR DESCRIPTION
**Pull request by IssamT**
See  #438

### CODE REVIEW

**Comment by sbromberger** [comment]
When this passes I'll revert #444 and merge this.

**Comment by IssamT** [comment]
Should I add the failing example as test?

**Comment by sbromberger** [comment]
Ooh. Actually, that's a great idea.

**Comment by sbromberger** [comment]
Let's get that test in :)

**Comment by sbromberger** [comment]
#449

**Comment by sbromberger** [comment]
Thank you, @IssamT!!!

**Comment by IssamT** [comment]
My thanks to you @sbromberger for being so reactive on all issues of this repository.

**Pull request merged**
