### PR TITLE
Replace SimpleGraph by AbstractGraph everywhere

### PR DESCRIPTION
**Pull request by juliohm**
As discussed in #527 , this replaces all occurrences of "SimpleGraph" by "AbstractGraph", it also makes the latter an abstract type instead of a Union type. All tests pass locally.

### CODE REVIEW

**Comment by juliohm** [comment]
What has happened in the `codecov/patch` check? What is this check about and where I can see file causing the decrease in coverage?

**Comment by sbromberger** [comment]
@juliohm - https://codecov.io/gh/JuliaGraphs/LightGraphs.jl/compare/211ff2c439c37de717d1478ea76861f5d01778ab...1040c58d0e340b80bc51ec22cb7a86815c08f48f/diff

**Comment by juliohm** [comment]
@sbromberger why is the coverage not reaching all those lines? The only change I made was SimpleGraph -> AbstractGraph

**Comment by sbromberger** [comment]
don't know, actually. I'm ok with approving, though.

S.

**Comment by sbromberger** [comment]
@jpfairbanks review and merge if you're good with this. Thanks.

**Comment by jpfairbanks** [comment]
Should we tag a version now 7.3? with the graph6 support.
Then we do the abstraction stuff for 0.8.0 and then 1.0 when julia hits 1.0?

**Comment by sbromberger** [comment]
yes. I'll tag 7.3 (using new attobot) and then we can merge abstraction.

**Comment by sbromberger** [comment]
On the 👍 side, attobot works well.
On the 👎 side, I realize I am completely confused by REQUIRES version checking. It took me 3 tries to get it right, despite @tkelman's gentle nudging and patience.

**Comment by sbromberger** [comment]
erm... did you merge the latest changes from master?

**Pull request merged**
