### PR TITLE
add a Project.toml file

### PR DESCRIPTION
**Pull request by jpfairbanks**
I think this should suffice for a project.toml file unless we need to specify compat or test dependencies.

### CODE REVIEW

**Comment by simonschoelly** [comment]
Maybe you have to replace `Pkg.add(pwd());` by `Pkg.add("LightGraphs");`

**Comment by fredrikekre** [comment]
>  unless we need to specify compat or test dependencies

Yea, you will have to add test dependencies.

**Comment by sbromberger** [comment]
yup: https://travis-ci.org/JuliaGraphs/LightGraphs.jl/jobs/519328334#L566

Where do we put the test dependencies?

**Comment by fredrikekre** [comment]
```toml
name = "LightGraphs"
uuid = "093fc24a-ae57-5d10-9952-331d41423f4d"

[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extras]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Base64", "DelimitedFiles", "Test"]

```

**Comment by sbromberger** [comment]
https://julialang.github.io/Pkg.jl/dev/creating-packages/#Test-specific-dependencies-in-Julia-1.2-and-above-1

**Comment by sbromberger** [comment]
@fredrikekre Statistics.jl is a test dependency. Do we move it down to `[extras]`?

**Comment by fredrikekre** [comment]
Ok sorry missed that, yea.

**Comment by sbromberger** [comment]
awesome. Thanks.

Also: we have submodules (see `Parallel`) that have their own dependencies. (see also #1197). Do we need to do anything special for them?

**Comment by fredrikekre** [comment]
>  Statistics.jl is a test dependency.

Actually that is not true, e.g. https://github.com/JuliaGraphs/LightGraphs.jl/blob/1c92ad8f8f88a58e04b4a933c0f705b105bbd942/src/LightGraphs.jl#L7 so should be moved back.

> Also: we have submodules (see Parallel) that have their own dependencies. (see also #1197). Do we need to do anything special for them?

No, dependencies for those are still dependencies for LightGraphs.

**Comment by sbromberger** [comment]
Gah. you're absolutely correct. Sorry. I had forgotten that `mean` moved out.

**Comment by simonschoelly** [comment]
Would it make sense, to group the dependencies that belong to the standard library (i.e Random, Distributed, SparseArrays, LinearAlgebra, Statistics) together in the texts, so that one sees, which dependencies are externally?

**Comment by sbromberger** [comment]
@fredrikekre thanks so much for the help!

**Pull request merged**
