### PR TITLE
Swap documentation for indegree and outdegree

### PR DESCRIPTION
**Pull request by juliohm**
This PR is documentation only.

### CODE REVIEW

**Comment by sbromberger** [comment]
Already fixed by #535...

**Comment by juliohm** [comment]
Missed it, sorry.

**Comment by sbromberger** [comment]
Erm. wait. Not so fast... This is different than #535.

**Comment by sbromberger** [comment]
Yup, sorry about that. You found a good bug :)

**Comment by iamed2** [comment]
Thanks! Just ran into this.

**Comment by sbromberger** [comment]
Yeah - sorry for the confusion surrounding this. We had multiple documentation errors with respect to degrees and I got confused.

**Pull request merged**
