### PR TITLE
bump datastructures

### PR DESCRIPTION
**Pull request by YingboMa**
Ping @sbromberger

### CODE REVIEW

**Comment by sbromberger** [comment]
This is based on the wrong branch. It needs to be on `v1.3.3`, not on `sbromberger/fix-corenum-1.3.3`.

**Comment by YingboMa** [comment]
Is it the `stable-1` branch?

**Comment by sbromberger** [comment]
no. It's `v1.3.3` (a tag). I *think* you can branch off of that. I can give it a try in a couple weeks if it's still a problem.

**Comment by YingboMa** [comment]
I don't think I can do that.
image

**Comment by YingboMa** [comment]
I did branch from the v1.3.3 tag though.

**Comment by YingboMa** [comment]
It's handled by #1473. It just needs a new release.

**Pull request closed without merging**
