### PR TITLE
redo pull request clique_percolation.jl

### PR DESCRIPTION
**Pull request by suzhu1988**
reopen pull request clique_percolation.jl

### CODE REVIEW

**Comment by sbromberger** [comment]
See #824 - already done.

**Comment by sbromberger** [comment]
This one seems to have passed the tests that the other one failed. Reopening.

**Comment by sbromberger** [comment]
Reopening because this one appears to be passing tests.

**Comment by sbromberger** [comment]
Oh, wait. No. Check the files. There are no changes due to my mess-up on your PR. #824 is the latest version of your code, @suzhu1988 . It's currently failing a test.

**Comment by suzhu1988** [comment]
I see, I'll deal with it as soon as possible.

**Comment by sbromberger** [comment]
Sorry for all the hassle. I messed things up when I tried to make some changes to the code. Many apologies.

**Pull request closed without merging**
