### PR TITLE
closeness, radiality, stress, distance

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by sbromberger** [comment]
Couple more after this

**Comment by jpfairbanks** [comment]
I'm worried about the Parallel tests drifting out of sync. maybe all the parallel test should just be Parallel.func(args) == func(args).

**Comment by sbromberger** [comment]
> maybe all the parallel test should just be Parallel.func(args) == func(args).

Doesn't work all the time (e.g., for `Parallel.dijkstra_shortest_paths`). But I can change it for the others.

**Comment by sbromberger** [comment]
Closing in favor of #962

**Pull request closed without merging**
