### PR TITLE
remove rng from type

### PR DESCRIPTION
**Pull request by matbesancon**
Starting to address #1237

### CODE REVIEW

**Comment by matbesancon** [comment]
ping @sbromberger here

**Comment by matbesancon** [comment]
bump

**Comment by sbromberger** [comment]
This sorta looks like a breaking change....

**Comment by matbesancon** [comment]
It changes an internal field, all methods can still be called in the same fashion

**Comment by sbromberger** [comment]
OK. Why are we doing this? (Sorry.)

**Comment by sbromberger** [comment]
OK, I think I get this. Instead of passing a seed to SBM, we're passing an instance of a random number generator (that itself can be seeded if the user wants)? If so, this makes sense in the context of what we want to do with RNGs in LightGraphs. 

Let me know?

**Comment by matbesancon** [comment]
> Instead of passing a seed to SBM, we're passing an instance of a random number generator

Yes, the goal is to let people choose the RNG when they call a method requiring randomness. The stochastic block model becomes just the declarative model and doesn't need a source of randomness itself

**Comment by sbromberger** [comment]
sounds great. Thanks. As soon as tests pass I'll merge. Appreciate your patience :)

**Pull request merged**
