### PR TITLE
sdata, and faster sharedarray construction

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by somil55** [comment]
```
```

**Comment by somil55** [comment]
On current master
```
julia> @benchmark parallel_multisource_dijkstra_shortest_paths(g,50:100)
BenchmarkTools.Trial: 
  memory estimate:  443.80 MiB
  allocs estimate:  1056636
  --------------
  minimum time:     2.255 s (13.14% GC)
  median time:      2.368 s (13.25% GC)
  mean time:        2.385 s (15.53% GC)
  maximum time:     2.564 s (20.39% GC)
  --------------
  samples:          11
  evals/sample:     1

julia> @benchmark parallel_closeness_centrality(g)
BenchmarkTools.Trial: 
  memory estimate:  536.83 MiB
  allocs estimate:  1312599
  --------------
  minimum time:     7.073 s (5.26% GC)
  median time:      7.379 s (7.04% GC)
  mean time:        7.347 s (6.95% GC)
  maximum time:     7.558 s (8.19% GC)
  --------------
  samples:          4
  evals/sample:     1

```

**Comment by sbromberger** [comment]
That doesn't make sense to me:
```
# this is what the PR does
julia> @benchmark SharedMatrix{Int}(30000,30000)
BenchmarkTools.Trial:
  memory estimate:  8.30 KiB
  allocs estimate:  172
  --------------
  minimum time:     94.309 μs (0.00% GC)
  median time:      117.674 μs (0.00% GC)
  mean time:        320.210 μs (3.19% GC)
  maximum time:     527.682 ms (7.20% GC)
  --------------
  samples:          10000
  evals/sample:     1

# this is what the current code does.
julia> @benchmark SharedMatrix{Int}(zeros(30000,30000))
BenchmarkTools.Trial:
  memory estimate:  6.71 GiB
  allocs estimate:  175
  --------------
  minimum time:     20.393 s (0.12% GC)
  median time:      20.393 s (0.12% GC)
  mean time:        20.393 s (0.12% GC)
  maximum time:     20.393 s (0.12% GC)
  --------------
  samples:          1
  evals/sample:     1
```

**Comment by sbromberger** [comment]
@jpfairbanks review please? this is pretty minor.

**Comment by sbromberger** [comment]
Thanks!

**Pull request merged**
