### PR TITLE
zero on graph type, not value

### PR DESCRIPTION
**Pull request by matbesancon**
`zero(G)` can be implemented instead of `zero(g::G)`, with the fallback `zero(g::G) = zero(G)`

### CODE REVIEW

**Comment by sbromberger** [comment]
This looks good to me but we're violating the (existing, unwritten, informal) convention that single type parameters are not surrounded by braces. (I personally don't like braces for type parameterization, but realize that this could be a violation of a new style guideline.)

**Comment by matbesancon** [comment]
> existing, unwritten, informal

Indeed I didn't even know about it. The problem with that is that you read things differently depending on whether there is one or more type specifications in the `where` clause

**Comment by sbromberger** [comment]
Yeah, it's not (yet) a huge deal. I'm not sure I can realistically enforce this convention anyway, especially since I don't even know whether there's an official style guideline around it.

**Comment by matbesancon** [comment]
it made me wonder, so I checked the manual, there doesn't seem to be anything around it. I think the manual is trying not be too strict about syntaxic style guide, without a formatter it's a pain to enforce

**Comment by sbromberger** [comment]
> there doesn't seem to be anything around it.

Not to get too off-topic here, but without a nice, strict style guide linting is a problem. I guess `gofmt` has spoiled me.

**Pull request merged**
