### PR TITLE
Ensure package is still tested on 0.3

### PR DESCRIPTION
**Pull request by IainNZ**

### CODE REVIEW

**Comment by sbromberger** [comment]
Do you still recommend this given that we're dropping support for 0.3 in the next minor release?

**Comment by IainNZ** [comment]
If you aren't doing any more work on 0.3, then no.

**Comment by sbromberger** [comment]
See specifically https://groups.google.com/d/msg/julia-dev/7dj29g_pHFY/FyjxXdMBCAAJ and following comments.

**Comment by sbromberger** [comment]
I will tag a final release that's guaranteed to build on 0.3. Thanks.

**Pull request closed without merging**
