### PR TITLE
Parallel Bellman Ford

### PR DESCRIPTION
**Pull request by SohamTamba**
I have 3 implementations of parallel bellman ford.

1. `parallel_bellman_ford_shortest_paths`: Thread safety is obtain using local memory (`active`, `dists`, `parallel`) for each thread. Thus, is faster than sequential but requires much more memory ( `nthreads()` times).

2. `parallel_bellman_ford_shortest_paths_2`: Does extra work compared to the sequential implementation but is thread safe. Instead of iterating over out-edges of `active` vertices, It iterates over `in-edges` of `outneighbors(g, active)` vertices. Thus, depending on how many vertices are `active`, could be much slower than the sequential algorithm.

3. `parallel_bellman_ford_shortest_paths_3`: Uses locking, but memory, allocations and runtime is FAR worse than the other 2, which makes me suspect a performance bug.

I noticed that the memory and allocations increase greatly with atomic operations.
I was hoping to get advice in case I missed something in [parallel_bfs.jl](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/traversals/parallel_bfs.jl).

*cc* @rohitvarkey  @jpfairbanks

### CODE REVIEW

**Comment by SohamTamba** [comment]
I chose `parallel_bellman_ford_2` (Made thread safe by operating on inward edges (and doing extra work))

Undirected Facebook Combined Graph: |V| = 4039  |E| = 88234
`seq_bellman_ford_shortest_paths`:   39.675 s (92898 allocations: 764.61 MiB)
`parallel_bellman_ford_shortest_paths`:   24.677 s (28290 allocations: 251.70 MiB)

Somehow, the memory useage reduces compared to the sequential algorithm.

I checked for race condition by comparing `dists` on graphs of size 1000.

**Comment by sbromberger** [comment]
@somil55 could you please review this first? Thanks.

**Comment by somil55** [comment]
@sbromberger Sorry I was traveling. I will review it today

**Comment by somil55** [comment]
@sbromberger The algorithm is fine but I was not sure of performance improvements.
@SohamTamba How scalable is this on large dense graphs?

**Comment by sbromberger** [comment]
Let's merge it and then we can discuss performance. That way we can get more eyes on it.

**Comment by sbromberger** [comment]
PS: @SohamTamba - I really like this coding style. Nice work!

**Pull request merged**
