### PR TITLE
WIP: Getting LightGraphs 0.7 ready

### PR DESCRIPTION
**Pull request by rohitvarkey**
This is an initial stab at getting LightGraphs ready for Julia 0.7.  

- [x] Add `using` statements for functionality moved into stdlibs from `Base`
- [x] Fix erroring and failing tests
- [ ] Remove deprecations - I'm hoping we can run Femtocleaner to automate this once https://github.com/mauro3/SimpleTraits.jl/issues/46 is fixed

As a happy coincidence I was able to find a fix a bug in base julia too! https://github.com/JuliaLang/julia/pull/25943

You should be able to get the following on the latest master
```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.3961 (2018-02-13 10:42 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 12964e839e* (0 days old master)
|__/                   |  x86_64-apple-darwin16.4.0

julia> Pkg.test("LightGraphs")
***Lots of deprecation warnings***
Test Summary: |  Pass  Total
LightGraphs   | 28781  28781
[ Info: LightGraphs tests passed
```

cc: @jpfairbanks

### CODE REVIEW

**Comment by jpfairbanks** [comment]
It looks like this fails on 0.6 because of SparseArrays. @sbromberger do you want to maintain compatability with 0.6 or just switch to 0.7 and update REQUIRE to prevent the new version from installing on 0.6?

**Comment by sbromberger** [comment]
The plan is to cut a final version that works with 0.6 and then bump REQUIRES to make master (and subsequent releases) 0.7-only.

Are we at the point where we freeze LightGraphs on Julia 0.6? I will cut a final version if so.

**Comment by mbesancon** [comment]
do we need to remove require? It won't be used by 0.7 anyway I believe, replaced by the TOML files

**Comment by jpfairbanks** [comment]
@sbromberger What is the status regarding this branch and #848?

**Comment by sbromberger** [comment]
We could probably merge the two branches. SimpleTraits just got fixed; I incorporated those changes in #848. Does this one fix the linalg issues?

**Comment by rohitvarkey** [comment]
> Does this one fix the linalg issues? 

I think so!

I'll rebase/merge this onto #848 and check.

**Comment by jpfairbanks** [comment]
Already merged into #848

**Comment by sbromberger** [comment]
@rohitvarkey see #850 - @jpfairbanks beat you to it.

**Comment by rohitvarkey** [comment]
Awesome! Thanks @jpfairbanks!

**Pull request closed without merging**
