### PR TITLE
Support tuples as dims parameter for method grid

### PR DESCRIPTION
**Pull request by karlwessel**
This implements #1260.

### CODE REVIEW

**Comment by sbromberger** [comment]
What happens with

```
grid(Int8(2), Int8(3))
```
and
```
grid(Int8(2), 3)
```
?

**Comment by karlwessel** [comment]
The first returns the same as the array version
```
julia> grid((Int8(2), Int8(3)))
{6, 7} undirected simple Int8 graph

julia> grid(Int8[2, 3])
{6, 7} undirected simple Int8 graph
```

The second errors with
```
julia> grid((Int8(2), 3))
ERROR: MethodError: no method matching widen(::Type{Signed})
Closest candidates are:
  widen(::Type{T}) where T at operators.jl:839
  widen(::T) where T at operators.jl:838
  widen(::Type{Int8}) at int.jl:687
  ...
Stacktrace:
 [1] widen(::Type{Signed}) at ./operators.jl:839
 [2] #grid#11(::Bool, ::typeof(grid), ::Array{Signed,1}) at LightGraphs.jl/src/SimpleGraphs/generators/staticgraphs.jl:454
 [3] (::getfield(LightGraphs.SimpleGraphs, Symbol("#kw##grid")))(::NamedTuple{(:periodic,),Tuple{Bool}}, ::typeof(grid), ::Array{Signed,1}) at ./none:0
 [4] #grid#12(::Bool, ::typeof(grid), ::Tuple{Int8,Int64}) at LightGraphs.jl/src/SimpleGraphs/generators/staticgraphs.jl:475
 [5] grid(::Tuple{Int8,Int64}) at 
LightGraphs.jl/src/SimpleGraphs/generators/staticgraphs.jl:475
 [6] top-level scope at REPL[7]:1
```
probably because collect returns an `Array` of  `Signed`
```
julia> collect((Int8(2), 3))
2-element Array{Signed,1}:
 2
 3
```

and the array version of `grid` does not know how to handle that. I'm not quite sure what the correct handling should be...

**Comment by sbromberger** [comment]
I think that's fine. This errors when we do the same thing with the array. Thanks for the additional checks.

**Comment by sbromberger** [comment]
Nice! Thanks again.

**Comment by karlwessel** [comment]
No problem! Thanks for reviewing and merging it this quickly!

**Pull request merged**
