### PR TITLE
doc fixes per Andy

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by sbromberger** [comment]
@hayd hey, getting a doc build error with this code:

```
seth@schroeder:~/dev/julia/wip/LightGraphs.jl/doc$ julia build.jl
 - 'about.md'
 - 'basicmeasures.md'
 - 'centrality.md'
 - 'distance.md'
 - 'generators.md'
 - 'gettingstarted.md'
 - 'index.md'
ERROR: LoadError: ParseError("extra token \"}\" after end of expression")
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/dev/julia/wip/LightGraphs.jl/doc/build.jl, in expression starting on line 298
```

**Comment by hayd** [comment]
Are you running that with 0.3?

Can you do me a favour and checkout this branch of Compat https://github.com/JuliaLang/Compat.jl/pull/126 and see if that works/same error when removing all this (Docile + string macros) and leave `using Compat`.

That is a weird error, will see if I can replicate. (ps. Docs will be much clearer once Lexicon features are available upstream :) )

**Comment by sbromberger** [comment]
@hayd it's 0.4....

**Comment by hayd** [comment]
ha, I think this is due to the }} here

```
GraphMatrices.CombinatorialAdjacency{Float64,LightGraphs.Graph,Array{Float64,1}}({10, 9} undirected graph,[1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0])
```

the error sucks though.

I have an easy fix, to be more strict about splitting on {{}}s...

---

BTW we're working on syntax so that you can soon write:

    ```julia
    julia> g = PathGraph(10)
    {10, 9} undirected graph

    julia> a = CombinatorialAdjacency(g)
    GraphMatrices.CombinatorialAdjacency{Float64,LightGraphs.Graph,Array{Float64,1}}({10, 9} undirected graph,[1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0])
    ```

as
```
{{repl
    > g = PathGraph(10)
    > a = CombinatorialAdjacency(g)
}}
```

**Comment by sbromberger** [comment]
Nice! What do I do to build docs in the meantime? :)

**Comment by hayd** [comment]
I will feed you a regex when I come up with one.

The below fixes this case I think, but is still not quite right (still has edge cases).
```
r"{{|}}  # becomes
r"^{{|\n{{|}}\s*$|}}\s*\n"
```

**Comment by hayd** [comment]
Pushed the change just in case you hadn't already done so. :)

**Pull request merged**
