### PR TITLE
Support AbstractGraphs

### PR DESCRIPTION
**Pull request by IainNZ**
This PR:

* Makes a new test that implements a new graph type that does not explicitly contain the edges and vertices
* Makes modifications to core.jl to make methods as general as possible. Note that these default methods might be horribly inefficient for a new abstract type, but that can be addressed on a per-method basis by the new type - they will at least work by default.
* Tightens up some of the methods in core.jl that were relying on internal fields
* Removes some methods from graphs, digraphs.jl that could be used for general graphs if directedness was checked.

I've just been going through the functions on the "basic measures" part of the docs, will get to more complicated measures before its done.

Note that a second step after this would be to consider a type hierachy that seperates abstract undirected and abstract directed graphs, like

```julia
abstract AbstractDiGraph
abstract AbstractGraph <: AbstractDiGraph
```
or
```julia
abstract AbstractGeneralGraph
abstract AbstractDiGraph <: AbstractGeneralGraph
abstract AbstractGraph <: AbstractGeneralGraph
```

which would eliminate the `is_directed` ifs that this introduces.

### CODE REVIEW

**Comment by IainNZ** [comment]
Test failure on 0.4 seems unrelated.

**Comment by IainNZ** [comment]
@yeesian

**Comment by jpfairbanks** [comment]
I like the idea and the GridGraph is a good example of the benefits of the AbstractGraph type. The interface you have should be enough to do most graph programing. It is also simpler than a fully parameterized graph type

**Comment by IainNZ** [comment]
Yeah I'm halfway through some of the traversal functions and they all just work. I don't think it'll take me long to finish up and then will be ready to merge.

**Comment by yeesian** [comment]
:+1:

Did you mean

```julia
abstract AbstractGraph
abstract AbstractDiGraph <: AbstractGraph
abstract AbstractUndirectedGraph <: AbstractGraph  # maybe in need of a better name
```

instead of vice-versa? But yeah, I'm definitely happy with the changes here.

**Comment by IainNZ** [comment]
No I meant what I said, and I think what you have there is my second one with different names. The first one I propose is a more controversial choice, but I think it has some logical merit.

**Comment by yeesian** [comment]
> The first one I propose is a more controversial choice, but I think it has some logical merit.

I apologise for being dense, but care to elaborate abit?

Here's yet another proposal:
```
abstract EdgeType

immutable Directed <: EdgeType end
immutable Undirected <: EdgeType end

abstract AbstractGraph{T <: EdgeType}
```

**Comment by IainNZ** [comment]
My first proposal is simply that undirected graphs are a special case of directed graphs (one where all edges and their reverse are in the graph).

**Comment by IainNZ** [comment]
Ready to merge

**Comment by sbromberger** [comment]
re: the travis failures: I'm not sure we even need DataStructures anymore. Let me test something.

**Comment by sbromberger** [comment]
Also - this looks great. Could I bikeshed a name for a second? It seems to me that "GraphTypes" would better be called "SimpleGraphs", since that's what the union describes. Comments?

**Comment by sbromberger** [comment]
There's a slight performance regression in `betweenness_centrality` which is my go-to measure. It's on the order of 2 seconds on my machine:

Original code:
```
julia> @time z = betweenness_centrality(g);
  92.737 seconds      (380 M allocations: 27230 MB, 6.23% gc time)

julia> @time z = betweenness_centrality(g);
  94.471 seconds      (380 M allocations: 27230 MB, 8.05% gc time)
```

New code:
```
julia> @time z = betweenness_centrality(g);
  93.664 seconds      (380 M allocations: 27230 MB, 6.21% gc time)

julia> @time z = betweenness_centrality(g);
  96.199 seconds      (380 M allocations: 27230 MB, 7.97% gc time)
```

**Comment by IainNZ** [comment]
SimpleGraphs works for me, I have no love for GraphTypes.

I wonder if that performance regression is due to the `if`s, thats the only change that could affect perf.

**Comment by sbromberger** [comment]
I'm not TOO worried about the performance regression, but I'm wondering whether having specialization on things like `neighbors` is better than checking directedness within the function itself.

**Comment by sbromberger** [comment]
@IainNZ I submitted a PR to your `ird/abstract` branch.

**Comment by sbromberger** [comment]
PS: re https://github.com/JuliaGraphs/LightGraphs.jl/pull/72#issue-91664280 and https://github.com/JuliaGraphs/LightGraphs.jl/pull/72#issuecomment-116379688 - 

```
abstract AbstractGeneralGraph
abstract AbstractDiGraph <: AbstractGeneralGraph
abstract AbstractGraph <: AbstractGeneralGraph
```

is my preferred approach. I did lots of timing tests at the very beginning looking at the impact of directedness on various functions, and found that keeping `DiGraph` separate from `Graph` and using specialization resulted in better performance across the board (as a related aside, my guess is that this lack of specialization is what's causing the minor perf regressions in the PR).

**Comment by IainNZ** [comment]
Lets go with that type hierarchy, that will allows us to remove the ifs

**Comment by IainNZ** [comment]
Ok, done. The diff is now much larger, but, no ifs!

**Comment by sbromberger** [comment]
Ok, after some great off-list discussion, I think what I'd like to do is the following:

```
abstract AbstractGraph
Graph <: AbstractGraph
DiGraph <: AbstractGraph

typealias SimpleGraph Union(Graph,DiGraph)
```
and not worry about the other abstractions. I am not convinced (yet?) that LightGraphs needs to support arbitrary graph types. It was created to provide a easy, fast way of performing operations on simple graphs. At this point I'm inclined to just say, "if you need a more complex graph structure, Graphs.jl is probably for you". To excerpt from an email I sent earlier, my thoughts on why arbitrary graph structures in LightGraphs is a bad idea right now:

1. People will use it without understanding the implications and get frustrated because it’s so slow (as I did with Graphs.jl - admittedly, I was using it without understanding it, and that’s likely what caused the problems);
2. I really don’t want to have to troubleshoot someone else’s custom code;
3. Any modifications we make will have to take into account the fact that custom graph types might behave very differently, and either not implement that functionality or do something that we wouldn’t normally do;
4. People will add functionality for their particular custom type of graph, and that won’t really benefit the core of LightGraphs (which are simple graphs as defined in the README) since they won’t be defined for those graphs, and in any case trying to understand them so we can merge PRs will lead us back to issue 2;
5. Nobody seems to need it right now; and if they do,
6. Graphs.jl is designed specifically for that sort of work.

So I'll keep this open for discussion until `bfsdfs` gets merged and then will create a new PR to make these changes.

**Comment by IainNZ** [comment]
@sbromberger actually the conclusion (to me) was
```
type Graph
  ...
end
type DiGraph
  ...
end

typealias SimpleGraph Union(Graph,DiGraph)
```
Because the decision was to specifically not support AbstractGraphs

**Comment by sbromberger** [comment]
I'm ok with that as well. Is there a difference, or is it just so that folks like me don't abuse `AbstractGraph` any more?

**Comment by IainNZ** [comment]
No performance difference, but keeping AbstractGraph implies that there is a use for it, so if there isn't going to be a use for it then I don't think it should be there.

**Comment by sbromberger** [comment]
Fair enough. Thanks.

**Comment by jpfairbanks** [comment]
Was I correct in understanding that this Abstract graph was an interface based abstraction so any type that defined a few core methods could inherit from AbstractGraph and thus be used. In contrast Graphs.jl is a generics based abstraction so your type had to fit into the construction provided?

**Comment by IainNZ** [comment]
I'll open a new PR with the simple fix.

**Comment by sbromberger** [comment]
Oh, I did it already. See #79.

**Comment by sbromberger** [comment]
...but I may have been a bit too aggressive since I renamed things like `AbstractGraphVisitor`. Let's use yours.

**Pull request closed without merging**
