### PR TITLE
Added fast PageRank computation via sparse linear system.

### PR DESCRIPTION
**Pull request by karjudev**
As agreed in #1430, added an alternative implementation of PageRank explained in [Del Corso, Gianna M., Antonio Gulli, and Francesco Romani. "Fast PageRank computation via a sparse linear system." Internet Mathematics 2.3 (2005): 251-273.](https://projecteuclid.org/download/pdf_1/euclid.im/1150474883) that uses the Gauss-Seidel iterative model.

Let me know what graphs can I use for benchmarking the algorithm.

### CODE REVIEW

**Comment by sbromberger** [comment]
Hi @karjudev - thanks for this. If you would mind using a graph from the `SNAPDatasets.jl` database for benchmarking, that'd be great.

**Comment by karjudev** [comment]
Apologies for the delay, the too many questions and the Git misuse, contribution newbie here...

Do I just need to add a `src/benchmark.jl` file with a benchmark using `SNAPDatasets.jl` and `BenchmarkTools` or something more is required?

**Comment by sbromberger** [comment]
No worries re: delay. I'm happy to say that it's even easier than adding things to benchmarks (we want to do this eventually but we're not there yet!):

Just take a moderately-sized graph from somewhere like `SNAPDatasets.jl` and run the existing pagerank code using BenchmarkTools' `@benchmark`, and then run your code on the same graph using BenchmarkTools, and then just drop the output in this PR as a comment. Also helpful is demonstration that the outputs are identical.

**Comment by sbromberger** [comment]
See, for example, https://github.com/JuliaGraphs/LightGraphs.jl/pull/1380#issue-396450513.

**Comment by sbromberger** [comment]
@karjudev just pinging on this - would be great to get it merged. Are you still having problems with the benchmarks?

**Comment by karjudev** [comment]
I'm really sorry but I had my final university exam session and I started my BSc thesis immediately afterwards so I didn't had a lot of free time.
The benchmark I took showed that this version didn't perform better with any of the graphs I've tried.
The algorithm was supposed to perform better than the standard power method on web-sized sparse graphs, but a threaded implementation would do better with such a use case.
I'm sorry I wasted your time, but this contribution is not going to positively affect the project in any way.
I beg you pardon, thanks for your effort to provide such a useful library.

**Comment by sbromberger** [comment]
No worries. Negative results are still good results. This wasn't a waste of time at all.

Can you share your benchmarks anyway? I'd like to rule out any possible issue with the test itself.

**Comment by sbromberger** [comment]
Also, there are things we can optimize in the code itself. If you're willing to keep going on this we can try to make it a bit faster.

**Pull request closed without merging**
