### PR TITLE
close #192

### LINKED ISSUE #192: Persistence consistency
Right now, there's a mix of functionality for the different file formats. Some are read only, some are read and write, others are write only (gexf)! Some can take a dict of graph objects for writing; some can only write one at a time.

Let's make this consistent.

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by vchuravy** [comment]
Maybe we could interface with FileIO?

**Comment by sbromberger** [comment]
@vchuravy see https://github.com/JuliaIO/FileIO.jl/issues/46 - I'd like to figure out a way but I don't want to step on anyone else's toes to do so.

**Comment by sbromberger** [comment]
This is a semi-breaking change: I have a deprecation in for `readgraph()` but that's about it. We might want to tag a new minor number. Thoughts?

cc: @jpfairbanks @CarloLucibello

**Comment by CarloLucibello** [comment]
Having something like
`load("filename")`
doesn't conflict with other packages, if not with julia itself?

Also, I'd like load functions to return a graph, and not a dictionary, when loading a single graph (which is by far the most common behaviour). I find the current behaviour quite annoying

**Comment by sbromberger** [comment]
The load function allows you to specify a graph name - if you do, it will return a graph instead of a dict.

**Comment by CarloLucibello** [comment]
>The load function allows you to specify a graph name - if you do, it will return a graph instead of a dict.

what about returning a graph also when the name is not specified nut there is just one graph in the file?

**Comment by sbromberger** [comment]
Then `load()` becomes type unstable.

**Comment by CarloLucibello** [comment]
>Then load() becomes type unstable.

I don't think this would impact performance

>Having something like
load("filename")
doesn't conflict with other packages, if not with julia itself?

what about this?

**Comment by sbromberger** [comment]
```
julia> load
ERROR: UndefVarError: load not defined
```

I'm not so concerned about collisions with other packages.

**Comment by CarloLucibello** [comment]
it is conflicting with FileIO.jl, I advise against doing that, we should go  with something like `loadgraph`. In general using such a generic name and signature for a very specialized function seems bad practice to me

**Comment by sbromberger** [comment]
They're in different namespaces. I don't really see an issue here. We don't care much when other packages reuse other functions (see, e.g., the `add_*` and `rem_*` functions that are in pretty much every graph-related (and even some non-graph-related) package).

FileIO is cool, but the reliance on a single registry that loads the first dependency that comes along seems to me to be a problem waiting to happen.

**Comment by CarloLucibello** [comment]
As a user I would expect conflict with other graph libraries, but not with generic i/o libraries.  What about implementing them as extensions to FileIO? like

```add_format(format"GRAPHML", (), ".graphml") ```

**Comment by sbromberger** [comment]
Adding to FileIO is in the plans assuming the registry issues can get resolved - as it stands I don't know how it's going to scale efficiently, particularly for common file formats. How do you handle CSVs, for example?

In any case, I'll reconsider `load()` / `save()` but I think we're solving a problem here that doesn't exist. The original methods extended `write()`, for example. There's nothing that would prevent us from doing that later if this became a problem.

**Comment by sbromberger** [comment]
I started looking at renaming but I can't come up with anything good. `loadgraph()` is a misnomer because it implies loading a single graph. Things like `loadg()` or `gload()` are not intuitive.

I think I'd like to just keep it `load/save` until we run into a problem, at which point you can reopen this and say "I told you so!"

**Comment by SimonDanisch** [comment]
I think FileIO integration would be very nice... Implementing a way to specify what IO library to prefer in FileIO is straight forward, but hasn't been on anyone's priority list high enough to actually implement it.
Considering type stability, I'm using 3 solutions so far:
```Julia
# overloading the constructor:
# not very clean semantically but gets the job done quickly
x = MyType("path_to_file.myext")
# the solution that I used in my first prototype of FileIO.
# it's semantically a bit cleaner ;)
x = MyType(file"path.ext")
# And the most straightforward way, working nicely with FileIO
x = load("path.ext", MyType)
```
I'd vote, that the official interface should be the last option, and anything else should be implemented by calling that version.
An IO library would implement it then like that:
```Julia
function load(path, typ=StandardType)
    if !(typ in SupportedTypes)
        error
    end
end

**Pull request merged**
