### PR TITLE
https://github.com/JuliaCI/Coverage.jl/issues/187#issuecomment-470198083

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by fingolfin** [comment]
This won't work if you only do it for Travis but not AppVeyor, as the results of the two are merged.

**Comment by fingolfin** [comment]
Aha, but it seems that while you have an `appveyor.yml`, AppVeyor still did not run on this PR?

**Comment by fingolfin** [comment]
Aha, but you did not actually ensure that it uses the latest Coverage.jl master branch -- so it is still using Coverge.jl 0.8.0, which does not know about `DISABLE_AMEND_COVERAGE_FROM_SRC`...

**Comment by fingolfin** [comment]
In fact, not even the master branch is enough, you'll need the code from that PR, resp. from my `mh/DISABLE_AMEND_COVERAGE_FROM_SRC` branch... But tell you what, we should just make a release with `DISABLE_AMEND_COVERAGE_FROM_SRC` in it, then testing this becomes trivial.

**Comment by sbromberger** [comment]
@fingolfin I just reran travis w/ codecov - does this look correct to you?

**Comment by fingolfin** [comment]
No... hmm, the coverage displayed by codecov for some reason meshes the results of two Travis build with two jobs each, see 
https://codecov.io/gh/JuliaGraphs/LightGraphs.jl/commit/b10cf534534cb660dbbd79ffd62d0fb29f4c113f/build

This is because once the branch is built as a PR, and once as branch of your repo. Now, looking at the build logs, three of the four jobs used Coverage.jl 0.9.0, but one used 0.7.0, and that is tainting the results. Perhaps a cache for installed packages was used and not properly reset on some of the builders?!?

Anyway, try restarting 
https://travis-ci.org/JuliaGraphs/LightGraphs.jl/jobs/503662768 and/or update this PR again for another rebuild.

**Comment by sbromberger** [comment]
@fingolfin restarted....

**Comment by fingolfin** [comment]
Both Julia 0.7 jobs are using Coverage.jl 0.7.0 (which is three versions behind); hmm, I just realize this is way behind, as 0.8.0 and 0.8.1 had been released some time ago.

Perhaps try disabling Julia 0.7 for the sake of testing this?

**Comment by sbromberger** [comment]
yup! see #1167. It fixed things.

**Comment by sbromberger** [comment]
I'm pretty sure we don't want this since it won't count functions that aren't executed at all. @fingolfin - do I have this right?

**Comment by fingolfin** [comment]
Yes, agreed

**Pull request closed without merging**
