### PR TITLE
Vertex Cover

### PR DESCRIPTION
**Pull request by SohamTamba**
cc @somil55

### CODE REVIEW

**Comment by sbromberger** [comment]
> which bikeshed color do you prefer? 

Blue.

I think that consistency dictates we use either a passed struct to designate the algorithm (the way we do with `loadgraph`), or use a symbol (the way we do w/ `adjacency_matrix`). Making this a kwarg is preferable if there's an obvious default.

**Comment by SohamTamba** [comment]
@sbromberger  can you take a look at this?

**Comment by sbromberger** [comment]
This looks good to me, but I'd like @jpfairbanks to take a look as well.

**Comment by IssamT** [comment]
Can we have some naming convention that helps recognizing heuristics from exact algorithms?

**Comment by SohamTamba** [comment]
@somil55 
`mapreduce` seems to have the same run time as the sequential code.
Should I use `@distributed` instead?

**Comment by somil55** [comment]
@SohamTamba Try benchmarking it using `@distributed [reducer]` for loop.

**Comment by sbromberger** [comment]
@SohamTamba this needs a conflict resolution. Also, what's the status? Are we ready for review? (cc @somil55 )

**Comment by SohamTamba** [comment]
@sbromberger  It's ready but can we merge #960 first?

Changes will have to be made to this PR based on how #960 ends up.

**Comment by SohamTamba** [comment]
@somil55 can you take a look?

**Comment by sbromberger** [comment]
@somil55 @jpfairbanks @SohamTamba - can we make a decision on this PR please? What needs to happen here? Thank you.

**Comment by SohamTamba** [comment]
@sbromberger  I think its ready.

I changed the interface to use structs as requested.

**Comment by sbromberger** [comment]
Congrats, @SohamTamba - and thanks for a great GSOC!!!

**Comment by SohamTamba** [comment]
@sbromberger 
Thanks alot :)

It was a great experience working with you'll

**Comment by matbesancon** [comment]
congrats @SohamTamba :)

**Pull request merged**
