### PR TITLE
Non visitor based maxadjvisit

### PR DESCRIPTION
**Pull request by somil55**

### CODE REVIEW

**Comment by sbromberger** [comment]
@somil55 thank you for this! Can you post some benchmarks? I'd imagine your code is significantly faster.

**Comment by somil55** [comment]
@sbromberger actually it's not ....I am working to remove `haskey` if possible using `dequeue_pair`
```
julia> @benchmark maximum_adjacency_visit(g)
BenchmarkTools.Trial: 
  memory estimate:  2.64 MiB
  allocs estimate:  95108
  --------------
  minimum time:     21.692 ms (0.00% GC)
  median time:      22.707 ms (0.00% GC)
  mean time:        23.022 ms (0.43% GC)
  maximum time:     27.430 ms (0.00% GC)
  --------------
  samples:          218
  evals/sample:     1
```
```
julia> @benchmark maximum_adjacency_visit_new(g,false)
BenchmarkTools.Trial: 
  memory estimate:  955.67 KiB
  allocs estimate:  42
  --------------
  minimum time:     17.032 ms (0.00% GC)
  median time:      17.525 ms (0.00% GC)
  mean time:        17.780 ms (0.05% GC)
  maximum time:     25.495 ms (0.00% GC)
  --------------
  samples:          281
  evals/sample:     1
```

**Comment by sbromberger** [comment]
That's 20% improvement right off the bat, and look at those allocations!

**Comment by somil55** [comment]
If I do something like 
```
    has_key = ones(Bool, nv(g))
    sizehint!(vertices_order, nv(g))
    @assert nv(g) >= 2

    # Setting intial count to 0
    for v in vertices(g)
        pq[v] = zero(T)
    end


    #Give vertex `1` maximum priority
    pq[one(U)] = one(T)

    #start traversing the graph
    while !isempty(pq)
        u = dequeue!(pq)
        has_key[u] = false
        push!(vertices_order, u)
        for v in out_neighbors(g, u)
            if has_key[v]
                ed = distmx[u, v]
                pq[v] += ed
```

Then result are a bit improved
```
julia> @benchmark maximum_adjacency_visit_new(g,false)
BenchmarkTools.Trial: 
  memory estimate:  965.61 KiB
  allocs estimate:  43
  --------------
  minimum time:     15.109 ms (0.00% GC)
  median time:      15.382 ms (0.00% GC)
  mean time:        15.513 ms (0.09% GC)
  maximum time:     18.442 ms (2.93% GC)
  --------------
  samples:          323
  evals/sample:     1
```

**Comment by sbromberger** [comment]
@somil55 - any way you can rework `mincut` so that it doesn't use visitors?

**Comment by somil55** [comment]
@sbromberger sure :)

**Pull request merged**
