### PR TITLE
eigenvector centrality

### PR DESCRIPTION
**Pull request by sbromberger**
@jpfairbanks - this one is really your area of expertise. Please review - I tested against NetworkX, but there may be corner cases where it fails, and I don't know about its efficiency.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
@sbromberger are you going to use the version I put in gitter? abs should be fine to save on ^2 and sqrt.

**Comment by sbromberger** [comment]
@jpfairbanks wait - the code you pasted on twitter was for eigenvector centrality of exponential subgraph?

**Comment by jpfairbanks** [comment]
I meant this part `eigenvector_centrality_2(g::AbstractGraph) = abs(vec(eigs(adjacency_matrix(g), nev=1)[2]))::Vector{Float64}`  no need to do norm when there is only one value.

**Comment by sbromberger** [comment]
Ah - I didn't see that. Let me update this PR.

**Comment by sbromberger** [comment]
@jpfairbanks - it appears to pass my tests but it needs your eyes on it please :)

**Comment by sbromberger** [comment]
Test failures related to https://github.com/JuliaStats/StatsBase.jl/issues/252

**Comment by sbromberger** [comment]
@jpfairbanks see https://travis-ci.org/JuliaGraphs/LightGraphs.jl/builds/228155282#L831-L848 - is this a problem with benchmarks?

**Pull request merged**
