### PR TITLE
fix type signature

### PR DESCRIPTION
**Pull request by matbesancon**

### CODE REVIEW

**Comment by matbesancon** [comment]
generalized the previous PR. The branches `stable-10` and `stable-1` are errors, they can be deleted

**Comment by sbromberger** [comment]
I don't know what branch this is applied on, though.

**Comment by matbesancon** [comment]
it's on 1.3,  so that we can merge it and release a 1.3.4 bugfix release without waiting for other big changes

**Comment by sbromberger** [comment]
The problem here is that when you created the `stable` branch, you didn't set up the CI tests for it, so we don't know whether it even compiles....

**Pull request merged**
