### PR TITLE
appveyor initial support

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by sbromberger** [comment]
Ugh. Appveyor is horrible. Closing this out.

**Comment by tkelman** [comment]
Any recollection what was the problem here?

**Comment by sbromberger** [comment]
It took 20+ minutes to test, the queues were too long, and it errored out with some other issue.

There's nothing OS-specific in LG at the moment so there's not a huge benefit to testing on OSes other than Linux. As it is our tests take ~10 minutes.

**Comment by tkelman** [comment]
anything that touches the filesystem can be os specific, leaving handles open accidentally etc. the speed is much better now than is used to be.

**Pull request closed without merging**
