### PR TITLE
second cut at laplacians for digraphs

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by sbromberger** [comment]
@jpfairbanks would you mind reviewing and writing tests? I can do the docs.

**Comment by jpfairbanks** [comment]
What do you think about these tests?

```julia
#that call signature works
inmat   = adjacency_matrix(g5, Int; dir=:in)
outmat  = adjacency_matrix(g5, Int; dir=:out)
bothmat = adjacency_matrix(g5, Int; dir=:both)

#relations that should be true
@test inmat' == outmat
@test all((bothmat - outmat) .>= 0)
@test all((bothmat - inmat)  .>= 0)

#check properties of the undirected laplacian carry over.
for dir in [:in, :out, :both]
    mat = adjacency_matrix(g5, Float64; dir=dir)
    @test isa(mat, SparseMatrixCSC{Float64, Int64})
    evals = eigvals(full(mat))
    @test all(evals .>= 0.0) # positive semidefinite
    @test minimum(evals) == 0.0 
end
```

**Comment by sbromberger** [comment]
Love them. Do they capture what you'd think is reasonable?

**Comment by jpfairbanks** [comment]
Yeah if some people start using it for their needs then we will find out
what else they expect to be true and can add to the tests

**Comment by sbromberger** [comment]
@jpfairbanks this test appears to fail for `dir=:both` in the latest code. Could you check please?

```
@test all(evals .>= 0.0) # positive semidefinite
```

**Comment by jpfairbanks** [comment]
Here is the patch
```
diff --git a/test/linalg.jl b/test/linalg.jl
index 5db9e4c..b4bee15 100644
--- a/test/linalg.jl
+++ b/test/linalg.jl
@@ -17,10 +17,12 @@ bothmat = adjacency_matrix(g5, :both, Int)

 #check properties of the undirected laplacian carry over.
 for dir in [:in, :out, :both]
-    mat = adjacency_matrix(g5, dir, Float64)
-    @test isa(mat, SparseMatrixCSC{Float64, Int64})
-    evals = eigvals(full(mat))
+    amat = adjacency_matrix(g5, dir, Float64)
+    lmat = laplacian_matrix(g5, dir, Float64)
+    @test isa(amat, SparseMatrixCSC{Float64, Int64})
+    @test isa(lmat, SparseMatrixCSC{Float64, Int64})
+    evals = eigvals(full(lmat))
     info("evals = $(evals)")
-    @test all(evals .>= 0.0) # positive semidefinite
-    @test minimum(evals) == 0.0
+    @test all(evals .>= -1e-15) # positive semidefinite
+    @test 1e-8 >= minimum(evals) >= -1e-15
 end
```

**Comment by jpfairbanks** [comment]
It was using the adjacency instead of the laplacian and also expecting to see the result of a floating point computation as 0.0 :unamused:

**Comment by sbromberger** [comment]
That works; thank you. I'm puzzled by the last test though: `@test 1e-8 >= minimum(evals) >= -1e-15` - what's the significance of being within those values? Would it be better to use `@test_approx_eq`?

**Comment by jpfairbanks** [comment]
The smallest eigenvalue should be close to zero. I just picked two numbers for the range without thinking to hard about it.  +1e-13 > minimum(evals) > -1e-13 should work.

**Comment by sbromberger** [comment]
OK, thanks. I used `@test_approx_eq_eps` with an epsilon of 1e-8. Is that precise enough?

**Comment by jpfairbanks** [comment]
that'll do

**Comment by sbromberger** [comment]
Cool. I think this will fail travis nightly because of https://github.com/JuliaLang/julia/issues/12063 but that might be fixed by now...

**Comment by sbromberger** [comment]
Yup! All fixed.

**Comment by jpfairbanks** [comment]
success!

**Comment by sbromberger** [comment]
Yup. it's been a good day for getting Julia stuff done... https://github.com/JuliaLang/julia/issues/12063 is fixed. BUT - there may be an issue with `Edge`s (at least in 0.3) per https://groups.google.com/d/msg/julia-users/bi9sBnlTswQ/njsRvLzgd5gJ - need to follow that.

**Pull request merged**
