### PR TITLE
Suzhu1988 master redo

### PR DESCRIPTION
**Pull request by sbromberger**
Redoing the clique percolation PR.

### CODE REVIEW

**Comment by omus** [comment]
Redo of: https://github.com/JuliaGraphs/LightGraphs.jl/pull/819

**Comment by sbromberger** [comment]
Looks like this is a legitimate test failure:

```
Clique percolation: Test Failed
  Expression: @inferred test_cliques(g, Array[[1, 2, 3], [1, 4, 5]])
```

**Comment by sbromberger** [comment]
cc @jpfairbanks @suzhu1988

**Comment by sbromberger** [comment]
Closing in favor of #826

**Pull request closed without merging**
