### PR TITLE
Sbromberger/inflate

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by sbromberger** [comment]
cc @jpfairbanks @GunnarFarneback

**Comment by sbromberger** [comment]
I will squash these commits. sorry about that.

**Comment by matbesancon** [comment]
is removing compression penalizing for some use cases? Isn't the resulting file too big for large graphs?

**Comment by sbromberger** [comment]
> is removing compression penalizing for some use cases? Isn't the resulting file too big for large graphs?

Generally no. Graphs are mostly limited by RAM, not by disk. When we're working with very large graphs (billions of edges) on large systems, we either 1) have enough disk space to save this native format, or 2) we're using StaticGraphs anyway, which has its own (JLD2-based) format.

**Comment by sbromberger** [comment]
That is to say: this is definitely a loss of functionality, but the impact should be minimal. And if someone *really* wants gzip-on-the-fly writes, we can add something in the new GraphIO bundle.

**Comment by jpfairbanks** [comment]
I'm still worried that this will break someone's workflow and how to help them adapt.

If the user has CodecZlib.jl installed and they pass a `GzipCompressorStream` as the first argument to  `savegraph` it should save a compressed version of the graph to that stream.

That way we give users a smooth upgrade experience and can avoid a "breaking" change.

In LGv1.2:
   - We REQUIRE Inflate.jl and not CodecZlib
   - So reading with compress=true or compress = false will work just like now.
   - Writing with compress=true will work if you have CodecZlib installed with a depwarn
   - If you do not have CodecZlib writing with compress=true will give you an error telling you to either install codeczlib or switch to passing a `GzipCompressorStream` as the first argument

That way users of 1.2 on machines that have CodecZlib will get depwarns.
Users without CodecZlib will be able to choose to modify their code or their install process.

I don't think the SemVer spec requires us to keep the same install process between minor versions so we could have say that for 1.2 you install LG by `]add LightGraphs; add CodeZlib`.

I don't think we can get rid of the ability to write compressed graphs entirely without incrementing the major version number. But, I do think we can require an additional install step if you want to use that functionality in v1.2.

**Comment by GunnarFarneback** [comment]
> * Writing with compress=true will work if you have CodecZlib installed with a depwarn

I'd be happy to be proven wrong but I don't think you can get that to work without CodecZlib either being in REQUIRE or being loaded by means of the Requires package. (It was easier to do tricks like this in 0.6 than it is in 1.0.)

**Comment by sbromberger** [comment]
Some random thoughts in response.

1) I don't think that breaking a for-now hypothetical workflow requires a major version change.

2) If we moved the old functionality to GraphIO.jl and directed anyone there who might be affected, then it seems to me that's "good enough".

3) I think the conditional use of CodecZlib would require Requires, which adds a dependency, which sort of defeats the purpose here.

**Comment by sbromberger** [comment]
Hey folks,

Absent any really compelling reason not to do this, I will be merging this PR and tagging a new minor release in the next few days.

**Comment by sbromberger** [comment]
Ref: https://github.com/JuliaGraphs/GraphIO.jl/pull/18

I will be merging this tomorrow unless there are any objections.

**Pull request merged**
