### PR TITLE
change ordering in strongly_connected_components

### PR DESCRIPTION
**Pull request by jpfairbanks**
breaks tests which depend on ordering.

### CODE REVIEW

**Comment by sbromberger** [comment]
Does this run faster?

**Comment by jpfairbanks** [comment]
It will for graphs with lots of small strongly connected components.

**Comment by sbromberger** [comment]
OK, sounds good to me. Can you fix the tests?

**Comment by sbromberger** [comment]
ping @jpfairbanks :)

**Comment by jpfairbanks** [comment]
I vaguely remember something about the tests actually needing this ordering. Will investigate further.

**Comment by jpfairbanks** [comment]
It was this function. `_karp_minimum_cycle_mean` that depends on this ordering and I didn't have a good way to fix it. Probably not worth changing unless someone else complains about performance.

**Comment by sbromberger** [comment]
Should we close this out?

**Pull request closed without merging**
