### PR TITLE
[WIP] Contiguous trait

### PR DESCRIPTION
**Pull request by matbesancon**
Trait for contiguous vertices, for which one must have `all(collect(vertices(g)) .== collect(1:nv(g)))`

### CODE REVIEW

**Comment by sbromberger** [comment]
I'm not sure this is generally useful. There are currently no graphs that do not require contiguous vertices. I know you're working on one, so that would bring the number of grap types that need this trait to 1.

Contrast with the "directed" trait - all graph types so far have both directed and undirected variants, and it is important that we be able to distinguish between them for common functions, so the trait sees wide use.

How else would this particular trait be used?

**Comment by matbesancon** [comment]
> There are currently no graphs that do not require contiguous vertices.

Might be a chicken and egg problem. Building new graphs may not be practical if we have this restriction.

As discussed in the issue and the blog post, some bits of the interface are redundant if this assumption is a strict requirement. This PR is a first step by specifying which algorithms that assumption, otherwise the contract of the interface is not respected since we use something more than the announced interface.

**Comment by matbesancon** [comment]
Making some of these algorithms as fast without relying on this assumption may be non-trivial, so for now at least it can be signaled at dispatch type: "there is currently no algorithm for that if you don't have contiguous vertices".

And then possibly write a (slower) implementation for non-contiguous, with a perf tip in the documentation

**Comment by sbromberger** [comment]
Yes, this is eventually where I see things going, and you're right that we need to take a first step, but I'm not sure that this is that time. There are other traits that would arguably be more important (`Has_Adjlist`, for example, or `IsModifiable`), but I've resisted creating them because there's really only one graph type that takes advantage of it, and it doesn't seem right to add complexity to LightGraphs to support a single graph type.

**Comment by matbesancon** [comment]
Not everything has to go the trait way, especially when a  reasonable fallback for a given method is possible. I think `IsModifiable` is a great candidate too, I was about to file an issue around this.
This could be a part of the doc "Characterizing your graph type"

**Comment by simonschoelly** [comment]
I too would like some traits :) Would be good for dealing with metadata and also some topological information, for example if a directed graph supports only outgoing edges or also incoming edges, or if it is a multigraph.

I would suggest, to look at the traits that we already have in Julia and see if we could use them for graphs.

Also, these decisions should not be rushed, but I think it would be important to have some experiments. Maybe it would be a good idea to create a package `GraphTraits.jl`, where we create some traits that can imported by other packages, and if these traits prove to be successful, they could be implemented in LightGraphs at some point. Or we we do it in an experimental submodule of LightGraphs.

If we do it this way, I am not yet sure, how we would overload the functions then. Maybe there is a way to force Julia to replace the definition of a function in a package from another package. Or we would declare `AbstractGraphWithTraits <: AbtractGraph` and then new graph types would have to inherit from this graph.

**Comment by sbromberger** [comment]
> Also, these decisions should not be rushed, but I think it would be important to have some experiments. Maybe it would be a good idea to create a package GraphTraits.jl

I think this would be an ideal use case for our `experimental` subpackage.

**Comment by matbesancon** [comment]
> I think this would be an ideal use case for our `Experimental` sub-package.

Agreed, but at the same time the interest of traits is to be used in current functions which assume some behaviour not encoded in the types. It's not like defining new self-contained features/functions/types

**Comment by matbesancon** [comment]
Go away bot

**Pull request closed without merging**
