### PR TITLE
Fix adjacency_matrix for all types

### PR DESCRIPTION
**Pull request by abhinavmehndiratta**
#1130 
For adjacency_matrix `@inferred` tests should probably be removed as the function is type unstable

### CODE REVIEW

**Comment by sbromberger** [comment]
Why are you removing `@inferred` from the tests? That's how we ensure type stability.

**Comment by abhinavmehndiratta** [comment]
> Why are you removing `@inferred` from the tests? That's how we ensure type stability.

the return type of adjacency_matrix , spmx depends upon the number of edges in the graph and function will be type unstable. Another option would be to use Int for storing column pointers all types but that would use more space.

**Comment by sbromberger** [comment]
My preference would be to use `Int` for storing the column pointer, or maybe passing the type into `_adjacency_matrix` so that it is type stable.

**Comment by abhinavmehndiratta** [comment]
> My preference would be to use `Int` for storing the column pointer, or maybe passing the type into `_adjacency_matrix` so that it is type stable.

Using Int will fail some tests like https://github.com/JuliaGraphs/LightGraphs.jl/blob/3f71acda3996c429f5df268649f05b79e85def62/test/linalg/spectral.jl#L101  Should I alter this test then ?

**Comment by sbromberger** [comment]
Let's see if we can pass the type in from `adjacency_matrix`. That way we can still have an efficient storage but we can preserve type stability.

**Comment by abhinavmehndiratta** [comment]
@sbromberger I modified the code to pass type from adjacency_matrix.I don't know if this is the right way to do this but it still seems to be type unstable.

**Pull request closed without merging**
