### PR TITLE
Adding NetworkViz integration to README and docs.

### PR DESCRIPTION
**Pull request by abhijithanilkumar**
NetworkViz support has been added to the README and the integration section in the docs. An example with a gif showing the working is also included. @sbromberger Do you need any further details to be added ?

### CODE REVIEW

**Comment by CarloLucibello** [comment]
doc/integration.md is auto-generated.

Please add those lines to doc/build.jl in the corresponding section, then run
```julia
julia doc/build.jl
```

**Comment by abhijithanilkumar** [comment]
@CarloLucibello I've made the change to `build.jl` and generated the docs.

**Comment by CarloLucibello** [comment]
thanks, LGTM

**Comment by sbromberger** [comment]
Thanks!

**Pull request merged**
