### PR TITLE
[WIP] deprecations for snake case

### PR DESCRIPTION
**Pull request by matbesancon**

### CODE REVIEW

**Comment by matbesancon** [comment]
closes #1221 without breaking thanks to deprecations

**Comment by sbromberger** [comment]
The new snake case functions need exporting :)

**Comment by matbesancon** [comment]
Woops that's right! I have some commits I need to push

**Comment by matbesancon** [comment]
@sbromberger the snake_cases are exported when they replaced an exported function

**Comment by sbromberger** [comment]
101 files changed. WOW. :)

**Comment by matbesancon** [comment]
yes sorry about that, I was hesitating to create separate PRs but they would really do the same thing, it's mostly a ctrl-F and replace

**Comment by matbesancon** [comment]
ha, Travis got hit by a non-deterministic error again, on nightly only, I restarted it

**Pull request merged**
