### PR TITLE
added generic simple graph constructor

### PR DESCRIPTION
**Pull request by chethega**
Useful for working with new graph types.

Needs tests and analogue for SimpleDiGraph. 

Please comment whether this is a desired feature. If not then I'll close instead of writing tests.

### CODE REVIEW

**Comment by sbromberger** [comment]
Would it make sense to limit the constructor to undirected `AbstractGraph`s? If so, we could make this a trait function.

**Comment by simonschoelly** [comment]
I like this function. I think we should not restrict it to undirected graphs, but maybe add a comment what the behavior for directed graphs is. After all we also have the constructor `SimpleGraph(g::SimpleDiGraph)`.

Might be worth considering also adding the constructor `SimpleGraph{T}(g::AbstractGraph), so one could specify the resulting eltype as an optional argument.

**Comment by sbromberger** [comment]
> Might be worth considering also adding the constructor `SimpleGraph{T}(g::AbstractGraph), so one could specify the resulting eltype as an optional argument.

I think that would get us in trouble since `AbstractGraph` is already parameterized. We don't really want to do type conversions in the constructor.

**Comment by simonschoelly** [comment]
Let's skip the parametrization for now, if we come to the conclusion that it is a good idea in the future, we can still add that without breaking the interface.

So should have some tests.

I don't think we should restrict `AbstractGraph` to directed graphs here, as there is also a case where one wants to make an undirected graph from a directed one.

**Comment by sbromberger** [comment]
@chethega were you planning on writing tests here? I'd like to merge this in the near future.

**Pull request closed without merging**
