### PR TITLE
add function adjlist

### PR DESCRIPTION
**Pull request by CarloLucibello**
since it was not exposed

### CODE REVIEW

**Comment by sbromberger** [comment]
Does `adjacency_list(g)` not do what you want? (See functions in `spectral.jl`.)

**Comment by CarloLucibello** [comment]
I cannot find `adjacency_list` anywhere. Maybe you meant `adjacency_matrix`?

**Comment by sbromberger** [comment]
Ah, sorry. I meant `fadj()` and `badj()`.... why aren't these acceptable? (They're the standard API elements for the adjacency lists of a graph.)

**Comment by CarloLucibello** [comment]
`fadj` and `badj` are not  exported. We use them internally but I think that `adjlist` or `adjacency_list` are  more intuitive names to export.

**Comment by jpfairbanks** [comment]
we use adjacency_matrix so I support adjacency_list for consistency over adjlist. However, it isn't actually an adjacency *list* it is an array of arrays. But maybe :ship: :boat:?

**Comment by sbromberger** [comment]
Not to be difficult, but I just don't see the need here. We already have the API-stable functions `fadj` and `badj` - all this PR would do is essentially typealias them. It adds almost no value.

I could see exporting `fadj` and `badj`, though, if that's a sticking point.

**Comment by jpfairbanks** [comment]
The larger question is whether we want people to design against the adjacency list representation or just some representation that supports `neighbors` and `edges`. I am inclined to keep the api smaller so that we can change things in the future without breaking user code. Breaking our own code that uses fadj and badj is a hassle but breaking user code is a headache.

**Comment by sbromberger** [comment]
wait. which is worse, a hassle or a headache? (I'm feeling both right now, but it's primarily due to the fact that I've been buried in javascript for the past 4 days.)

**Comment by jpfairbanks** [comment]
haha I backed off the word nightmare to headache to tone down the rhetoric but I guess I went too far.  breaking user code is worse.

**Comment by sbromberger** [comment]
yup. There are a few solid functions that form the LG API. `edges()`, `vertices()`, `ne()`, `nv()`, `fadj()`, and `badj()` are pretty much guaranteed stable. (I say "pretty much" because that's the contract I want to keep.)

**Comment by jpfairbanks** [comment]
Yeah if fadj and badj are part of the contract then they should be exported. I think a "Core API" section of the readme would help settle this discussion.

**Comment by jpfairbanks** [comment]
we have exported functions that are not "Core" like `maximal_cliques` and `local_clustering`.

Probably the core api is found in the source as 

```julia 
# core
export SimpleGraph, Edge, Graph, DiGraph, vertices, edges, src, dst,
in_edges, out_edges, has_vertex, has_edge, is_directed,
nv, ne, add_edge!, rem_edge!, add_vertex!, add_vertices!,
indegree, outdegree, degree, degree_histogram, density, Δ, δ,
Δout, Δin, δout, δin, neighbors, in_neighbors, out_neighbors,
common_neighbors, all_neighbors, has_self_loop, rem_vertex!,

```

**Comment by sbromberger** [comment]
> we have exported functions that are not "Core" like `maximal_cliques` and `local_clustering`

Well, yes - I would suggest that most exported functions in LG are not considered "core". It's a big library now.

> Probably the core api is found in the source as...

It's a good start and may help further resolution of https://github.com/JuliaGraphs/LightGraphs.jl/issues/278.

**Comment by CarloLucibello** [comment]
For compatibility reasons, I find myself often defining functions accepting an adjacency_list instead of a Graph, especially when I don't need to do fancy graph operations but just need to know the neighbors of each node.

Definitely some function returning an adjacency list should be exported, as we export adjacency_matrix. Exporting it does not mean we have to guarantee O(1) adjlist construction, altough we could. Notice in fact that adjacency matrix construction is not O(1). 

Regarding the naming we could just use `fadj` and `badj`, but I find them not particularly intuitive and see no problem in aliasing them or replacing them. Make your choice, as long as we have some (exported) function returning an adjacency list all is fine to me.

**Pull request closed without merging**
