### PR TITLE
fix deprecations

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by sbromberger** [comment]
@KristofferC thank you! One question: it appears to be rewriting the `@traitfn` signatures but as far as I know @mauro3 hasn't updated SimpleTraits to take advantage of the "new" `where` syntax. I'll do some investigating, but is it possible to override this syntax suggestion?

**Comment by KristofferC** [comment]
Ah, hmm. I thought Femtocleaner was very careful about leaving things inside macros alone. It doesn't seem to work here. I will have to look into it.

**Comment by KristofferC** [comment]
The old parametric syntax rewriter is explicitly set to be allowed in macro contexts. Is that intended @keno?

**Comment by Keno** [comment]
Yes, that's intended because there's a ton of macros on such definitions. We can have a blacklist where necessary, but if it's an actual function definition, it would be better to update the package that defines the macro.

**Comment by KristofferC** [comment]
Yeah, makes sense.

**Comment by sbromberger** [comment]
See https://github.com/mauro3/SimpleTraits.jl/issues/46 for the SimpleTraits macro issue.

**Comment by sbromberger** [comment]
Closing this out since we've made these changes in #848 . Thanks.

**Pull request closed without merging**
