### PR TITLE
has_path(g, v, v) now false

### PR DESCRIPTION
**Pull request by sbromberger**
...unless explicit self-loop exists.

### CODE REVIEW

**Comment by EricForgy** [comment]
The Zen question.

If we allow `PathGraph(1)` to exist, then we are allowing _trival paths_ with no edges and in that way, maybe `has_path(PathGraph(1), 1, 1)` should be `true` 🤔

**Comment by EricForgy** [comment]
I like your example in Slack:

```julia
julia> g = PathGraph(3)
{3, 2} undirected simple Int64 graph

julia> has_path(g, 1, 1)
false

julia> add_edge!(g, 1, 1)
true

julia> has_path(g, 1, 1)
true
```

So it is probably just worth noting in the documentation somewhere that you are explicitly excluding degenerate / trivial paths with no edges 😊

**Comment by sbromberger** [comment]
> So it is probably just worth noting in the documentation somewhere that you are explicitly excluding degenerate / trivial paths with no edges 😊

I think the new docstring does it adequately, though I'm open to edits:

> ### Implementation Notes
	`has_path(g, v, v)` will return `false` unless there is an explicit
	self-loop defined on vertex `v`. This is a change from previous
	versions.

**Comment by GunnarFarneback** [comment]
I don't like this dependency on self-loops. The way I see it, going from `v` to `v` via a self-loop is a cycle rather than a path, and I don't see why other cycles shouldn't be considered in that case. The two alternatives that make sense to me is to return true unconditionally (we reached the target just by starting at the source, a trivial path of length 0 visiting only `v`) or return false unconditionally (we don't accept trivial paths).

Or stated somewhat differently, a path from `v` to `v` via a self-loop would be a path with repeated vertices, but why should that only be allowed for the self-loop?

**Comment by jpfairbanks** [comment]
A path that goes from `v` to `v` via a longer path is a valid path. I think both the old state and the current state of the code get this wrong.

I think that all cycles should count as paths so if you have the graph`CycleGraph(n)` where `n > 2`, then there are two paths from `v` to `v`. One path is `v -> v+1 %n -> v+2%n ... v-1 % n` and the other path is `v -> v-1 % n -> v-2 % n ... v+1 % n`.

**Comment by sbromberger** [comment]
> the current state of the code get this wrong

```
julia> g = PathGraph(3)
{3, 2} undirected simple Int64 graph

julia> h = CycleGraph(3)
{3, 3} undirected simple Int64 graph

julia> has_path(g, 1, 1)
false  # this is correct

julia> has_path(h, 1, 1)
false  # this is not correct
```

Let's revert this until we get this fixed.

**Comment by jpfairbanks** [comment]
Yeah, if v is in a path to itself, that path is a cycle.

The bounces don't count because they reuse vertices and edges (in a directed graph, they only reuse vertices).

**Comment by sbromberger** [comment]
I don't know how to do this generally for undirected graphs unless we specifically track edges, which will clobber memory usage.

**Pull request merged**
