### PR TITLE
codecov

### PR DESCRIPTION
**Pull request by somil55**

### CODE REVIEW

**Comment by somil55** [comment]
@sbromberger @SohamTamba  Test on line 16 in `test/traversals/bfs.jl` was creating problem as for empty source vector the `for` loop in `gdistance` won't be covered. Removing that increases coverage to 100%

**Comment by somil55** [comment]
@SohamTamba That makes two of us. But try getting full coverage in #943.

**Comment by somil55** [comment]
@sbromberger That is difference between #966 and master right? The report at https://codecov.io/gh/JuliaGraphs/LightGraphs.jl/compare/7dfcb8132d51043bf12f80fa901d70c90bd7c864...f4e7f698e47ba69786d03c626143a7f8576a9b3a/tree/src says 100% for all

**Comment by sbromberger** [comment]
Yeah, I'm looking at 
https://github.com/JuliaGraphs/LightGraphs.jl/pull/966#issuecomment-409561761.

**Comment by somil55** [comment]
I am checking that.

**Comment by somil55** [comment]
@sbromberger nope. Coverage decreases. I tried multiple things but still, coverage doesn't increase. Seems to be a bug with codecov.

**Comment by sbromberger** [comment]
Closing this - we need to take a fresh look once other things happen.

**Pull request closed without merging**
