### PR TITLE
[breaking] Seed to rng

### PR DESCRIPTION
**Pull request by matbesancon**
As mentioned by @simonschoelly  in #1211, it would be interesting to let users provide their own RNG instead of having to use only MersenneTwister. This PR is thus replacing the seed keyword with rng, defaulting to GLOBAL_RNG

### CODE REVIEW

**Comment by simonschoelly** [comment]
I think, because of semantic versioning, we cannot simply make a breaking change. A solution would be, to allow both a seed & a rng parameter. (With some sanity checks, so that they cannot both be set at the same time). Then, if we want to get rid of `seed` in the future, we could start emitting deprecation messages, before we remove it completely in some further version.

**Comment by matbesancon** [comment]
Yes agreed. I think this PR comes too early. At the same time it would be nice to have a backlog for 2.0 to start. Allowing to set the two at the same time would be complex for the code, documentation and force numerous checks. We should use this only in the last version before 2.0 (like Julia 0.7)

**Comment by matbesancon** [comment]
@SohamTamba as mentioned on slack, there are some pieces here that would be worth considering for the parallel part (is the current implementation thread-safe, etc)

**Comment by matbesancon** [comment]
Yes this PR is a good excuse for starting that. @sbromberger I think we could extract the small refactoring from `Parallel` into a separate PR, this could be merged now

**Comment by sbromberger** [comment]
where do we stand on this? If it's truly non-breaking let's get it merged... if not, maybe we start a `2.0-dev` branch?

**Comment by matbesancon** [comment]
this one is definitely truly breaking, we can start a 2.0-dev, I'll rebase and change the PR branch target

**Comment by simonschoelly** [comment]
Couldn't we have both the `seed` and the `rng` keyword, so that we have some sort of transitition period? I would imagine having a function (just a sketch)

```
function getRNG(seed, rng)
   if seed != nothing
      .. print some deprecation warning
      return getRNG(seed)
   elseif rng != nothing
        return getRNG(seed)
    else
     return the global rng
   end
end
```

Then for some random function we have
```
function my_random_function(g; seed=nothing, rng=nothing)
    rng = getRNG(seed, rng)
   ... the usual stuff
end
```
Then we avoid breaking changes.

**Comment by matbesancon** [comment]
Sorry for the delayed answer. I think this would be a bit of a hassle to maintain both `seed` and `rng` in all required functions. This create massive PRs touching a big portion of the code base, just for legacy reasons

**Comment by sbromberger** [comment]
@matbesancon what should we do with this PR? If it is breaking, perhaps we create a `2.0-dev` branch? I'd like to move some of the new object-based dispatch stuff out of Experimental in any case :)

**Comment by matbesancon** [comment]
yes I think a 2.0 branch would be good, on which we should add deprecations so that we can prepare it as a pre-2.0 branch.
Then when the actual 2.0 is there, we just have to remove the deprecation macros

**Pull request closed without merging**
