### PR TITLE
Provide read_graphml

### PR DESCRIPTION
**Pull request by jiahao**
Reads in GraphML files and returns a LightGraph object.

Requires LightXML as an optional dependency

### CODE REVIEW

**Comment by jiahao** [comment]
What's this package's policy on `@doc` strings? I see some functions have them commented out. Can we introduce a dependency on Docile.jl to handle 0.3 compatibility?

**Comment by sbromberger** [comment]
> What's this package's policy on @doc strings? I see some functions have them commented out. Can we introduce a dependency on Docile.jl to handle 0.3 compatibility?

@jpfairbanks uses them; I don't :) They were commented out because they broke 0.3 without Docile. Given that docstring format is still up in the air for 0.4 I'm inclined to not have them right now.

**Comment by jiahao** [comment]
Ok, I commented them out.

**Comment by sbromberger** [comment]
This is awesome, btw. Thank you. I'll add some docs later.

**Pull request merged**
