### PR TITLE
Sbromberger/new shortest paths

### PR DESCRIPTION
**Pull request by sbromberger**
This is the renamed `sbromberger/aggregation` from #1239.

### CODE REVIEW

**Comment by sbromberger** [comment]
I'd appreciate a quick review. This is in Experimental and is non-breaking, but it's important to get it out there so people can start trying the new functionality. Thanks.

**Comment by sbromberger** [comment]
> Do you have a checklist of how you are grouping Algorithms into functions?

No, not yet. My next effort will probably be centrality measures, though, unless there's something more pressing?

**Comment by simonschoelly** [comment]
I think I've said everything that I had to say in the other PR, so I think this can be merged, and if we have  a better idea, we still can experiment with that later.

**Comment by sbromberger** [comment]
Given that @jpfairbanks is on vacation and @simonschoelly has approved, I'm going to merge this now.

**Pull request merged**
