### PR TITLE
WIP: benchmarks

### LINKED ISSUE #45: Build benchmarks into the repo
@jpfairbanks suggested in https://github.com/JuliaGraphs/LightGraphs.jl/pull/31#issuecomment-87030715 that we develop performance benchmarks into the repo (so that we can compare the effects of changes to data structures and algorithms). 

IMO, this is an excellent idea. I've opened this issue to figure out how we do this.

### PR DESCRIPTION
**Pull request by sbromberger**
Closes #45 

- [x] major benchmarks
- [ ] minor benchmarks
- [x] saving benchmarks
- [x] loading benchmarks
- [ ] comparing benchmarks
- [ ] alerting on regressions

### CODE REVIEW

**Comment by jpfairbanks** [comment]
What is holding this up? It is marked do not merge.

I don't think that we should wait to have all the benchmarks before merging anything.

**Comment by sbromberger** [comment]
Nothing in particular; I was hoping to have loading/saving done before we commit it though.

**Comment by sbromberger** [comment]
We definitely need load/save methods prior to doing anything with #541.

**Comment by sbromberger** [comment]
failure related to #542

**Comment by sbromberger** [comment]
Just discovered PkgBenchmarks so moved to that. It looks like it's easier for global comparisons.

**Comment by sbromberger** [comment]
@jpfairbanks @juliohm - I'd like to get this merged soon if possible. It's not 100% ready yet, but I think it's close enough to start trying it out.

**Pull request merged**
