### PR TITLE
Incidence Matrix Bufgix

### LINKED ISSUE #1388: [BUG] incidence_matrix deliver wrong values
Working for my Masterthesis and tried to work on a simple model to verify my algorithm. Found that the resulting incidence matrix is wrong, despite the fact the adjacency matrix is correct.

```julia
using LightGraphs, GraphRecipes
A_pap = [0 1 1 0 0;0 0 0 1 1; 0 0 0 0 1; 1 0 0 0 0; 1 0 0 1 0];
Ap = DiGraph(A_pap);
Dp = incidence_matrix(Ap);
graphplot(Ap, x= [3 1 5 1 5], y = [1 3 3 5 5], names=1:5)
```
bugreport

It easy to verify that the last column must be somethin like this:
```julia
Matrix(buildbyHand*)
5×8 Array{Int64,2}:
 -1  -1   0   0   0   1   1   0
  1   0  -1  -1   0   0   0   0
  0   1   0   0  -1   0   0   0
  0   0   1   0   0  -1   0  -1
  0   0   0   1   1   0  -1   1
```

But suprisingly we get
```julia
Matrix(Dpp)
5×8 Array{Int64,2}:
 -1  -1   0   0   0   1   1  -1
  1   0  -1  -1   0   0   0   0
  0   1   0   0  -1   0   0   0
  0   0   1   0   0  -1   0   1
  0   0   0   1   1   0  -1   0
```

Does anybody have a clue?

```julia
versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 7 2700X Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)
Environment:
  JULIA_EDITOR = "C:\Users\farid\AppData\Local\atom\app-1.45.0\atom.exe"  -a
  JULIA_HOME = C:\Users\farid\AppData\Local\Julia-1.3.0\bin
  JULIA_NUM_THREADS = 16
```
```julia
status LightGraphs
  [093fc24a] LightGraphs v1.3.1
  [37e2e46d] LinearAlgebra
```

### PR DESCRIPTION
**Pull request by birm**
fixes #1388
coauthor @abhinavmehndiratta

### CODE REVIEW

**Comment by birm** [comment]
Where has the spectral code gone post 1.3 anyway?

**Comment by sbromberger** [comment]
Thanks to both of you for the quick fix.

**Comment by sbromberger** [comment]
Paging @dilumaluthge - sorry to bother you, but do you have an idea how to fix the travis branch integration? This is affecting all PRs.

**Comment by DilumAluthge** [comment]
The `Travis CI - Pull Request` status is reported for all pull requests.

The `Travis CI - Branch` status is only reported for pull requests that are made from this repository. It is not reported for pull requests made from forks.

You should go to the Settings of this repo, go to the protected branch settings, edit the branch settings for master, and uncheck the checkbox for `Travis CI - Branch`.

**Pull request merged**
