### PR TITLE
modified Graph to remove badjlist (it's the same as fadjlist)

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by sbromberger** [comment]
cc @jpfairbanks @CarloLucibello this deserves a couple more eyes on it, please.

**Comment by sbromberger** [comment]
```
julia> g = Graph(1_000_000,10_000_000)
{1000000, 10000000} undirected graph

julia> Base.summarysize(g)
453212768

julia> g = Graph(1_000_000,5_000_000)
{1000000, 5000000} undirected graph

julia> Base.summarysize(g)
230606432
```

**Comment by jpfairbanks** [comment]
It passes the tests so it should be good. badj(g) == fadj(g) before so this looks like a transparent change.

**Comment by sbromberger** [comment]
OK, thanks. Merging.

**Pull request merged**
