### PR TITLE
change (in|out)degree to (in|out)_degree

### PR DESCRIPTION
**Pull request by sbromberger**
Ref #665

### CODE REVIEW

**Comment by jpfairbanks** [comment]
Why are we adding an underscore here? I like `indegree`. I feel like we shouldn't add an underscore when base is eliminating them. Not that we are bound to conform to Base's naming convention, but I think this is a lot of name churn without a clear benefit.

**Comment by sbromberger** [comment]
> Why are we adding an underscore here?
Because `in_neighbors`. See [this hot mess](https://discourse.julialang.org/t/naming-remove-all-underscores-to-matter-what/8549) for the rationale.

**Comment by jpfairbanks** [comment]
I know that the deprecation warning helps people deal with name changes, but this will effect almost all user code. I wish we had a better rational for deprecating the name than "to match stylistically." That is pretty disruptive.

If we are to rename something, then it is better to match inneighbors/outneighbors. Wolfram Mathworld says indegree is one word. 
> Weisstein, Eric W. "Indegree." From MathWorld--A Wolfram Web Resource. http://mathworld.wolfram.com/Indegree.html

As does wikipedia https://en.wikipedia.org/wiki/Directed_graph#Indegree_and_outdegree

 I think of `indegree` as a single concept. It is not the predicate `X is in degree` like `in_rectangle(shape, point)` would mean. We should get it right for the 1.0 release, but I think that means `indegree` and `inneighbors`. I did not find any evidence for `inneighbors` as the standard term, so I think there is room to say that `in neighbors` is two words so it should get an underscore.

**Comment by sbromberger** [comment]
I see what you're saying, but two counterpoints: both NetworkX and Boost call it `in_degree`.

**Comment by jpfairbanks** [comment]
That monograph looks legit, I trust the AMS on this.

NetworkX has a function  `non_neighbors(graph, node)` | Returns the non-neighbors of the node in the graph.

```python
raise CredibilityNotFoundException()
```

I think we can defend `indegree` and `inneighbors`

**Comment by sbromberger** [comment]
*We* need `non_neighbors` too!

**Comment by sbromberger** [comment]
ok. Closing this out. Keeping `indegree` and `outdegree` and deprecating `in_neighbors` and `out_neighbors` in favor of `inneighbors` and `outneighbors`.

I really want `hasselfloops` at some point though :) It has a nice ring to it.

**Pull request closed without merging**
