### PR TITLE
BenchmarkTools for Core

### PR DESCRIPTION
**Pull request by birm**
Following discussion in #1526 I figured I'd share what I believe could be useful format for benchmarking LightGraphs. Comments certainly welcome.

### CODE REVIEW

**Comment by sbromberger** [comment]
@birm - thanks for this. Do you expect to have time to create and launch a benchmarking suite for LG? If so, we should talk about making you a committer.

**Comment by birm** [comment]
At this point, I'm a bit reluctant to make promises of any sort, sorry to say. But I'll happily work on this in chunks, and do appreciate guidance on how you expect this to be structured or used.

**Comment by sbromberger** [comment]
Understood. :)

My high-level goal would be to have a set of benchmarks that we could run (via github actions) on all PRs to detect performance regressions. Beyond that, I don't really have any expectations right now :)

**Comment by sbromberger** [comment]
@birm - do you want me to go ahead and merge this now, or are you treating this PR as a WIP?

**Comment by birm** [comment]
I'm ok either way. Would you like me to migrate the other existing benchmarks in this PR? I wanted to start small to be able to incorporate feedback.

**Comment by sbromberger** [comment]
I agree we should start small. I can review later this week.

**Review by sbromberger — APPROVED** [review]

**Comment by sbromberger** [comment]
actually, I can review now since this is super low-risk. Thanks.

**Pull request merged**
