### PR TITLE
bump compat bounds from 1.3.3

### PR DESCRIPTION
**Pull request by ExpandingMan**
Bumped compat bounds, no errors.

Not entirely sure how this merge would work since there is no 1.3 branch (maybe there should be?).  Clearly it can't be merged into master.  Let me know if there's anything I can do to help us get it tagged.

### CODE REVIEW

**Comment by ExpandingMan** [comment]
Looks like I may have to close and re-open the PR to get it into a place where we can tag it.

I think you'll need to create a 1.3 branch for this.

Let me know when you have a way to merge it, and I'll re-create the PR.

**Comment by sbromberger** [comment]
Stand by. We'll try to get a `stable` branch that people can use for PRs. Sorry for the hassle.

**Comment by jpfairbanks** [comment]
I think this should probably try to merge into the `stable` branch which appears to have been created the last time someone wanted to bump compat

**Comment by sbromberger** [comment]
Yup. I had forgotten that we had already done this :) Please make PRs to `stable` and we'll cut a 1.3.4 from that soon.

**Comment by ExpandingMan** [comment]
Oops, I didn't even *notice* that branch.  Ok, PR incoming...

**Pull request closed without merging**
