### PR TITLE
made changes to bfs and vistors that didn't return bool

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by IainNZ** [comment]
Add a test?

**Comment by sbromberger** [comment]
Yes - I want to but I don't know how to suppress `println()` output, which is what I need to/should do with `traverse_graph_withlog()`. Ideas?

**Comment by IainNZ** [comment]
Could use an IOBuffer instead of STDOUT?

**Comment by sbromberger** [comment]
Ah, ok. I'll change that then, and have it default to STDOUT. Thanks.

**Comment by sbromberger** [comment]
Yup, the visitor actually accepts an `IO` type. However: https://github.com/JuliaLang/julia/issues/12050 .

**Comment by IainNZ** [comment]
Can't you make an IOBuffer() and then just throw it away?

**Comment by sbromberger** [comment]
Yes, of course. I was trying to do this with an IOStream() and not having much luck.

**Pull request merged**
