### PR TITLE
add savegml

### PR DESCRIPTION
**Pull request by CarloLucibello**

### CODE REVIEW

**Comment by sbromberger** [comment]
Is this gml or gexf?

**Comment by sbromberger** [comment]
Is there a reason we can't implement save on multiple graphs?

**Comment by CarloLucibello** [comment]
just my laziness. I'll add the multiple graphs save method

**Comment by sbromberger** [comment]
Oh, no worries :) It was more a question of "is there something preventing this?" 

Do you want me to merge this now or wait?

**Comment by CarloLucibello** [comment]
let's wait a few days, shouldn't be hard to implement

**Comment by sbromberger** [comment]
Assuming this passes tests, would you mind squashing?

**Comment by CarloLucibello** [comment]
omg I tried to squash but I messed up with git. I don't really know ho to clean up this mess. I keep getting errors with `git rebase`. Please merge this as it is, the "files changed" looks clean

**Comment by CarloLucibello** [comment]
Is there something withstanding the merge of this?

**Comment by sbromberger** [comment]
Just that there are 9 commits. I'll merge it but it would be better in the future to squash them.

**Pull request merged**
