### PR TITLE
Experiment: test LightGraphs with Pkg3

### PR DESCRIPTION
**Pull request by KristofferC**
I'm using this package as an experiment to try out if the Pkg3 in Base can handle current CI scripts. Sorry for the noise.

### CODE REVIEW

**Comment by mbesancon** [comment]
The current error seems to come from the way Pkg3 uses git if I'm not mistaken:
```
ERROR: GitError(Code:ERROR, Class:Invalid, reference 'HEAD' is neither a local nor a remote branch.)
```

**Comment by KristofferC** [comment]
Yep, definitely a Pkg3 problem :). It seems to work fine for Travis branch builds but not for Travis PR builds. Will have to figure out why.

**Comment by sbromberger** [comment]
Thanks, @KristofferC. Feel free to test away, and let me know if you need anything.

**Comment by KristofferC** [comment]
Ok so now things look better. The tests are running as they should

There are some test errors like

```
  Test threw exception ARPACKException(1)
  Expression: ((eigs(avgmat, which=:LR))[1])[1] ≈ 1.0
  ARPACKException: unspecified ARPACK error: 1
```

but I doubt those are Pkg3s fault?

**Comment by sbromberger** [comment]
@KristofferC - should we look at merging this at some point?

**Comment by KristofferC** [comment]
No need, this was just to test that things would work with the Pkg rename which is now merged. Thanks for letting me use this package for experimenting. It was very helpful.

**Comment by sbromberger** [comment]
My pleasure, and thanks for choosing LightGraphs.

**Pull request closed without merging**
