### PR TITLE
[Shortest Paths Algorithm] Bidirectional AStar

### PR DESCRIPTION
**Pull request by Shushman**
This PR implements and tests a simple bidirectional A* search algorithm from Goldberg et al "Computing Point-to-Point Shortest Paths from External Memory" (https://archive.siam.org/meetings/alenex05/papers/03agoldberg.pdf)

- The call to shortest paths is exactly the same as for AStar except with an `alg::ShortestPaths.BidirAStar`, which requires both forward and backward heuristics (defaults to zero). The search returns an `AStarResult` object with the path and distance.

- For the tests, I have the same tests as for A*. For further correctness, I informally tested the shortest path results on 100 different random queries to a road network graph and confirmed the paths were exactly the same as with A*.

### CODE REVIEW

**Comment by sbromberger** [comment]
Apologies for the delay. Would you mind posting some benchmarks and results? This looks pretty interesting.

**Comment by Shushman** [comment]
While doing the benchmarking, I realized there was actually was a bug that I've now fixed. I'm not sure what benchmarks would be most appopriate, but I compared to normal A* on a 2D Euclidean planning problem. Each vertex in the simple digraph corresponds to a 2D point in [0,1]^2, and the edge costs are the euclidean distances between the source and target. I'm just posting the script and numbers here, on my 2018 Macbook Pro with Julia 1.5.


```
using Random
using Statistics
using BenchmarkTools
using LinearAlgebra
using Infiltrator
using LightGraphs: ShortestPaths, SimpleDiGraph

const RNG = MersenneTwister(12345)

function main(num_verts::Int64=5000, num_edges::Int64=50000, num_trials=20)

    # Sample 1000 points in [0,1]^2 grid
    vset = rand(RNG, num_verts, 2)
    graph = SimpleDiGraph(num_verts, num_edges, rng=RNG)
    distmx = reshape( [norm(vset[i, :] - vset[j, :]) for i = 1:num_verts for j = 1:num_verts] , num_verts, num_verts)

    # For each trial, compute paths and times
    astar_times = Float64[]
    bidir_times = Float64[]

    for t = 1:num_trials

        source = rand(RNG, 1:num_verts)
        target = rand(RNG, 1:num_verts)

        # Euclidean heuristic; symmetric
        heuristic(u, t) = norm(vset[u, :] - vset[t, :])
        astar_alg = ShortestPaths.AStar(heuristic)
        bidir_alg = ShortestPaths.BidirAStar(heuristic, heuristic)

        astar_time = @elapsed ShortestPaths.shortest_paths(graph, source, target, distmx, astar_alg)
        bidir_time = @elapsed ShortestPaths.shortest_paths(graph, source, target, distmx, bidir_alg)


        push!(astar_times, astar_time)
        push!(bidir_times, bidir_time)
    end

    println("AStar Times - Mean: ", mean(astar_times)," ; Median: ", median(astar_times))
    println("Bidir Times - Mean: ", mean(bidir_times)," ; Median: ", median(bidir_times))
end

main()
```

And the results were

```
AStar Times - Mean: 0.0022700786000000002 ; Median: 0.001415515
Bidir Times - Mean: 0.00221759785 ; Median: 0.0016334255000000002
```

**Comment by sbromberger** [comment]
Sorry about this - we renamed some branches and this PR was closed. Would you mind rebasing on `master` and reopening? Thanks.

**Comment by Shushman** [comment]
What happened to `ShortestPathAlgorithm` and the style I adapted here?

**Comment by sbromberger** [comment]
Oh, right. This should be rebased on `development`, not `master`.

**Pull request closed without merging**
