### PR TITLE
Add comparison operators < and isless for AbstractSimpleEdge

### PR DESCRIPTION
**Pull request by simonschoelly**
Hope it is ok that I did not open an issue for such a minor thing. 
I added the operators `<` and `isless` for  `AbstractSimpleEdge`  (using lexical ordering). The main idea is, that now `sort` and `sort!` can be used on lists of edges.

### CODE REVIEW

**Comment by sbromberger** [comment]
We had this a while back and I didn't like it. We have `is_ordered` to test whether the source is less than the destination, but ordering of edges breaks down in the general case – there's no intuition that `Edge(3,10)` should somehow be less than `Edge(5,1)`.

**Comment by sbromberger** [comment]
(and it's perfectly ok to open a PR directly; we can have conversations here. But where substantial work is involved, you might want to solicit opinions before you start coding – which wasn't the case here.)

**Comment by simonschoelly** [comment]
Would it be ok then to take out the `<` operator and just leave in `isless`? That should be enough for `sort` to work.

**Comment by simonschoelly** [comment]
My use case here was creating graphs, where it is easier to check for duplicates if the list of edges is already sorted. Of course it is also possible to do that with
```
sort!(edge_list, by=Tuple)
```

**Comment by sbromberger** [comment]
> My use case here was creating graphs, where it is easier to check for duplicates if the list of edges is already sorted. 

Are you using `add_edge!`? Because it does the check for you.

**Comment by sbromberger** [comment]
Having given this some more thought, I can't agree that this is generally useful or desirable. In certain specific cases, it might make sense to define an ordering to edges, but as long as we do not distinguish between edges and arcs (that's a huge can of worms), there will be cases that are inconsistent.

If we don't absolutely need this for some core LG functionality, I'm inclined to suggest that packages that need to define some arbitrary ordering of edges should do so locally.

**Comment by sbromberger** [comment]
@simonschoelly - I've thought about this some more over the past week and still haven't resolved my problems with specifying an explicit ordering for edges. Do you mind if we close this out unmerged?

**Comment by simonschoelly** [comment]
I did not use `add_edge!`, because I was writing a constructor for a custom graph type.
But then it is no something that is very important, as one always can pass a sort-by function to `sort`, so I don't mind if this is not getting merged.

**Pull request closed without merging**
