### PR TITLE
integration of GraphMatrices

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by jpfairbanks** [comment]
The tests as currently exist show that you can construct the derived matrices (Laplacian, Normalized Laplacian, etc) and that you can use the eigensolver. There might be more than necessary but we definitely want to test the constructors and the arithmetic. I caught a bug where `CombinatorialAdjacency(g)` was not casting the indegrees to floats because when I went to construct the NormalizedLaplacian, the test failed. Also the tests of the that call `eigs` ensures that all of the other operators (size, sum, ndims, length, etc) work properly.

**Comment by sbromberger** [comment]
> the tests of the that call eigs ensures that all of the other operators (size, sum, ndims, length, etc) work properly

but whatever was in there wasn't providing Coveralls coverage (I created explicit tests because I was puzzled that they weren't being called anywhere).

I'll throw in some more tests but I'm not sure we need the full suite. Everything's going in linalg.jl, which I think will need to be renamed to spectral.jl at some point.

**Comment by sbromberger** [comment]
W00. GraphMatrices integration was the :100: th commit!

**Comment by jpfairbanks** [comment]
woohoo!

**Comment by sbromberger** [comment]
Tagged as 0.3.2.

**Pull request merged**
