### PR TITLE
Use a global test set to simplify and condense test output

### PR DESCRIPTION
**Pull request by jgoldfar**
Wrapping all of the tests in one test set reduces noise in the test output. I looked through PRs and issues and didn't see a reason why it wasn't written this way, but feel free to close if there's a reason why it's not done this way.

### CODE REVIEW

**Comment by sbromberger** [comment]
We did individual test sets so we could see where failures were occurring. I'm very interested in the output of this PR, though.

**Comment by jgoldfar** [comment]
Failures should still be reported separately for each test set by default AFAIK; the output is only reduced if no failures occur in sub-test-sets

**Comment by jgoldfar** [comment]
Looks like one of the random graph tests escaped some kind of tolerance? Looking to the Travis log does show how this change effects the test output with failing tests.

**Comment by sbromberger** [comment]
I *really* like this. Can you do me a favor and change 

https://github.com/JuliaGraphs/LightGraphs.jl/blob/928bc5a868b2146a297f975f7e059445c79c8cb1/test/core.jl#L10

to, say, `0` and let's run this to see what a failure looks like? (We'll change it back before merging.)

**Comment by sbromberger** [comment]
PS: if we can get this done today it'll go in with v0.9.0 (same with #600).

**Comment by jgoldfar** [comment]
The previous CI run has a failure. https://travis-ci.org/JuliaGraphs/LightGraphs.jl/builds/225376321

**Comment by sbromberger** [comment]
Perfect. Thanks. One final review and then a merge :)

**Pull request merged**
