### PR TITLE
first cut at laplacians for digraphs

### PR DESCRIPTION
**Pull request by sbromberger**
cc @jpfairbanks

### CODE REVIEW

**Comment by jpfairbanks** [comment]
Am I understanding the intent correctly?

adjacency(g, t;:in) would give you the matrix where `A[i,j] = one(t)` if there is an edge from `j` to `i`.
`:out` is the transpose of that, and `:both` is if there is an edge from `j to i` and another edge `i to j`?

If so, we need to use something other than `neighbors` for the `:both` case because `neighbors` returns `fadj` and thus produces the same result as `:out`.

Also if that is the intent, an `:either` option would make sense to give the adjacency matrix of the undirected graph.
 
I think it is a good idea to have an optional parameter for the direction of the adjacency_matrix.

**Comment by sbromberger** [comment]
So: `fadj` works for "in+out neighbors" in undirected graphs, but there's not currently an equivalent for directed graphs. (There used to be, called "all_neighbors"). What do you think of making `neighbors(g::DiGraph, v::Int)` a union of the fadj and badj instead of `out_neighbors` as it is now?

How is "neighbors" of a vertex in a directed graph defined?

**Comment by jpfairbanks** [comment]
That would require taking a look at what people using directed graphs
think. I don't think it matters in the long run as long as its documented
and consistent. My preference is for neighbors to do both and out_neighbors
an in_neighbors to give their directed edges. It feels like an
inconsistency to say `DirectedGraph` and then have methods that support
both directions but it is convenient.

**Comment by sbromberger** [comment]
I think, unless you object, I'll go with `all_neighbors()` for DiGraphs which will be the union of in_neighbors and out_neighbors, and then use that for Laplacians. What do you think?

**Comment by jpfairbanks** [comment]
> I think, unless you object, I'll go with all_neighbors() for DiGraphs
which will be the union of in_neighbors and out_neighbors, and then use
that for Laplacians. What do you think?
>
There is another issue to consider. What order will all_neighbors use? In
then out, out then in, sorted by vertex number, deduplicated?

Maybe neighbors should be the intersection and all_neighbors should be the
union both in an arbitrary order?

If you want to store an undirected graph in a directed graph type you can
just make sure to always insert both directions. Then degree and neighbors
will function as usual for you.

**Comment by sbromberger** [comment]
> What order will all_neighbors use?

None of the `neighbors` functions guarantee ordering. They do guarantee deduplication, which is why I'd use `union` on in and out.

**Comment by sbromberger** [comment]
Closing out in favor of #89.

**Pull request closed without merging**
