### PR TITLE
Implement LightGraphs.Datasets

### LINKED ISSUE #186: WIP: Datasets
Now that we've got our own github org, it may make sense to move smallgraphs out from LightGraphs and into its own module. The graphs are reasonably stable (despite an enhancement we made last week - see #178 / #181 ). Ref #185 for additional discussion.

Two approaches:

1) keep Smallgraphs as a submodule of LightGraphs (similar to how @andrewcooke does ParserCombinator)
2) move Smallgraphs into its own peer package.

I'm leaning towards 1). The submodule would be inextricably linked to LightGraphs, since we're calling `unsafe_add_edge!()` which is unlikely to exist in other graphs packages. Plus, we need smallgraphs for tests, so we'd have to REQUIRE smallgraphs in any case.

Thoughts?

### PR DESCRIPTION
**Pull request by sbromberger**
This is the PR associated with #186 

Closes #186.

### CODE REVIEW

**Comment by CarloLucibello** [comment]
I would leave the most commonly used constructors (eg. 
+CompleteGraph, StarGraph, PathGraph, WheelGraph, CycleGraph,
+CompleteBipartiteGraph, CompleteDiGraph, StarDiGraph, PathDiGraph,
+WheelDiGraph, CycleDiGraph) in the LightGraphs module

**Comment by sbromberger** [comment]
@CarloLucibello why?

**Comment by CarloLucibello** [comment]
so that one doesn't need to import a submodule to use them. It's also kinda coherent, in LG some utility constructors and in Datasets you have real data and some famous non-trivial artificial graph

**Comment by sbromberger** [comment]
OK, yep, I think you convinced me.

**Comment by sbromberger** [comment]
@CarloLucibello: does this do what you were expecting?

@jpfairbanks - please make sure I migrated your RoachGraph stuff properly (it's now in generators.jl).

**Comment by sbromberger** [comment]
Also: I guess the rule is this: any graph generator that requires arguments (e.g., number of edges or vertices) will go in generators.jl; any graph generator that's static will go into Datasets.

**Comment by CarloLucibello** [comment]
>Also: I guess the rule is this: any graph generator that requires arguments (e.g., number of edges or vertices) will go in generators.jl; any graph generator that's static will go into Datasets.

sounds reasonable

**Comment by sbromberger** [comment]
@CarloLucibello @jpfairbanks final review please? Thank you.

**Pull request merged**
