### PR TITLE
deterministic random functions

### PR DESCRIPTION
**Pull request by matbesancon**
make all functions deterministic by using the seed keyword consistently

### CODE REVIEW

**Comment by simonschoelly** [comment]
I very much like the changes in this PR.
Perhaps this would also be a good opportunity to think about how we could support arbitrary random number generators instead of just a seed. Or maybe I should do that in another issue.

**Comment by matbesancon** [comment]
Yes I ways thinking about this, I kept the changes light to bring the discussion before changing everything.
One minor gripe with rng: rng is mutated by sampling from it, so it needs to be the first argument generally. But since it's also optional, it requires writing two functions:
```
f(rng, x, y)
f(x, y) = f(Random.GLOBAL_RNG, x, y)
```

A good compromise would be to put the rng as keyword, with default as `GLOBAL_RNG`

**Comment by matbesancon** [comment]
@simonschoelly I am going to put this in another PR, but realized mid-way that it will be a breaking change, and thus cannot appear before LightGraphs 2.0 (I think?)

**Comment by matbesancon** [comment]
seems good for merging

**Comment by matbesancon** [comment]
bump

**Pull request merged**
