### PR TITLE
Methodize centrality

### LINKED ISSUE #1308: Methodize centrality
Do for centrality what we just did for shortestpaths, and make centrality its own module.

### PR DESCRIPTION
**Pull request by birm**
closes #1308

Work in progress.
Starting small, working out from there...

### CODE REVIEW

**Comment by sbromberger** [comment]
I appreciate the help, but I'm doing this already in #1318 and in the 2.0.0-dev branch....

**Comment by sbromberger** [comment]
@birm - let's coordinate on the work you're doing so we're not conflicting. There's lots of stuff to do :)

**Comment by birm** [comment]
Okay, any thoughts?

**Comment by sbromberger** [comment]
Sure. If you're up for a challenge, #1323. #1287 is also a good one (less difficult).

For each of these, base on the `2.0.0-dev` branch. All enhancements should be there. Any bugfixes we'll need to cherry-pick or backport, so let's talk if you tackle a bug report.

**Comment by sbromberger** [comment]
Forgot to add: if you decide to work on either of those (or any other open issue), post in the issue that you're taking it so that others know it's spoken for.

**Pull request closed without merging**
