### PR TITLE
cherry pick bellman-ford test

### PR DESCRIPTION
**Pull request by sbromberger**
test for negative cycle error.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
Should this error get thrown on a cycle that sums to 0? We should test for that too.

**Comment by sbromberger** [comment]
What happens with a zero cycle? error or pass?

**Comment by jpfairbanks** [comment]
I don't know yet, never tried it! 🎲 🎲

**Comment by sbromberger** [comment]
Then let's keep things as-is for now :)

**Comment by jpfairbanks** [comment]
Let's merge #551 into this and then them both into master?

**Comment by sbromberger** [comment]
Sounds ok to me. I'll review #551, you review this one?

**Comment by sbromberger** [comment]
Then I'll cherry-pick (probably manually) to the abstract branch.

**Comment by jpfairbanks** [comment]
ok

**Pull request merged**
