### PR TITLE
Queues

### PR DESCRIPTION
**Pull request by harryscholes**
So these are some other algorithms that use queues, or, in some situations, deques. I've replaced the `Vector` implementations with `Queue` or `Deque`.

Is anyone aware of any other places where these data structures could be used?

NB I had to do the `bipartite_map` commits on the GitHub website because my local machine's filesystem is case-insensitive, so it didn't like the LightGraphs codebase structure.

### CODE REVIEW

**Comment by sbromberger** [comment]
> my local machine's filesystem is case-insensitive

Ugh. I was afraid of this; sorry for the hassle. This will go away in 2.0.

**Comment by sbromberger** [comment]
We need to hold off on this for a bit since I'm in the middle of moving the `ShortestPaths` code from `Experimental` to its own module, and this should be integrated into that new structure.

**Comment by harryscholes** [comment]
Cool. Give me a shout when those bits are done!

**Comment by sbromberger** [comment]
Will do. Thanks!

**Comment by sbromberger** [comment]
in the meantime, can you rebase onto master? We moved `shortestpaths` to `shortestpaths13`.

**Comment by harryscholes** [comment]
I've rebased and I think (🤞) it worked properly

**Comment by sbromberger** [comment]
@harryscholes I think we might be ready to revisit this if you have some time. Please limit any changes to the new module-based code (that is, code in directories beginning with capital letters) and NOT in any directory ending in `13`.

**Comment by harryscholes** [comment]
Hey Seth, I've just looked over these changes again and I think it all looks good. I also don't see any other obvious places where `Queue` or `Deque` could be used in the codebase.

**Comment by sbromberger** [comment]
@harryscholes lots has changed in the menatime, though. Can you rebase onto the master branch?

**Comment by harryscholes** [comment]
Rebased :)

**Comment by sbromberger** [comment]
@harryscholes thanks! Just to confirm - you've seen performance improvements with these changes?

**Comment by harryscholes** [comment]
`bipartite_map` benchmarks for the vector- and queue-based implementations. Vector-based implementation is on branch #1385, which is master with a tweak in `bipartite_map` that removes some dead code and improves performance.

```julia
julia> @btime LightGraphs.Traversals.bipartite_map($g)
4.260 s (135 allocations: 3.04 MiB)

julia> @btime bipartite_map_queue($g)
3.966 s (200 allocations: 2.36 MiB)
```

Script:

```julia
using LightGraphs, DataStructures, BenchmarkTools

function bipartite_map_queue(g::AbstractGraph{T}) where T
    nvg = nv(g)
    if !is_directed(g)
        ccs = filter(x -> length(x) >= 2, connected_components(g))
    else
        ccs = filter(x -> length(x) >= 2, weakly_connected_components(g))
    end
    seen = zeros(Bool, nvg)
    colors = zeros(Bool, nvg)
    Q = Queue{T}()
    @inbounds for cc in ccs
        s = cc[1]
        enqueue!(Q, s)
        while !isempty(Q)
            u = dequeue!(Q)
            for v in outneighbors(g, u)
                if !seen[v]
                    colors[v] = !colors[u]
                    enqueue!(Q, v)
                    seen[v] = true
                elseif colors[v] == colors[u]
                    return Vector{UInt8}()
                end
            end
        end
    end
    return UInt8.(colors) .+ (one(UInt8))
end

n = 20_000
g = complete_bipartite_graph(n, n)

@btime LightGraphs.Traversals.bipartite_map($g)
@btime bipartite_map_queue($g)
```

**Comment by harryscholes** [comment]
No speed up with `SPFA` from what I can tell :(

```julia
julia> @btime shortest_paths($g, 1, $distmx, $alg)
260.543 ms (26 allocations: 4.30 MiB)

julia> @btime shortest_paths_queue($g, 1, $distmx, $alg)
271.346 ms (206 allocations: 3.08 MiB)
```

Script:

```julia
using LightGraphs, DataStructures, BenchmarkTools
import LightGraphs.ShortestPaths: shortest_paths, SPFA, SPFAResult

function shortest_paths_queue(g::AbstractGraph{U}, source::Integer, distmx::AbstractMatrix{T}, alg::SPFA) where {T, U<:Integer}


    nvg = nv(g)

    (source in 1:nvg) || throw(DomainError(source, "source should be in between 1 and $nvg"))
    dists = fill(typemax(T), nvg)
    parents = zeros(U, nvg)
    dists[source] = 0

    count = zeros(U, nvg)           # Vector to store the count of number of times a vertex goes in the queue.

    queue = Queue{U}()
    inqueue = falses(nvg,1)         # BitArray to mark which vertices are in queue
    enqueue!(queue, source)
    inqueue[source] = true

    @inbounds while !isempty(queue)
        v = dequeue!(queue)
        inqueue[v] = false

        @inbounds for v_neighbor in outneighbors(g, v)
            d = distmx[v,v_neighbor]
            alt = dists[v] + d

            alt > alg.maxdist && continue

            if alt < dists[v_neighbor]         # Relaxing edges
                dists[v_neighbor] = alt
                parents[v_neighbor] = v

                if !inqueue[v_neighbor]
                    enqueue!(queue,v_neighbor)
                    inqueue[v_neighbor] = true                   # Mark the vertex as inside queue.
                    count[v_neighbor] = count[v_neighbor]+1      # Increment the number of times a vertex enters a queue.

                    if count[v_neighbor] > nvg          # This step is just to check negative edge cycle. If this step is not there,
                        throw(NegativeCycleError())     # the algorithm will run infinitely in case of a negative weight cycle.
                                                        # If count[i]>nvg for any i belonging to [1,nvg], it means a negative edge
                                                        # cycle is present.
                    end
                end
            end
        end
    end

    return SPFAResult(parents, dists)
end

n = 100_000
g = erdos_renyi(n, .01)
distmx = weights(g)
typeof(distmx)
alg = SPFA(3)

@btime shortest_paths($g, 1, $distmx, $alg)
@btime shortest_paths_queue($g, 1, $distmx, $alg)
```

**Comment by sbromberger** [comment]
OK. Can we include the queue for bipartite_map and not use it for SPFA? I've merged #1385.

**Comment by harryscholes** [comment]
`DEsopoPape` benchmarks for the vector- and queue-based implementations.

```julia
julia> @btime shortest_paths($g, 1, $distmx, $alg)
81.727 ms (25 allocations: 3.62 MiB)

julia> @btime shortest_paths_queue($g, 1, $distmx, $alg)
70.851 ms (205 allocations: 2.41 MiB)
```

Script:

```julia
using LightGraphs, DataStructures, BenchmarkTools
import LightGraphs.ShortestPaths: shortest_paths, DEsopoPape, DEsopoPapeResult

function shortest_paths_queue(g::AbstractGraph, src::Integer, distmx::AbstractMatrix, alg::DEsopoPape)
    T = eltype(distmx)
    U = eltype(g)
    nvg = nv(g)
    (src in 1:nvg) || throw(DomainError(src, "src should be in between 1 and $nvg"))
    dists = fill(typemax(T), nvg)
    parents = zeros(U, nvg)
    state = Vector{Int8}()
    state = fill(Int8(2), nvg)
    q = Deque{U}()
    push!(q, src)
    @inbounds dists[src] = 0

    @inbounds while !isempty(q)
        u = popfirst!(q)
        state[u] = 0

        for v in outneighbors(g, u)
            alt = dists[u] + distmx[u, v]

            alt > alg.maxdist && continue

            if (dists[v] > alt)
                dists[v] = alt
                parents[v] = u

                if state[v] == 2
                    state[v] = 1
                    push!(q, v)
                elseif state[v] == 0
                    state[v] = 1
                    pushfirst!(q, v)
                end
            end
        end
    end

    return DEsopoPapeResult{T, U}(parents, dists)
end

n = 100_000
g = erdos_renyi(n, .001)
distmx = weights(g)
alg = DEsopoPape()

@btime shortest_paths($g, 1, $distmx, $alg)
@btime shortest_paths_queue($g, 1, $distmx, $alg)
```

**Comment by harryscholes** [comment]
I think what's happening in the shortest paths algorithms is that if no maximum distance is specified in `SPFA` or `DEsopoPape`, then more work gets done after the line:

```julia
alt > alg.maxdist && continue
```

which involves enqueueing vertices. If a maximum distance is specified, then fewer vertices are added to the queue and the vector- and queue-based implementations have approximately the same performance. The question is: do _most_ users specify a maximum distance, or not?

**Comment by sbromberger** [comment]
That makes sense.

**Comment by sbromberger** [comment]
Thanks, @harryscholes !

**Pull request merged**
