### PR TITLE
fix type inferences on nightly

### PR DESCRIPTION
**Pull request by sbromberger**
Nightly is failing due to inability to infer type correctly on these three functions.

### CODE REVIEW

**Comment by sbromberger** [comment]
I'm going to close this out because this looks like a general type inference issue with nightly, as new methods are now failing inference checks. cc @viralbshah - are you aware of any issues with inference on nightly that don't appear in release?

**Comment by ViralBShah** [comment]
1.7 has had a lot of stuff merged in since 1.6 was branched. So it is certainly possible. I suggest merging, and if the issue persists - or if we have an easy reproducer, then we file an upstream issue.

**Comment by sbromberger** [comment]
@ViralBShah - thanks, but there's nothing to merge, really. This PR was an attempt to fix 3 type inference errors from https://github.com/JuliaGraphs/LightGraphs.jl/actions/runs/478583624 - but the tests on nightly now fail with inference errors in different spots. If the type inference errors are expected to be fixed, then there's no problem, but I'd rather not have to coerce return values if I don't have to (1.5.3 doesn't seem to have an issue).

I can open up a Julia issue if you think it might be worthwhile.

**Comment by ViralBShah** [comment]
Ah I see. I have not looked deeply at the errors, but if it is only on nightly, it would certainly be worthwhile to file an issue. Thanks.

**Comment by sbromberger** [comment]
Closing via https://github.com/JuliaLang/julia/issues/39673

**Pull request closed without merging**
