### PR TITLE
Compat 0.5

### PR DESCRIPTION
**Pull request by sbromberger**
This will be messy and unsquashable.

### CODE REVIEW

**Comment by sbromberger** [comment]
@jpfairbanks I'd really like to get coverage for spectral.jl in this merge. Could you please assist here?

**Comment by jpfairbanks** [comment]
So these tests were removed when the community detection tests were removed in commit d50ef8e.
I am adding them back in. Is there an easy way to get the coverage statistics locally (ie. without pushing and waiting for travis)?

**Comment by jpfairbanks** [comment]
I just looked at the output of Pkg.test("LightGraphs", true) by hand. PR #429 adds the coverage. I remembered to checkout -b this time to avoid a direct push.

**Comment by sbromberger** [comment]
I will be committing this (and breaking 0.4 compatibility in master) as soon as the tests finish, assuming the only failures are on -release.

**Comment by sbromberger** [comment]
@jpfairbanks when we move the linalg stuff into its own directory, perhaps we can improve test coverage as well?

**Comment by sbromberger** [comment]
https://travis-ci.org/JuliaGraphs/LightGraphs.jl/jobs/161229871#L701-L705

**Pull request merged**
