### PR TITLE
WIP: Code coverage strangely failing for commits

### PR DESCRIPTION
**Pull request by SohamTamba**
As per my GSoC proposal, I have added algorithms for;
Vertex Cover
Independent Set
Matching

### CODE REVIEW

**Comment by SohamTamba** [comment]
In Travis's job log, it says there were 2 errors on label propagation.

**Comment by sbromberger** [comment]
Probably unrelated. I'll restart Travis.

**Comment by SohamTamba** [comment]
When I used test("LightGraphs", coverage=true), it showed that all the lines where run at least once.
Now it says
[L82](https://github.com/SohamTamba/LightGraphs.jl/blob/cover_ind_match/src/matching/augment_matching.jl#L82)
I'm unfamiliar with how codecov works.

**Comment by SohamTamba** [comment]
The [codecov report](https://codecov.io/gh/JuliaGraphs/LightGraphs.jl/compare/2b7689aceb6a5030740bf466a8fb3022aa7b0ac8...718d8e4b8996d5c70919a0b90c2761d645f88714/tree/src) shows that coverage was lost for unchanged files.
I'll make some changes to the PR's and see what happens.

**Comment by sbromberger** [comment]
Here's where the coverage is mising:

screen shot 2018-05-17 at 11 11 07

**Comment by SohamTamba** [comment]
The tests passed for [this PR](https://github.com/JuliaGraphs/LightGraphs.jl/pull/882/commits/d4e90cc8af2f7671d3626b32d74573081593ce47). The only difference is I removed an loop that iterates over an arguement, matching.
But if matching is not an empty vector, it should be iterated over. So I'm not sure what's going on

**Comment by somil55** [comment]
Tests are certainly working and covering newly-written code. I ran into a similar problem last year. What I did was to sync the fork, create a new branch and add the changes again. @sbromberger can help further with this.

**Pull request closed without merging**
