### PR TITLE
remove ... from interface defs. Fixes #647

### LINKED ISSUE #647: add_vertex! not implemented for (at least) UInt8 graphs
```
julia> g = Graph{UInt8}()
empty undirected simple UInt8 graph

julia> add_vertex!(g,1)
ERROR: Not implemented: add_vertex!
Stacktrace:
 [1] add_vertex!(::LightGraphs.SimpleGraphs.SimpleGraph{UInt8}, ::Int64, ::Vararg{Int64,N} where N) at /Users/seth/.julia/v0.6/LightGraphs/src/interface.jl:129
```

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by sbromberger** [comment]
cc @jpfairbanks since you're in review mode today :)

**Comment by jpfairbanks** [comment]
Is the idea here just that these functions are intended to take only one argument and we just want to communicate that fact?

**Comment by sbromberger** [comment]
@jpfairbanks yes - the issue is that doing `g = Graph{UInt8}(); add_vertex!(g, 1)` caused a "not implemented" error when it should've been a method error (because `add_vertex` doesn't take a second argument).

**Comment by jpfairbanks** [comment]
Which would imply that you should have implemented a function that you shouldn't. That makes sense.

**Pull request merged**
