### PR TITLE
some changes in rand graph generation

### PR DESCRIPTION
**Pull request by CarloLucibello**
- add `seed` to SBM @jpfairbanks 
- use the GLOBAL_RNG when seed <0 instead of MersenneTwister()
- avoid use of `sample` from StatsBase defining custom `sample!` (~10% faster and can use any RNG)

### CODE REVIEW

**Comment by CarloLucibello** [comment]
@sbromberger please merge this as soon as possible since I just noticed that after my last PR to randgraphs I introduced a subtle bug:
I thought that the no argument constructor MersenneTwister() initialized the `rng` with a random seed, but instead it initialize it with seed 0. Therefore at the present time graphs generated withouth seeding are all the same. I'm deeply sorry for this :(

**Comment by sbromberger** [comment]
The main problem I have is the rewriting of `sample!`. LG should be using external libraries for these sorts of things, since we can't expect any LG maintainers to know enough about random sequence generation to be able to support it in the future.

Is there really no way to rely on StatsBase for RNG?

**Comment by CarloLucibello** [comment]
>Is there really no way to rely on StatsBase – or some other package that's focused on randomness – for RNG?

Unfortunately not that I could find

I know it is not the optimal situation, but at least the function is very short and simple

**Comment by sbromberger** [comment]
OK. I'd like to revisit this at some point soon. Thank you for identifying and fixing the bug.

Also: can we get rid of StatsBase as a dependency now? IIRC, there was one other function (betweenness centrality?) that used it. If so, perhaps we can use this sample routine instead. Would you mind looking into this and filing another PR?

**Comment by CarloLucibello** [comment]
The one in betweenness centrality can be eliminated but there is also a call to `StatsBase.rand_binom` in erdos renyi generator, so unfortunately we cannot remove StatsBase dependency

**Pull request merged**
