### PR TITLE
Proposed rewording for  #1107.

### PR DESCRIPTION
**Pull request by dourouc05**

### CODE REVIEW

**Comment by sbromberger** [comment]
This is good, but there are more places where we need to make this change:

```
src/core.jl
216:Returns a reference, not a copy. Do not modify result.
250:Returns a reference, not a copy. Do not modify result.
289:Returns a reference, not a copy. Do not modify result.

src/SimpleGraphs/simplegraph.jl
336:Returns a reference, not a copy. Do not modify result.
349:Returns a reference, not a copy. Do not modify result.
```

**Comment by dourouc05** [comment]
Here it is! (BTW, isn't there a way to factor out this paragraph instead of copying it everywhere it is required?)

**Comment by sbromberger** [comment]
On second thought, I don't like the last sentence: "If the graph is modified, the array behind this reference will be modified too." - this makes it sound like this is defined behavior. It should be explicit that modifying the graph and continuing to reference the previous output of the function will result in *undefined* behavior - we make no promises whatsoever.

**Comment by dourouc05** [comment]
I've updated the message according to your comment; is that better?

**Pull request merged**
