### PR TITLE
FIX mathjax documentation...

### PR DESCRIPTION
**Pull request by hayd**
Fingers crossed.

Latex works locally for me with `mkdocs serve`...

*This also updates the mkdocs.yml to non-deprecated syntax.*

### CODE REVIEW

**Comment by sbromberger** [comment]
Thanks again, @hayd :)

**Comment by hayd** [comment]
great! It works! (e.g. see the latex https://lightgraphsjl.readthedocs.org/en/latest/operators/#blkdiag)

**Comment by sbromberger** [comment]
@hayd This. Is. Awesome. Too bad I don't remember any LaTeX - my last go with it was in 1993 :)

**Comment by hayd** [comment]
The remaining issue is the docs from Base/elsewhere. I/we have a solution for that, will post a fix "soon".

**Pull request merged**
