### PR TITLE
Add Boruvka Parallel MST implementation 

### PR DESCRIPTION
**Pull request by hanstananda**
The current implementation is derived from [here](https://stanford.edu/~rezab/dao/notes/lecture06/cme323_lec6.pdf). 
Manually tested with a random graph with 10^5 vertices and 5*10^6 edges.  
The multi-threaded version took 4.52s in total and the single-threaded version took 10.17s
Meanwhile, the current distributed version took 12.83s

### CODE REVIEW

**Comment by hanstananda** [comment]
@sbromberger I wanted to create the test cases for this implementation, but I saw that the tests for the e other spanning tree algorithms are now under the `deprecation` folder. How should I proceed with the test case development?

**Comment by sbromberger** [comment]
ref: #1440

**Comment by sbromberger** [comment]
Sorry about that. `test/spanningtrees13` is now out of that directory. Tests should go there.

**Comment by hanstananda** [comment]
@sbromberger , I have successfully implemented the test cases for this PR. As you can see, it sucessfully passed the both `CI/Julia` and `CI-nightly/Julia nightly`. However, it failed at documentation CI with following error: 
```
 ERROR: LoadError: LoadError: TaskFailedException:
ArgumentError: Package DataStructures not found in current path:
- Run `import Pkg; Pkg.add("DataStructures")` to install the DataStructures package.
```
I have no idea how to resolve this issue. Can you help me?

**Pull request closed without merging**
