### PR TITLE
[WIP] Algorithms for cycle detection

### PR DESCRIPTION
**Pull request by AsileBcd**
Part 2 of the split of #486 with only algorithms for cycle detection. (#486 can be closed).
That is not the iterative version. For that I will open an issue.

### CODE REVIEW

**Comment by sbromberger** [comment]
@AsileBcd @jpfairbanks status of this, please?

**Comment by AsileBcd** [comment]
Work in progress, in order to improve the algorithm, but the current one is working.

**Comment by sbromberger** [comment]
@AsileBcd did we merge this functionality via another PR? If not, do you still want to hold this PR open? Thanks.

**Comment by AsileBcd** [comment]
@sbromberger : No we did not.
The functionality is working, I just have not been able to implement it as @jpfairbanks would like (not yet at least). And I don't really have time to work on it now and won't for some time. So do whatever you want with it. I just would like to keep the code if you ever close it.

**Comment by jpfairbanks** [comment]
I don't want to lose functionality in favor of perfection. But I think that given how hard it has been to transform that from a Task to an iterator, implies that we don't have it in a maintainable form. That is based on my belief that iterators are easier to program with than tasks but I guess this could be a counter example to that belief. There is no ban on tasks in this package, but I want to avoid breakage later.

I don't really want to merge things that are not yet maintainable but I also don't want to hold up progress because of this.


@AsileBcd: do you think there is a simple iterator based implementation that will be easier to maintain than this task based approach?

**Comment by AsileBcd** [comment]
@jpfairbanks My knowledge of maintenance is close to nil, so I don't know. What I know is that the original Johnson's algorithm is well known and rather widely available at this point, at least in the recursive form as it is now and tasks are a natural way (in Julia) to implement this recursion. From that perspective, I believe the algorithm is fairly easy to maintain. 

Now I guess the main question is whether Tasks will be stable inside Julia or not, and I don't have insider knowledge nor a crystal ball to know that.

**Comment by sbromberger** [comment]
Note: Tasks have changed fundamentally in 0.6; everything that's using `Task` now in LightGraphs needs to be rewritten.

**Comment by jpfairbanks** [comment]
Docs Link?

**Comment by sbromberger** [comment]
> Docs Link?

None that I can see; just a ton of deprecations.

**Comment by jpfairbanks** [comment]
Basically you need to use `ch = Channel(f,ctype=T, csize=N)` where `f` is a function that takes a channel as an argument and then does `put!(ch, value::T)` instead of produce. The consumer task uses `val = take!(ch)` to get the value out. It is much more like the Golang interface which I like a lot.

**Comment by AsileBcd** [comment]
Thanks for the help!
I guess the change to tasks proves @jpfairbanks points about tasks!

**Comment by sbromberger** [comment]
@AsileBcd - please convert to channels - that way it will merge cleanly into the 0.6 code we're developing.

**Comment by AsileBcd** [comment]
I am trying to do that, but I have failed to compile LightGraphs on the alpha version of Julia (before any change from me). I imagine that I am not using the correct couple of versions of LightGraphs / Julia. Which one are you using? Thank you.

**Comment by sbromberger** [comment]
Use the `sbromberger/simplegraphs` branch with Julia 0.6.

**Comment by sbromberger** [comment]
@AsileBcd it'd be great if we could get this into 0.8, which I want to tag soon. Could you work on replacing `Task` and let me know when it's ready for review?

If you can't get to it for a while, please let me know. Thanks!

**Comment by AsileBcd** [comment]
@sbromberger When are you planning on tagging 0.8?
I will probably work on that next week.

**Comment by sbromberger** [comment]
Why don't we wait until 0.8.1 then? I was hoping to tag 0.8 this week. There's no urgency but I'm just trying to get the PRs in a state where they have a plan for inclusion at some point :)

**Comment by AsileBcd** [comment]
Fine! Thank you

**Comment by AsileBcd** [comment]
I have updated the commits to get rid of the Tasks and replace them with Channels, but I did it in an ugly way I believe. If you don't like it I can open a new pull request which should be clearer.

I have a question: I have realized that some syntax changes happened between .7 and .8. Something related to the type of DirectedGraph. I have not done anything in my code. Does it matter?

**Comment by sbromberger** [comment]
> I have a question: I have realized that some syntax changes happened between .7 and .8. Something related to the type of DirectedGraph. I have not done anything in my code. Does it matter?

Yes. We're using traits now for directedness. That is, instead of
```
foo (g::DiGraph)
```

we now write
```
foo(g::::IsDirected)
```

**Comment by AsileBcd** [comment]
I am not sure I understand what this means. Does it matter?

**Comment by jgoldfar** [comment]
Would there be any interest in a PR with additional graph cycle detection algorithms after this merges? We've created our own package on top of LightGraphs implementing the Hadwick & James algorithm: https://github.com/jgoldfar/GraphCircuits.jl but would be happy to contribute it here (we just needed it for our own work, so it is most likely not idiomatic/well-tested/documented but we would be willing to learn & improve!)

**Comment by sbromberger** [comment]
@AsileBcd I'll propose some changes later on - I'm currently on vacation but will have some time over the next couple of days.

@jgoldfar - yes - we're always happy to accept PRs. If you're willing to work with us on this, we can probably get it merged fairly quickly. Have a look at https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/CONTRIBUTING.md for some general guidance, and once you make a PR we can get into details.

**Comment by sbromberger** [comment]
@jgoldfar - I just took a look at your code - it looks pretty much ready to go, I think. The only things you'll want to change are the use of traits instead of `DiGraph` (that is, see my comment above), and replacing `out_edges` - we're deprecating that in favor of `out_neighbors`, which means you'll want to create your own edges from that. (You could easily reimplement `out_edges` in your local code.)

**Comment by AsileBcd** [comment]
I am not sure I understood all the philosophical changes that happened, but I have a running and without errors/warnings version of these algorithms on my computer.
I will probably push a new PR with it, I feel it is getting very messy here.

**Comment by AsileBcd** [comment]
I have made the changes, I hope according to what you said. This is running on my computer, but I should probably push a new PR so that it stop being that messy.

**Comment by sbromberger** [comment]
@AsileBcd - a rebase with a new PR might be a good idea here. Sorry - we've been merging lots of changes lately.

**Pull request closed without merging**
