### PR TITLE
removed flow algorithms

### PR DESCRIPTION
**Pull request by mbesancon**
As discussed, flow algorithms have been moved to [LightGraphsFlows](https://github.com/JuliaGraphs/LightGraphsFlows.jl).

The removal include sources, tests, benchmarks, docs which have all been transferred to the new repo.

### CODE REVIEW

**Comment by sbromberger** [comment]
@jpfairbanks @juliohm any objections to this? See also #807.

**Comment by sbromberger** [comment]
> So LG will have LGFlows.jl on its REQUIRE file or users will be asked to install it separately?

Separately, if they need flow functionality. This is primarily because the new flow algorithms that @mbesancon created require JuMP, and we don't want that dependency in LightGraphs itself.

I imagine there's a small subset of LightGraphs users who need flow functionality in any case.

**Comment by mbesancon** [comment]
Thanks @juliohm!  LGFlows has LG as a dependency since it works on the types defined in LG.

**Comment by juliohm** [comment]
Oh yes, makes total sense, sorry for the confusion. Thanks again for the split :)

**Comment by juliohm** [comment]
I think it is a good idea to check the dependencies of LG that make use of flow functionality and open issues alerting devs about the change, I will for instance have to release a new patch for ImageQuilting.jl requiring LGFlows.jl

**Comment by sbromberger** [comment]
> I will for instance have to release a new patch for ImageQuilting.jl requiring LGFlows.jl

Ah, interesting. How do we check? We're up to ~108 packages that use LightGraphs directly or indirectly.

Also - do you already require JuMP in ImageQuilting?

**Comment by juliohm** [comment]
List of packages, I am not sure there is a bot for that functionality:

```julia
Pkg.dependents("LightGraphs")
28-element Array{AbstractString,1}:
 "Circuitscape"        
 "MetaGraphs"          
 "Dispatcher"          
 "CausalInference"     
 "CommunityDetection"  
 "LightGraphsMatching" 
 "GraphIO"             
 "LightGraphsExtras"   
 "ImageQuilting"       
 "RobustShortestPath"  
 "Mamba"               
 "SNAPDatasets"        
 "QuantEcon"           
 "BayesNets"           
 "ImageSegmentation"   
 "Graph500"            
 "EllipticFEM"         
 "Phylogenies"         
 "Metis"               
 "SimpleWeightedGraphs"
 "GraphPlot"           
 "NetworkLearning"     
 "NetworkViz"          
 "TreeView"            
 "TrafficAssignment"   
 "GraphGLRM"           
 "Bio"                 
 "TikzGraphs"
```

**Comment by sbromberger** [comment]
See also https://juliaobserver.com/packages?dependent_id=LightGraphs

**Comment by juliohm** [comment]
Thank you @sbromberger , `Pkg.dependents()` doesn't return all packages then?

**Comment by sbromberger** [comment]
> `Pkg.dependents()` doesn't return all packages then?

As a primary dependency, perhaps. I don't know why there's a discrepancy.

**Comment by mbesancon** [comment]
If it is the case, should the next tagged version of LG deprecate the flow functionalities with a warning instead of plain removal?

**Comment by sbromberger** [comment]
Good question. Probably. Would you mind adding the removed functions to `deprecations.jl`?

**Comment by juliohm** [comment]
Very true @sbromberger , forgot it only catches direct dependencies.

**Comment by juliohm** [comment]
@sbromberger that is a good point, I don't require JuMP on my package, I think that is a big dependency :( Is there any way around this? I'd rather keep ImageQuilting.jl not depending on JuMP.jl

**Comment by juliohm** [comment]
Maybe keep the already existing flow algorithms that don't depend on JuMP here, the dependency issue made me think again about this change.

**Comment by sbromberger** [comment]
> Maybe keep the already existing flow algorithms that don't depend on JuMP here

This is a non-starter for several reasons. We don't want to get in the habit of creating companion packages based solely on their dependency tree; that way lies madness as dependencies come and go. Would you have the flow functions split across several companion packages?

**Comment by juliohm** [comment]
Yes, I agree entirely, I am just worried about the dependency list. For instance, we did split the Images.jl project into ImageMorphology.jl and ImageFiltering.jl among others, just so that we could use filtering and morphological operations without having all the color-related dependencies. That single move helped me afterwards decreasing the dependency list of ImageQuilting.jl by a lot. If we could avoid this dependency increase with flow algorithms, I would appreciate it very much.

**Comment by sbromberger** [comment]
Perhaps this is a good time to try to work around the macros issue with Requires.jl and conditional dependencies. Paging @vchuravy for some insight here.

**Comment by sbromberger** [comment]
@mbesancon - can we try this? In `/src/LightGraphsFlows.jl`, instead of plain old `include "mincost.jl"`, do this:
```
try 
  using JuMP
  include("mincost.jl")
catch _
  global mincost_flow(x...) = warn("This function requires JuMP. Please install it.")
end
```
and then, in "mincost.jl", put the "using JuMP" statement from line 8.

Let's see if this is a quick, painless way to solve this issue. (Note: might not need the `global` there.)

**Comment by mbesancon** [comment]
This could work. Another possibility would be to use MathProgBase.jl instead of JuMP. I have to tweak the mincost formulation a bit but it seems a lot more lightweight.
http://mathprogbasejl.readthedocs.io/en/latest/linprog.html
Could it be acceptable instead of JuMP?

**Comment by juliohm** [comment]
The issue with the try-catch block is that it inhibits precompilation.

On Jan 9, 2018 7:50 AM, "mbesancon" <notifications@github.com> wrote:

This could work. Another possibility would be to use MathProgBase.jl
instead of JuMP. I have to tweak the mincost formulation a bit but it seems
a lot more lightweight.
http://mathprogbasejl.readthedocs.io/en/latest/linprog.html
Could it be acceptable instead of JuMP?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/JuliaGraphs/LightGraphs.jl/pull/815#issuecomment-356323963>,
or mute the thread

**Comment by mbesancon** [comment]
I removed the JuMP dependency by formulating the linear program explicitly, see https://github.com/JuliaGraphs/LightGraphsFlows.jl/pull/5


This should make the LGFlows package much lighter

**Comment by sbromberger** [comment]
So – what dependencies do we have in LGFlows now?

**Comment by mbesancon** [comment]
MathProgBase, LightGraphs and GLPK as a default solver (necessary only if no other solver is provided)

**Comment by juliohm** [comment]
Thank you @mbesancon, that is a good improvement.

My personal view on the PR is that many users would still feel uncomfortable with having external dependencies such as optimization solvers. What did other packages in other languages did for these graph flow problems? Did they also depend on external optimizers? Maybe we can learn from them.

Can we classify these flow algorithms further into those that are naturally implemented without the need for external solvers versus those for which an optimization solver is welcome? For example, it seems that there is a concept of "cost" or additional weight to the algorithms requiring JuMP that would be otherwise hard to implement from scratch? The majority of flow algorithms already present in LG may have some attribute (or the lack of an attribute) that distinguishes them from this other class? Perhaps a generalization in that sense would make us more aware of the need for external solvers. We could also come up with a reasonable split where algorithms that are minimal are kept in one package and algorithms that are in a different complexity class live in another package. Just random thoughts.

The issue is really the lack of conditional dependency features in Julia, I wish there was a good solution for it already.

**Comment by mbesancon** [comment]
Actually I see it a bit of the other way around: 
All flow problems can be seen as linear optimization problems, but in some cases (maxflow with and without minimal demand, simple bi-partite matching), there are other algorithms solving that problem. 

NetworkX solves minimal cost as a linear optimization problem. The other problems could use the same algorithm with a cost matrix of 0 for all edges.

**Comment by juliohm** [comment]
We can always formulate things in terms of optimization solvers :) The question is, should we? Specially when dependencies are involved, it is good to keep things self-contained.

**Comment by juliohm** [comment]
I checked the REQUIRE files for MathProgBase and GLPK, there is almost nothing there. :+1: Nice.

If there is no good split for something like cost-aware vs. cost-free flow, I would be ok with merging this PR as is. @sbromberger and @jpfairbanks, please feel free to make a decision, I am neutral on this one.

**Comment by mbesancon** [comment]
@juliohm @sbromberger one last possibility is to remove the GLPK dependency by making the solver parameter mandatory from
```julia
solver::AbstractMathProgSolver = GLPKSolverLP())
```

With this in mind, the user has to provide their solver, this makes GLPK a required package for the tests, not the usage. I find it more straightforward to use with GLPK as default (not having to bother with which solver is usable for LP problems, etc), but this can make the package lighter on dependencies.

**Comment by juliohm** [comment]
Well thought @mbesancon :+1:  I like the idea. The interface is fine and we will save users from having GLPK on the system. What do you think @sbromberger ?

Besides being a non-trivial dependency, I am not sure if we could actually require it from a licensing point of view. I am unaware of licensing issues, but GLPK is GNU. My limited understanding is that any product shipped with LGFlows in that scenario would need to be open source? Please correct me if I am wrong. You can already predict users on the same level of understanding avoiding LGFlows because of GLPK, regardless of this being a real issue or not.

**Comment by mbesancon** [comment]
Regardless of requiring it for the package, the tests will still require a solver.

**Comment by juliohm** [comment]
I think requiring it for tests is a smaller issue, we can also require other heavier LP solvers that aren't GNU for the tests.

**Comment by mbesancon** [comment]
Ok, see https://github.com/JuliaGraphs/LightGraphsFlows.jl/pull/6 which brings the discussed modifications

**Comment by mbesancon** [comment]
Also, I guess Clp.jl would solve the problem (MIT license for the package, EPL for the solver itself).
Another solver will have to be used for LGMatching.jl, which formulates a MIP problem.

**Comment by sbromberger** [comment]
Is this ready to merge?

**Comment by mbesancon** [comment]
All good on my side, the issues discussed have been corrected in LGFlows

**Comment by juliohm** [comment]
Thank you again for your work @mbesancon, very well done. :)

Everything seems very organized and light :+1: Please feel free to go ahead and merge.

**Comment by sbromberger** [comment]
@mbesancon - would you mind rebasing on master to resolve the conflicts? This should not be a huge effort as we've just renamed all `Graph` / `DiGraph` to `SimpleGraph` / `SimpleDiGraph` throughout the codebase, and you're removing stuff. Thank you.

**Comment by sbromberger** [comment]
I will merge as soon as this passes tests. Thank you again, @mbesancon and @juliohm !

**Pull request merged**
