### PR TITLE
document add_edge! argument order

### PR DESCRIPTION
**Pull request by cmcaine**
This caught me out ;)

### CODE REVIEW

**Comment by sbromberger** [comment]
I can't reproduce this:
```
julia> g = DiGraph(4)
{4, 0} directed simple Int64 graph

julia> add_edge!(g, 1, 2)
true

julia> collect(edges(g))
1-element Array{LightGraphs.SimpleGraphs.SimpleEdge{Int64},1}:
 Edge 1 => 2
```

**Comment by bovine3dom** [comment]
The confusion arose from the adjacency matrix, I think. I've always used the same convention that Newman uses, i.e, that

`A_ij = 1 iff there is a link from j to i`

and I thought everyone else did, too, but Wikipedia disagrees with me so I must be wrong : )

Should we perhaps add a line to the `adjacency_matrix` documentation that clarifies which convention LightGraphs follows?

**Comment by simonschoelly** [comment]
Mark Newman? For me the convention that `A_ij = 1` iff there is a link from from i to j is more familiar, I have to say, although the other convention works a bit better with Julia's column major format.

Documentation for `adjaceny_matrix` currently says:
```

  Return a sparse adjacency matrix for a graph, indexed by [u, v] vertices. Non-zero values indicate an
  edge between u and v. Users may override the default data type (Int) and specify an optional
  direction.
```
I would agree, that this is a bit confusing if one not already had was convinced which order is used.

**Comment by bovine3dom** [comment]
Yeah, Mark Newman, e.g, https://books.google.co.uk/books?id=-DgTDAAAQBAJ&lpg=PP1&dq=newman%20networks%20adjacency%20matrix%20of%20a%20directed%20network%20has%20matrix&pg=PA114#v=onepage&q&f=false

**Comment by sbromberger** [comment]
> A_ij = 1 iff there is a link from j to i

I've honestly never heard this and haven't ever come across it in any other graph package I've used.

In any case, [it's in the documentation](
http://juliagraphs.github.io/LightGraphs.jl/latest/linalg.html#LightGraphs.LinAlg.adjacency_matrix).

**Comment by cmcaine** [comment]
Cool. If I'd investigated this better I could have avoided wasting your time :/

Thank you for clarifying, though. Maybe an explicit statement in add_edge as well would help for people like Olie who have had their ears filled with poison?

**Comment by sbromberger** [comment]
The thing is, the API contract for `add_edge!()` is to supply an edge, and (at least for the defined types) `Edge` has `src()` and `dst()` accessors.

**Comment by cmcaine** [comment]
Sure, but there's a method that takes node numbers, and that's the one
that's demoed in the documentation and that most people will probably use
unless their graphs are exotic.

Could move that documentation to the method or just drop this PR. I'm easy.

**Comment by sbromberger** [comment]
I'm always open to better documentation, but I'm struggling with something that someone else might be able to help with: that is, the difference between directed and undirected edges. Right now, we have no distinction: the directedness is at the graph level, so `Edge(1,2)` in a digraph is the same as `Edge(1,2)` in a graph.

The reason this is significant here (at least in my current thinking) is because if we add docs that explain `add_edge!(src, dst)`, what does that mean for undirected graphs? `src` and `dst` aren't really relevant in an undirected graph.

Maybe I'm overthinking this.

**Comment by bovine3dom** [comment]
I don't think `add_edge` needs any more documentation - `add_edge(src,dst)` is the obvious and I think only sane way of specifying it - it's the adjacency matrix which is following an unspecified convention, for which there is another possible convention, however much of a minority opinion that may be.

>  Return a sparse adjacency matrix for a graph, indexed by [u, v] vertices. Non-zero values indicate an
  edge between u and v. Users may override the default data type (Int) and specify an optional
  direction.

I'd just say "from u to v" because it's obvious (to me) that means "between u and v" for undirected graphs (or, it still means from u to v but you have a symmetric matrix so there's a v to u too).

**Comment by sbromberger** [comment]
Could it be as easy as substituting one word? "Non-zero values indicate an edge **from** u to v..."?

**Comment by bovine3dom** [comment]
Yes, that's exactly what I was suggesting : )

**Comment by sbromberger** [comment]
c.f. #1161

**Comment by sbromberger** [comment]
Thanks for the great discussion :)

**Pull request closed without merging**
