### PR TITLE
Revert "Nightly Stable Badge"

### PR DESCRIPTION
**Pull request by sbromberger**
Reverts JuliaGraphs/LightGraphs.jl#1544

### CODE REVIEW

**Comment by sbromberger** [comment]
@birm - this isn't quite what we want, I don't think: we want the status of the master branch of LightGraphs against the stable version of Julia.

**Comment by birm** [comment]
Oh, I'm sorry for the misunderstanding!

**Comment by birm** [comment]
So you prefer Build Status (https://github.com/JuliaGraphs/LightGraphs.jl/actions/workflows/ci.yml/badge.svg?branch=master)

**Comment by sbromberger** [comment]
I think that's right!

**Pull request merged**
