### PR TITLE
improvements in random graph generation

### PR DESCRIPTION
**Pull request by CarloLucibello**
I improved the erdos_renyi generation sampling from first the total number of edges from a binomial distribution

Also, I made some changes in the use of seeds. Sadly I could not achieve full consistency because of https://github.com/JuliaStats/Distributions.jl/issues/436

### CODE REVIEW

**Comment by sbromberger** [comment]
I don't like depending on other packages where we have functional and performant alternatives. What's the advantage to this PR? (Also, I don't like keywords where we can avoid them. It's nice to be able to do `g = Graph(10,20,1)` to quickly create consistent random graphs for testing.)

**Comment by sbromberger** [comment]
Oh, also - I've got even more efficient `Graph(m,n)` and `DiGraph(m,n)` in the edgeiter branch, so those changes will be short-lived.

**Comment by CarloLucibello** [comment]
there are some points this PR addresses 
- erdos-renyi(n,p) generation was inefficient, since it test each potential edge independently ( O(n^2)). The right thing to do is to extract first `ne` from the binomial distribution and then ad `ne` edges randomly (this is O(n) for sparse graphs).
- randgraphs generators should have a consistent interface and should all support seeding. I think having the keyword argument `seed` is the only way to go
- it is preferable to use a local `rng`, to decouple the seeding of the graph from that of any other part of a program

**Comment by sbromberger** [comment]
OK, I agree on all counts. Is there any way to do this without depending on Distributions?

**Comment by CarloLucibello** [comment]
I found the function rand_binom in StatsBase

**Comment by sbromberger** [comment]
Awesome. I'm out this morning but will give it a final review later today. Can you squash commits?

**Comment by CarloLucibello** [comment]
squashed

**Comment by sbromberger** [comment]
We merged this, but could you please make sure we're consistent with seeds in randgraphs? That is, some of them are keywords, but some aren't (I prefer non keywords, but whatever works); and there's some weirdness in erdos renyi that isn't in any of the others - why is it different?

```
    if seed >= 0
        # init dsfmt generator without altering GLOBAL_RNG
        Base.dSFMT.dsfmt_gv_init_by_array(MersenneTwister(seed).seed+1)
    end
```

**Comment by CarloLucibello** [comment]
Why you say it inconsistent? Each interface function has the keyword argument `seed`.... 

The weirdness in erdos_renyi is due to the fact that sampling from binomial distribution in StatsBase, as in other julia packages, relies on ccall to an Rmath function.  This
```
Base.dSFMT.dsfmt_gv_init_by_array(MersenneTwister(seed).seed+1)
```
is to seed the rng that Rmath uses while not altering GLOBAL_RNG  (the default and global rng for julia's random number generation)

**Comment by sbromberger** [comment]
Take a look here:

```
function Graph(nv::Integer, ne::Integer; seed::Int = -1)
function DiGraph(nv::Integer, ne::Integer; seed::Int = -1)
function erdos_renyi(n::Integer, p::Real; is_directed=false, seed::Integer=-1)
function erdos_renyi(n::Integer, ne::Integer; is_directed=false, seed::Integer=-1)
function watts_strogatz(n::Integer, k::Integer, β::Real; is_directed=false, seed::Int = -1)
function random_regular_graph(n::Int, k::Int, seed::Int=-1)
function random_configuration_model(n::Int, k::Array{Int}, seed::Int=-1)
function random_regular_digraph(n::Int, k::Int, dir::Symbol=:out, seed::Int=-1)
function stochastic_block_model(n::Integer, r::Integer, pint::Real, pext::Real, seed::Int=-1)
```

That is, only `Graph` and `DiGraph` use `seed` as a keyword argument. The rest are using it as a positional parameter.

**Comment by CarloLucibello** [comment]
Ok,  sorry, I'll fix the seed stuff later 

The global rng is not altered anywhere, since I'm using local rngs. The case of Erdos-Renyi had to be treated differently cause of Rmath

**Comment by sbromberger** [comment]
Ah, I think I understand. Thanks for your patient explanations and for making sure we're doing things the right way!

**Comment by CarloLucibello** [comment]
#251

**Comment by sbromberger** [comment]
All good! Thanks again.

**Pull request merged**
