### PR TITLE
Correct the doc for multiroute flow

### PR DESCRIPTION
**Pull request by Azzaare**
Following the request in #433

### CODE REVIEW

**Comment by sbromberger** [comment]
Thanks!

**Comment by Azzaare** [comment]
Thanks to you!

**Comment by sbromberger** [comment]
Let's make sure the docs are the way you want them....

**Comment by sbromberger** [comment]
I'm not sure that worked. Can you take a look?

**Comment by Azzaare** [comment]
It doesn't seem so. I tested locally and the file generated by docs/make.jl was correct.

**Comment by sbromberger** [comment]
Yeah, me too. I wonder why this isn't building properly. I'll take another look.

**Comment by sbromberger** [comment]
@michaelhatherly sorry to drag you in here, but would you mind taking a look and suggesting a fix? I thought that the way we had things set up, travis would automatically build the docs based on what was in `docs/src` - but apparently it's no longer working. Not sure what to do here.

**Comment by sbromberger** [comment]
See also https://travis-ci.org/JuliaGraphs/LightGraphs.jl#L1018-L1119, specifically the last line: "Skipping docs deployment".

**Comment by sbromberger** [comment]
Perhaps that's because of https://github.com/JuliaDocs/Documenter.jl/issues/81#issuecomment-223547528.

**Comment by MichaelHatherly** [comment]
> Perhaps that's because of JuliaDocs/Documenter.jl#81 (comment).

Yes, Julia versions need to match up [here](https://github.com/JuliaGraphs/LightGraphs.jl/blob/4ecc8087351f1cf9c642229c9d2b46613772f5b7/docs/make.jl#L18) and [here](https://github.com/JuliaGraphs/LightGraphs.jl/blob/4ecc8087351f1cf9c642229c9d2b46613772f5b7/.travis.yml#L9), i.e. switch to `"0.5"` in `make.jl` or add back `nightly` in `.travis.yml`.

**Comment by sbromberger** [comment]
Gotcha. Thanks for confirming my suspicions. Docs are now building properly. Cheers!

**Comment by Azzaare** [comment]
Thank you both!

**Pull request merged**
