### PR TITLE
Add edge destructuring

### PR DESCRIPTION
**Pull request by chethega**
This is basically the proposal from #1132.

### CODE REVIEW

**Comment by sbromberger** [comment]
I like the looks of this. @jpfairbanks @somil55 - what do you think?

**Comment by simonschoelly** [comment]
Would it make sense to get `@inbounds` working with this code so that the bound check is not used when the destructuring happens within a block that has `@inbounds` in front?

**Comment by chethega** [comment]
There is no runtime boundscheck. 

`s,d,w=edge` is simply an error, and I thought `BoundsError` was the most informative: It is the same error as happens when you try to destructure too many elements from a tuple.

**Comment by jpfairbanks** [comment]
I like this too, the only question is what to do about the other components of the edge. Do we want to allow implementors to define more fields in the edge for destructuring? If they do, what happens to the code that only uses the first two fields? Based on the default behavior of tuples in `v1.0.3`. I guess they just get dropped. 

```julia
julia> a,b = (1,2,3)
(1, 2, 3)

julia> a
1

julia> b
2
```

Does that behavior make sense for the graph destructuring case? If we define an edge as a tuple `(src, dst, otherstuff...)` then we don't have to make a decision about the order for the other data.

**Comment by chethega** [comment]
It is impossible to define an edge type `<:AbstractEdge` as a tuple. Implementors are still free to define
```
abstract type AbstractWeightedEdge <: LightGraphs.AbstractEdge
@inline function Base.indexed_iterate(e::AbstractWeightedEdge, i::Int, state=nothing)
￼     i == 1 && return ( LightGraphs.src(e), nothing)
￼     i == 2 && return ( LightGraphs.dst(e), nothing)
     i == 3 && return (weight(e), nothing)
￼     throw(BoundsError(e, i))
￼ end
```
Code that uses `u,v = edge` will never call `indexed_iterate(edge, 3, nothing)`, and the compiler knows this, so the bounds error cannot appear and the weight does not matter for code that expects `<:AbstractEdge` and therefore never attempts `u,v,w = edge`.

Implementors would not be free anymore to define
```
abstract type CrazyEdge <: LightGraphs.AbstractEdge
@inline function Base.indexed_iterate(e::CrazyEdge, i::Int, state=nothing)
￼     i == 1 && return ( LightGraphs.dst(e), nothing)
￼     i == 2 && return ( LightGraphs.src(e), nothing)
     i == 3 && return (weight(e), nothing)
￼     throw(BoundsError(e, i))
￼ end
```
because that would break our new extended API contract.

**Comment by sbromberger** [comment]
Can anyone think of any cases where `edge[1]` should return the *destination*? If not, I think this looks GTG.

**Comment by sbromberger** [comment]
> It is impossible to define an edge type `<:AbstractEdge` as a tuple.

Why not restrict this to `AbstractSimpleEdge` for now then?

**Comment by sbromberger** [comment]
pinging @chethega - is there a reason we can't limit this to `AbstractSimpleEdge`? If we do this, I think it's good to go immediately.

**Comment by chethega** [comment]
I apologize for lack of updates on my side.

Now waiting on comments from [upstream](https://github.com/JuliaLang/julia/pull/31765) on compatibility questions: Apparently `indexed_iterate` is considered internal and can change on any release. 

That would be a strong argument for delaying merge of this PR, especially as long as there is a faint possibility that the lowering will change in a way that completely forbids this feature: In that case, we this would necessitate modification of not just the 5 lines implementing the edge destructuring but also all the code that uses this new feature in lightgraphs. This would be a catastrophe, so we should wait a little longer.

**Comment by simonschoelly** [comment]
So it looks as this upstream change will not happen soon. Maybe we either simply merge it and then fix it in the future, when they change the code in `Base` or could we maybe use the standard iteration protocol with some possible overhead and add a comment to the code?

**Pull request closed without merging**
