### PR TITLE
Add the functions inedges and outedges

### PR DESCRIPTION
**Pull request by dourouc05**
Working with `inneighbors` and `outneighbors`, I was puzzled not to find related functions that return the corresponding edges. Hence this PR :)! 

For now, the test are not passing for type-related issues (how to create an edge with the right type, as the implementation should work for pretty much any graph type?): 

```
SimpleGraphs: Error During Test at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:68
  Test threw exception
  Expression: #= C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:68 =# @inferred(inedges(g, 2)) == [Edge(1, 2), Edge(3, 2)]
  MethodError: no method matching SimpleEdge(::UInt8, ::Int64)
  Closest candidates are:
    SimpleEdge(::T<:Integer, !Matched::T<:Integer) where T<:Integer at C:\Users\Thibaut\.julia\dev\LightGraphs\src\SimpleGraphs\simpleedge.jl:7
  Stacktrace:
   [1] (::getfield(LightGraphs, Symbol("##1#2")){Int64})(::UInt8) at .\none:0
   [2] iterate at .\generator.jl:47 [inlined]
   [3] collect at .\array.jl:606 [inlined]
   [4] inedges(::SimpleGraph{UInt8}, ::Int64) at C:\Users\Thibaut\.julia\dev\LightGraphs\src\interface.jl:336
   [5] top-level scope at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:68
   [6] top-level scope at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Test\src\Test.jl:1083
   [7] top-level scope at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:4
SimpleGraphs: Error During Test at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:69
  Test threw exception
  Expression: #= C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:69 =# @inferred(outedges(g, 2)) == [Edge(2, 1), Edge(2, 3)]
  MethodError: no method matching SimpleEdge(::Int64, ::UInt8)
  Closest candidates are:
    SimpleEdge(::T<:Integer, !Matched::T<:Integer) where T<:Integer at C:\Users\Thibaut\.julia\dev\LightGraphs\src\SimpleGraphs\simpleedge.jl:7
  Stacktrace:
   [1] (::getfield(LightGraphs, Symbol("##3#4")){Int64})(::UInt8) at .\none:0
   [2] iterate at .\generator.jl:47 [inlined]
   [3] collect at .\array.jl:606 [inlined]
   [4] outedges(::SimpleGraph{UInt8}, ::Int64) at C:\Users\Thibaut\.julia\dev\LightGraphs\src\interface.jl:352
   [5] top-level scope at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:69
   [6] top-level scope at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Test\src\Test.jl:1083
   [7] top-level scope at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:4
SimpleGraphs: Error During Test at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:68
  Test threw exception
  Expression: #= C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:68 =# @inferred(inedges(g, 2)) == [Edge(1, 2), Edge(3, 2)]
  MethodError: no method matching SimpleEdge(::Int16, ::Int64)
  Closest candidates are:
    SimpleEdge(::T<:Integer, !Matched::T<:Integer) where T<:Integer at C:\Users\Thibaut\.julia\dev\LightGraphs\src\SimpleGraphs\simpleedge.jl:7
  Stacktrace:
   [1] (::getfield(LightGraphs, Symbol("##1#2")){Int64})(::Int16) at .\none:0
   [2] iterate at .\generator.jl:47 [inlined]
   [3] collect at .\array.jl:606 [inlined]
   [4] inedges(::SimpleGraph{Int16}, ::Int64) at C:\Users\Thibaut\.julia\dev\LightGraphs\src\interface.jl:336
   [5] top-level scope at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:68
   [6] top-level scope at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Test\src\Test.jl:1083
   [7] top-level scope at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:4
SimpleGraphs: Error During Test at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:69
  Test threw exception
  Expression: #= C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:69 =# @inferred(outedges(g, 2)) == [Edge(2, 1), Edge(2, 3)]
  MethodError: no method matching SimpleEdge(::Int64, ::Int16)
  Closest candidates are:
    SimpleEdge(::T<:Integer, !Matched::T<:Integer) where T<:Integer at C:\Users\Thibaut\.julia\dev\LightGraphs\src\SimpleGraphs\simpleedge.jl:7
  Stacktrace:
   [1] (::getfield(LightGraphs, Symbol("##3#4")){Int64})(::Int16) at .\none:0
   [2] iterate at .\generator.jl:47 [inlined]
   [3] collect at .\array.jl:606 [inlined]
   [4] outedges(::SimpleGraph{Int16}, ::Int64) at C:\Users\Thibaut\.julia\dev\LightGraphs\src\interface.jl:352
   [5] top-level scope at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:69
   [6] top-level scope at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Test\src\Test.jl:1083
   [7] top-level scope at C:\Users\Thibaut\.julia\dev\LightGraphs\test\simplegraphs\simplegraphs.jl:4
```

### CODE REVIEW

**Comment by sbromberger** [comment]
Edge types can be gotten via `edgetype()`.  The best way to do this is simply:
```
inedges(g, v) = [edgetype(g)(x, v) for x in inneighbors(g, v)]
outedges(g, v) = [edgetype(g)(x, v) for x in outneighbors(g, v)]
```
Because this is so simple,  I don't think we really need separate functions for this.

**Comment by simonschoelly** [comment]
If we have such functions, I think they should be generators or iterators, otherwise one would have a lot of costly allocations.

While I am not convinced, that we need such a function right now, I can see two use cases:
1. For graphs with edge metadata, there are many cases, where we would have much better performance, if we could retrieve the the edge metadata at the same time as the neighbors.

2. For multigraphs, this functions would allow us to retrieve all outgoing edges, even if there is more than one between a pair of vertices.

For these two cases, one should consider, if it wouldn't be better, if we could omit the starting vertex, as this information is redundant and wastes space. Maybe the term `halfedge` would fit in here well.

**Comment by dourouc05** [comment]
I have added a commit to use generators (or would you prefer an iterator?) instead of allocating a list, which indeed would seem better. 

(The main reason for this PR is that I found myself writing code to do this multiple times, and I think I am not alone doing that. For that reason, I don't think halfedges would be a good solution -- this functionality is already available through `inneighbors` and `outneighbors`.)

**Comment by sbromberger** [comment]
I'm sorry, but I don't see this as generally useful. The solution here is a one-liner, and adding this to the  official interface just complicates things as it's not "standalone" - that is, it can be completely written using other interface functions, so there's no new or novel functionality that's expressed by the proposed functions.

**Comment by dourouc05** [comment]
The same reasoning applies to most of https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/core.jl, if not all these functions: they provide something useful for the user, something very simple that can be written as a one-liner, but allows more readable code for users. Shall I update my PR to move the proposed functions to that file?

**Comment by sbromberger** [comment]
`core` is not `interface` - that is, `core` provides important convenience functions that are not part of the required API.

The problem with moving this to `core` is that it produces edges, which are defined elsewhere. (There's only one function in `core` that deals with edges, and that's `is_ordered` which was only put there for convenience.)

I need to think about this a bit more. (cc @jpfairbanks)

**Comment by sbromberger** [comment]
Also, this doesn't generalize well, I don't think: `inedges` and `outedges` would have to be overridden by MetaGraphs and SimpleWeightedGraphs in order to preserve the metadata.

**Comment by dourouc05** [comment]
I don't see that as an issue: in MetaGraphs, `edges` just returns the result on the underlying graph, i.e. without its metadata (a list of the same type as these functions). Using these functions, I can still access the metadata through `get_prop`. 

I have no idea about weighted graphs, as I don't use them.

**Comment by sbromberger** [comment]
> I have no idea about weighted graphs, as I don't use them.

```
julia> g = SimpleWeightedGraph(5)
{5, 0} undirected simple Int64 graph with Float64 weights

julia> add_edge!(g, 1, 2, 1.0)
true

julia> add_edge!(g, 1, 3, 2.0)
true

julia> add_edge!(g, 1, 4, 3.0)
true

julia> add_edge!(g, 1, 5, 4.0)
true

julia> SimpleWeightedEdge(1, 5, 4.0) == SimpleWeightedEdge(1, 5, 4.0)
true

julia> SimpleWeightedEdge(1, 5, 4.0) == SimpleWeightedEdge(1, 5, 1.0)
true

julia> collect(edges(g))
4-element Array{SimpleWeightedEdge{Int64,Float64},1}:
 Edge 1 => 2 with weight 1.0
 Edge 1 => 3 with weight 2.0
 Edge 1 => 4 with weight 3.0
 Edge 1 => 5 with weight 4.0
```

**Pull request closed without merging**
