### PR TITLE
fixes 1258

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by sbromberger** [comment]
would like a review of this change, please.

**Comment by sbromberger** [comment]
I will be merging this in the next couple of days.

**Comment by matbesancon** [comment]
Simpler is better, I like it. Are there some implications from a runtime perspective?

**Comment by matbesancon** [comment]
to return to this, maybe we could add a test corresponding to the initial bug reported:
```julia
using LightGraphs

function astarbug()
    g::SimpleGraph = complete_graph(4)
    w::Array{Float64, 2} = [
        1. 1. 1. 4.;
        1. 1. 1. 1.;
        1. 1. 1. 1.;
        4. 1. 1. 1.;
    ]
    res = a_star(g, 1, 4, w)
end

astarbug()
```

Was throwing, checking that it now computes the correct result will be enough

**Pull request merged**
