### PR TITLE
transitive closure speed improved

### PR DESCRIPTION
**Pull request by abhinavmehndiratta**
#1035 
```julia
g = SimpleDiGraph(100,200)
@benchmark transitiveclosure(g)
```
Benchmarks using Floyd Warshall Algorithm
```julia
  BenchmarkTools.Trial: 
  memory estimate:  401.77 KiB
  allocs estimate:  1195
  --------------
  minimum time:     3.634 ms (0.00% GC)
  median time:      3.715 ms (0.00% GC)
  mean time:        3.859 ms (2.09% GC)
  maximum time:     64.727 ms (94.07% GC)
  --------------
  samples:          1294
  evals/sample:     1
```
Benchmarks using DFS
```julia
  BenchmarkTools.Trial: 
  memory estimate:  700.92 KiB
  allocs estimate:  2188
  --------------
  minimum time:     1.989 ms (0.00% GC)
  median time:      2.028 ms (0.00% GC)
  mean time:        2.119 ms (3.14% GC)
  maximum time:     63.122 ms (96.40% GC)
  --------------
  samples:          2352
  evals/sample:     1
```

### CODE REVIEW

**Comment by sbromberger** [comment]
My concern is that this will require double the memory due to the `copy(g)`. Can you try this on a very large graph (say, 10 million nodes) to see what happens?

**Comment by sbromberger** [comment]
Can you rerun the benchmarks with the update?

**Comment by abhinavmehndiratta** [comment]
i am implementing this using condensation graph and will share the benchmarks once i am sure it covers all cases :grimacing:

**Comment by abhinavmehndiratta** [comment]
```julia
@benchmark transitiveclosure(SimpleDiGraph(1000,rand(1000:5000)))
```
Using Floyd Warshall
```julia
BenchmarkTools.Trial: 
  memory estimate:  18.41 MiB
  allocs estimate:  16131
  --------------
  minimum time:     871.134 ms (0.00% GC)
  median time:      7.989 s (0.12% GC)
  mean time:        7.989 s (0.12% GC)
  maximum time:     15.106 s (0.13% GC)
  --------------
  samples:          2
  evals/sample:     1
```

Using condensation graph
```julia
BenchmarkTools.Trial: 
  memory estimate:  5.70 MiB
  allocs estimate:  24565
  --------------
  minimum time:     14.197 ms (0.00% GC)
  median time:      410.114 ms (0.73% GC)
  mean time:        382.006 ms (7.91% GC)
  maximum time:     687.441 ms (12.49% GC)
  --------------
  samples:          14
  evals/sample:     1
```

**Comment by abhinavmehndiratta** [comment]
For a graph of that size a lot of ram is required.I tried running on a graph of 50k,500k but the oom killer is triggered every time.Maybe its cause my ram is only 4gb and swap space is 2gb.

**Comment by sbromberger** [comment]
yup, that'd do it. Let me see what I can do here on a larger memory machine.

**Comment by simonschoelly** [comment]
A while ago, I tried to run `transitive_closure` on the `arxiv_cit_hep_th` graph from `SNAPGraphs.jl` and gave up after half an hour. This  graph has approximatly 28.000 nodes and 350.000 edge.
You could try to run your algorithm on this graph. As it as multiple strongly connected components and far fever weakly connected components, I would assume that it is a good test candidate.

**Comment by sbromberger** [comment]
```
julia> g = DiGraph(2000,30000)                                                                                                                                   
{2000, 30000} directed simple Int64 graph                                                                                                                        
                                                                                                                                                                 
julia> is_connected(g)                                                                                                                                           
true                                                                                                                                                             
                                                                                                                                                                 
julia> transitiveclosure(g)                                                                                                                                      
{2000, 3998000} directed simple Int64 graph                                                                                                                      
                                                                                                                                                                 
julia> @benchmark transitiveclosure($g)                                                                                                                          
BenchmarkTools.Trial:                                                                                                                                            
  memory estimate:  175.75 MiB                                                                                                                                   
  allocs estimate:  34369                                                                                                                                        
  --------------                                                                                                                                                 
  minimum time:     358.056 s (0.03% GC)                                                                                                                         
  median time:      358.056 s (0.03% GC)                                                                                                                         
  mean time:        358.056 s (0.03% GC)                                                                                                                         
  maximum time:     358.056 s (0.03% GC)                                                                                                                         
  --------------                                                                                                                                                 
  samples:          1                                                                                                                                            
  evals/sample:     1                                                                                                                                            
```

```
julia> @benchmark transitiveclosure($g)
BenchmarkTools.Trial:          
  memory estimate:  174.85 MiB 
  allocs estimate:  34374      
  --------------               
  minimum time:     1.593 s (0.00% GC)
  median time:      1.630 s (4.39% GC)
  mean time:        1.640 s (3.75% GC)
  maximum time:     1.707 s (6.02% GC)
  --------------
  samples:          4
  evals/sample:     1
```

**Pull request merged**
