### PR TITLE
Add Grid for #298

### PR DESCRIPTION
**Pull request by jpfairbanks**
construct the discrete Laplace operator in any number of dimensions using crosspath and PathGraph.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
I actually did this in the Github editor. I should get bonus points if it passes tests on the first try.

**Comment by sbromberger** [comment]
Looks ok except for some coverage :)

**Comment by sbromberger** [comment]
Also, mind squashing (or is that not easy since you did this in github editor)?

**Comment by jpfairbanks** [comment]
I gave up on the github editor :-1: :disappointed:. I'll squash it.

**Comment by sbromberger** [comment]
Thanks!!!

**Pull request merged**
