### PR TITLE
rename decomposition -> degeneracy

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by jpfairbanks** [comment]
Why degeneracy? Maybe we should go to a folder `decomposition/kcore.jl` /bikeshed

**Comment by sbromberger** [comment]
> Why degeneracy?

https://en.wikipedia.org/wiki/Degeneracy_(graph_theory)

**Comment by sbromberger** [comment]
Given that this is itself a bikeshed, I'm open to closing it out, but I think the definition is apt.

**Comment by sbromberger** [comment]
@jpfairbanks has approved (from dinner). Merging.

**Pull request merged**
