### PR TITLE
Add graph edit distance

### PR DESCRIPTION
**Pull request by juliohm**
Related: #415 

Can you please explain why the PR cannot be automatically merged? Git is always trick to get right.

### CODE REVIEW

**Comment by sbromberger** [comment]
First, you need to do squash the commits to a reasonable number (use `git rebase` with the appropriate arguments to do this).

Next, do a `git merge master` into your branch and resolve the conflicts using `git mergetool` - it's because we've changed files since you started this branch and git doesn't know which ones we want to keep.

**Comment by juliohm** [comment]
I will fork LG again and start the PR from scratch to save time.

**Comment by sbromberger** [comment]
No need to do a fork - just checkout master and do a `git pull`.

**Comment by juliohm** [comment]
@sbromberger I will do it next time, the clean PR is here: https://github.com/JuliaGraphs/LightGraphs.jl/pull/443

**Pull request closed without merging**
