### PR TITLE
removed a duplicated part in pathing.md

### PR DESCRIPTION
**Pull request by chkwon**

### CODE REVIEW

**Comment by sbromberger** [comment]
These files are actually autogenerated so editing them won't help - we need to track down where the duplication is actually happening.

Thanks for the report!

**Comment by sbromberger** [comment]
@hayd - sorry to keep bugging you, but I have no idea where the duplication is happening. See also https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/doc/pathing.md#bellman_ford_shortest_paths .

**Comment by hayd** [comment]
It's in the [build.jl and in the enumerate_paths docstring](https://github.com/JuliaGraphs/LightGraphs.jl/search?utf8=%E2%9C%93&q=For+Floyd-Warshall+path+states). I think it belongs in enumerate_paths docstring only.

**Comment by hayd** [comment]
If I have time at the weekend will try to kick the tyres on the Docile rewrite, which should generalize the build.jl and make it more transparent what's going on.

**Pull request closed without merging**
