### PR TITLE
Linalg submodule merge

### PR DESCRIPTION
**Pull request by jpfairbanks**

### CODE REVIEW

**Comment by jpfairbanks** [comment]
continues #473

**Comment by jpfairbanks** [comment]
Tests pass. I am out of time to work on this for now. Can we merge and get the coverage up later? Diff coverage is 94%. 100% diff coverage is very stringent.

**Comment by sbromberger** [comment]
If you promise to get test coverage up later, yes :)

**Comment by jpfairbanks** [comment]
:ship:

**Comment by sbromberger** [comment]
Already done, my friend. Thanks for your work on this. I'm going to open up an issue and assign it to you for codecov :)

**Pull request merged**
