### PR TITLE
update dfs

### PR DESCRIPTION
**Pull request by alimamdouh212**
in the old dfs we were always have to iterate over all the neighbours of every node we visit any node,
that problem appers most in graphs like star graph where there is one neightbour array of lenght n and we rescan it from the begining over and over agaon, 
which becam n^2 algorithm, in my solution the algorithm remmmper the last index it were in every neighbours, in the dfs stack, which unable us to avodid this problem,

### CODE REVIEW

**Comment by sbromberger** [comment]
This is competing with #1319. Which is faster?

**Comment by alimamdouh212** [comment]
@sbromberger  i compared the two, this one faster about 150% , but 1319  consumes two much memory

**Comment by alimamdouh212** [comment]
on star_fraph(5000_000)


1319
`BenchmarkTools.Trial: 
  memory estimate:  121.81 MiB
  allocs estimate:  4999518
  --------------
  minimum time:     1.143 s (0.00% GC)
  median time:      1.147 s (0.00% GC)
  mean time:        1.162 s (2.07% GC)
  maximum time:     1.199 s (5.22% GC)
  --------------
  samples:          5
  evals/sample:     1`


this code 

`BenchmarkTools.Trial: 
  memory estimate:  38.74 MiB
  allocs estimate:  4999495
  --------------
  minimum time:     1.073 s (0.00% GC)
  median time:      1.075 s (0.00% GC)
  mean time:        1.077 s (0.00% GC)
  maximum time:     1.087 s (0.00% GC)
  --------------
  samples:          5
  evals/sample:     1`


on binary_tree(10)
1319
`BenchmarkTools.Trial: 
  memory estimate:  8.81 KiB
  allocs estimate:  521
  --------------
  minimum time:     209.900 μs (0.00% GC)
  median time:      218.800 μs (0.00% GC)
  mean time:        229.343 μs (1.04% GC)
  maximum time:     12.447 ms (96.34% GC)
  --------------
  samples:          10000
  evals/sample:     1`

this code
`BenchmarkTools.Trial: 
  memory estimate:  4.55 KiB
  allocs estimate:  519
  --------------
  minimum time:     211.700 μs (0.00% GC)
  median time:      221.800 μs (0.00% GC)
  mean time:        226.026 μs (0.65% GC)
  maximum time:     15.075 ms (98.06% GC)
  --------------
  samples:          10000
  evals/sample:     1`

**Comment by sbromberger** [comment]
This doesn't seem to produce the correct results: on a `wheel_digraph(100)`.

**Comment by sbromberger** [comment]
Checking against `binary_tree(10)` is not a valid test since `is_cyclic` for an undirected graph is true if `ne(g) > 0`.

**Comment by sbromberger** [comment]
Could you fix your spacing in the code? It's really hard to read. Thanks!

**Comment by alimamdouh212** [comment]
@sbromberger  i didn’t test it against is_cyclic , could you tell me which parts you find unclear to modify them.

**Comment by simonschoelly** [comment]
I am not sure, how the benchmark that you are running exactly looks (that should be part of the benchmark) but DFS search can be really sensible for which branch is taken first, especially when it is run on something artifical like a star graph. For such graphs, it might be better, if you use dfs to get the min distance between several (or all) pairs of the graph.

**Comment by alimamdouh212** [comment]
@simonschoelly  the DFS in all the versions that i compared between, is taking every neighbours array in the same order, i do’t think that will make a difference between the algorithms,
i don’t know how to find min distance by DFS, could you be confusing it with  BFS ?

**Comment by sbromberger** [comment]
I've cleaned this up and ported it to the `2.0.0-dev` branch via `sbromberger/Traversals`.

**Comment by sbromberger** [comment]
Implemented in #1335. Thanks!

**Pull request closed without merging**
