### PR TITLE
Make connected_components(::DiGraph) a MethodError

### LINKED ISSUE #368: `connected_components` dispatch too broad?
`connected_components` doesn't seem to have a meaningful return when called on a directed graph.

``` julia
julia> g = DiGraph(5)
{5, 0} directed graph

julia> [add_edge!(g, Pair(x...)) for x in Array[[3,2],[3,4],[4,5],[5,1]]]
4-element Array{Pair{Int64,Int64},1}:
 edge 3 - 2
 edge 3 - 4
 edge 4 - 5
 edge 5 - 1

julia> connected_components(g)
3-element Array{Array{Int64,1},1}:
 [1]    
 [2]    
 [3,4,5]

julia> g2 = DiGraph(5)
{5, 0} directed graph

julia> [add_edge!(g2, Pair(x...)) for x in Array[[1,2],[1,3],[3,4],[3,5]]]
4-element Array{Pair{Int64,Int64},1}:
 edge 1 - 2
 edge 1 - 3
 edge 3 - 4
 edge 3 - 5

julia> connected_components(g2)
1-element Array{Array{Int64,1},1}:
 [1,2,3,4,5]

julia> symdiff(strongly_connected_components(g), strongly_connected_components(g2))
0-element Array{Array{Int64,1},1}

julia> symdiff(weakly_connected_components(g), weakly_connected_components(g2))
0-element Array{Array{Int64,1},1}
```

Should it's dispatch be limited to undirected graphs where it has meaning? Or could the documentation change of 9873d0f6274e584359 be reverted to specify that's the type it works on?

edit: This is on julia 0.4.5 using LightGraphs master.

### PR DESCRIPTION
**Pull request by jpfairbanks**
closes #368

### CODE REVIEW

**Comment by sbromberger** [comment]
Is there really no such thing as connected components for a digraph?

**Comment by jpfairbanks** [comment]
I like the explicitness of making the user choose. They can always define an additional method if they want to use connected_components to mean weakly connected.

**Comment by sbromberger** [comment]
This gets complicated.

**Comment by sbromberger** [comment]
@jpfairbanks is this an abandoned effort at this point?

**Comment by jpfairbanks** [comment]
You said it gets complicated, what did you mean by that? I don't think this is too much of a big deal. I would like to know how many people have broken code out there that uses the result of connected_components on a digraph.

**Comment by sbromberger** [comment]
It's complicated because my original quick fix for this turned out to break other stuff. If you can get it the way you want to do it, please go ahead and make the fix.

**Comment by sbromberger** [comment]
@jpfairbanks - I'm going to close this out. The move to traits for directedness undoubtedly changes a bunch of stuff, and we can revisit once we merge. Feel free to reopen if you object :)

**Pull request closed without merging**
