### PR TITLE
revert to v0.7.3

### PR DESCRIPTION
**Pull request by sbromberger**
Revert back to the code state as of v0.7.3, since we've had lots of downstream failures with v0.7.4.

### CODE REVIEW

**Comment by tkelman** [comment]
Oh, I just meant you can make another tag of the exact same commit from 0.7.3, not that you had to revert code on master.

**Comment by sbromberger** [comment]
@tkelman that sure sounds easier. Can you tell me how to do that?

**Comment by sbromberger** [comment]
do you mean checkout v0.7.3, then tag v0.7.5?

**Comment by tkelman** [comment]
yeah, or do it from the github releases tab, create an 0.7.5 tag (+ release so attobot sees it) from the same commit as 0.7.3 (9af5190cb14ff12785698c9716e9322a04179144)

**Comment by sbromberger** [comment]
> do it from the github releases tab, create an 0.7.5 tag (+ release so attobot sees it) from the same commit as 0.7.3 (9af5190)

I don't know how to do this.

**Comment by sbromberger** [comment]
I got it.

**Comment by juliohm** [comment]
Hi @tkelman, is there any way to test downstream packages whenever a new tag is created in LG?

I know we can list dependent packages easily, but I wonder if we could run something like:

```julia
downstream = Pkg.dependents("LightGraphs")
for pkg in downstream
  Pkg.test(pkg)
end
```

automatically. That would be a great addition to attobot or the Julia pkg ecosystem in general. I will open an issue there and cc you.

**Comment by tkelman** [comment]
I'm working on something for this. It won't be tied into attobot, it needs to run on different infrastructure.

**Comment by juliohm** [comment]
Awesome, looking forward to it, saw your comment in the thread, thanks.

**Pull request closed without merging**
