### PR TITLE
Sbromberger/parameterization

### PR DESCRIPTION
**Pull request by sbromberger**
This implements full parameterization for `AbstractGraph` types, reducing the need for `eltype()`. It should be at least as performant as existing code and probably slightly more performant.

### CODE REVIEW

**Comment by sbromberger** [comment]
cc @jpfairbanks @juliohm @somil55 I'd love feedback on this proposal. It's fairly radical but I think it puts us in a good position for new graph types.

**Comment by sbromberger** [comment]
I plan on merging this in the next few days.

**Comment by jpfairbanks** [comment]
My main concern here is that this parameterization forces all graph implementations to have a vertex type. Previously nothing would work without defining eltype anyway so we were already forcing that. So this doesn't represent a change from the static quo.

Andrew Lumsdaine had a good line at HPEC this week "What is a graph? Any container of containers where the element type of the inner containers is the index type of the outer container." So I guess in that sense, you are forced to have a vertex type.

This affects all implementors of the LightGraphs interface because they need to implement 

```julia
mutable struct MyGraphType{T} <: AbstractGraph{T}
  #fields 
end
```

So this would be a minor version bump once it drops.

**Comment by sbromberger** [comment]
> So this would be a minor version bump once it drops.

Yes. We'd go to 11. :)

https://www.youtube.com/watch?v=4xgx4k83zzc

**Comment by sbromberger** [comment]
also
> This affects all implementors of the LightGraphs interface because they need to implement
> ...

They can also do
```
struct MySmallGraph <: AbstractGraph{UInt8}
```
and not worry about parameterization in their code.

**Comment by jpfairbanks** [comment]
:one: :one:

**Comment by sbromberger** [comment]
Thanks!

**Pull request merged**
