### PR TITLE
Create a test set for each test file

### PR DESCRIPTION
**Pull request by juliohm**
This PR addresses #539.

There are two files that I couldn't convert to test sets, they are `test/traversals/graphvisit.jl` and `test/traversals/maxadjvisit.jl`. Both files are using variables not defined in the `runtests.jl` script, which is dangerous. Can you please take a look and confirm the definition of the variables in these files?

Based on this exercise, I noticed that the tests in `linalg` need more work, it would be great to have them fitting the coding standards of the other tests.

### CODE REVIEW

**Comment by juliohm** [comment]
Also, what do you think of replacing the list of files in `runtests.jl` by a glob expression with `Glob.jl`? I can work on it if you want.

**Comment by sbromberger** [comment]
What's the advantage of `Glob.jl`? Do we reuse that list of files anywhere else?

**Comment by sbromberger** [comment]
PS: I :heart: the new output.

**Comment by juliohm** [comment]
`Glob.jl` is not that important, I was just wondering :blush: That would save us from keeping track of listing the files in `runtests.jl`, I love automation.

**Comment by sbromberger** [comment]
I do too, but I also like making sure we know exactly what's running. I think it's best practice as well (that is, `importall` is discouraged), so let's just keep it as-is until we run into a problem with it, and then you can say "I told you so!" (it's happened before.)

**Pull request merged**
