### PR TITLE
Parallel BFS

### PR DESCRIPTION
**Pull request by rohitvarkey**
This is an implementation of the frontier based parallel BFS algorithm using the `@threads` macro. It uses a thread safe queue structure for the BFS and atomic operations to ensure correctness with multiple threads.

Based on comments from #497 I have tried to modify the code to work based on `eltype(g)`. However, a bitarray cannot be used here as Julia does not support atomic operations on bitarrays or `Bool`s for that matter.

I have ported over the tests for BFS to their parallel versions. This is a WIP currently because the tests are failing for `DiGraphs` with `UInt8` and `Int16` eltypes. 

cc: @jpfairbanks

### CODE REVIEW

**Comment by sbromberger** [comment]
@rohitvarkey thank you!! This is awesome.

Do you have an idea why the tests are failing on a subset of the DiGraph types?

**Comment by rohitvarkey** [comment]
I fixed the tests. Should I write a test for `shift!` for the `ThreadQueue` to get 100% code coverage.

**Comment by sbromberger** [comment]
Yes - if possible, we'd like to maintain 100% coverage.

**Comment by sbromberger** [comment]
I can't wait to see the performance gains :) 👍 🎉

**Comment by rohitvarkey** [comment]
I've added a few tests for the ThreadQueue and we're at 100% coverage now!

**Comment by sbromberger** [comment]
I'd like to bikeshed the name. Because it's using threads, perhaps we call it `threaded_bfs` - we might have a real (multiproc) parallel implementation as well at some point. Thoughts?

**Comment by rohitvarkey** [comment]
I agree. `threaded_bfs` is definitely better in terms of clarity of what kinds of parallelism it is doing.

**Comment by jpfairbanks** [comment]
I like the current design in terms of using an Algorithm argument to a common function. So `ThreadLevelSyncBFS` or something like that. Or we could have abstract types for `ThreadAlgorithm` and `ProcessAlgorithm` and `DistributedAlgorithm` there might be some shared subroutines that just need to know which category the algorithm falls into.

**Pull request merged**
