### PR TITLE
Betweenness optimization

### PR DESCRIPTION
**Pull request by rlouf**
@sbromberger @jpfairbanks I added an example docstring for the betweenness centrality calculation. What do you think? Any suggestion?

I also changed the _accumulate and _rescale functions to in-place functions (seems to be the Julia way of doing things).

### CODE REVIEW

**Comment by sbromberger** [comment]
The code itself looks great - thanks. Will defer to @jpfairbanks on the docstring evaluation, since I don't know much about docstrings :)

**Comment by sbromberger** [comment]
We need to get travis tests passed though - does this require Docile? If so, make sure to add that to `REQUIRE`.

**Comment by rlouf** [comment]
It does, or Julia v.04, I'll have a look into this right now

**Comment by rlouf** [comment]
Funny, Julia does not support $$ $$ if you write some Latex in the docstrings...

**Comment by sbromberger** [comment]
LGTM. @jpfairbanks?

**Comment by rlouf** [comment]
Use this opportunity to give your suggestions on the docstring formatting. Once we agree on the convention, I'll start going over the code to reorganise it and document it.

**Comment by sbromberger** [comment]
Erm - not sure I want to reorganize anything. The layout of the methods within the files is deliberate....

**Comment by rlouf** [comment]
Probably, but the shortest path methods deserve their own folder for
instance!

On 22 May 2015 at 22:29, Seth Bromberger <notifications@github.com> wrote:

> Erm - not sure I want to reorganize anything. The layout of the methods
> within the files is deliberate....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaGraphs/LightGraphs.jl/pull/55#issuecomment-104779705>
> .
>



-- 
Rémi

"We asked the captain what course
of action he proposed to take toward
a beast so large, terrifying, and
unpredictable. He hesitated to
answer, and then said judiciously
'I think I shall praise it' '" (Robert Hass)

www.notonebitsimpler.com
www.quanturb.com

Institut de Physique Théorique, CEA Saclay
Bât. 774, P.136

remi.louf@cea.fr
0777034170

**Comment by jpfairbanks** [comment]
I think you can escape the $with \

**Comment by rlouf** [comment]
Indeed, you can.

**Pull request merged**
