### PR TITLE
duplicates #588 but on master

### PR DESCRIPTION
**Pull request by sbromberger**
This will close #588.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
I renamed _getBinomial, because we aren't writing java round these parts.

**Comment by sbromberger** [comment]
> I renamed _getBinomial, because we aren't writing java round these parts.

You also broke the build :)

I use underscores there to remind myself that docstrings aren't necessary because they're not part of the public API.

**Comment by sbromberger** [comment]
@jpfairbanks your review, please?

**Comment by sbromberger** [comment]
@jpfairbanks I noticed you reviewed #588 - I'll go ahead and squash/merge this given that it's the same code. If that was a mistake, please let me know and I'll revert.

**Comment by jpfairbanks** [comment]
Retroactive approval.

**Pull request merged**
