### PR TITLE
Add relabel_vertices

### PR DESCRIPTION
**Pull request by timholy**
This allows you to "rename" your vertices.

I'm not a heavy user of this package, so I'm not sure if I've got the abstraction levels correct. In particular, I wonder about the direct calls to `SimpleGraphs.SimpleGraph` from `operators.jl`.

### CODE REVIEW

**Comment by sbromberger** [comment]
Very cool. What does this do to the edges? That is,
```
g = PathGraph(5)   # 1 -> 2 -> 3 -> 4 -> 5
relabel_vertices(g, [4,3,2,5,1])
```
Does this provide new edges `4 -> 3 -> 2 -> 5 -> 1`?

**Comment by sbromberger** [comment]
PS: this may also be equivalent to `induced_subgraph` (and we may have a bug there in any case):
```
julia> g = PathGraph(5)
{5, 4} undirected simple Int64 graph

julia> h = relabel_vertices(g, [4,3,2,1,5])
{5, 4} undirected simple Int64 graph

julia> j = g[[4,3,2,1,5]]
{5, 4} undirected simple Int64 graph

julia> h == j
true
```

**Comment by sbromberger** [comment]
OK, so good news:

1) no bug in `induced_subgraphs` (ref #660).
2) looks like this may be equivalent to `induced_subgraphs` as shown above.

**Comment by timholy** [comment]
Cool. Didn't know about `g[[4,3,2,1,5]]`. I don't think we need this.

**Comment by sbromberger** [comment]
@timholy thanks for the contribution, though! Just curious: what are you using LG for?

**Comment by timholy** [comment]
Image segmentation---handling lots of local overlapping regions of interest. Though to be honest, I was just flirting with an idea that didn't pan out and so it's already been dropped from that particular application. Still, I've used it here and there previously, and have always been happy with it.

**Comment by jpfairbanks** [comment]
Well even if it doesn't help for that application I'm glad to have some positive feedback.

 I never thought of taking induced subgraphs with a permutation of the verticed as a method of relabeling the vertices so I am happy that the code we have actually works on that input. 

I'll leave a note here that Tim's method might be more performant in the case where you are relabeling the whole vertex set. If anyone has that problem in the future they should reopen this issue.

**Pull request closed without merging**
