### PR TITLE
first cut at fixing deprecations / errors on 0.6

### PR DESCRIPTION
**Pull request by sbromberger**
Branch `sbromberger/compat-0.6` is designed to work on Julia 0.6. So far all tests pass, though there are deprecations in graphmatrices, randgraphs, and persistence (the latter two dealing with produce/consume stuff.)

### CODE REVIEW

**Comment by sbromberger** [comment]
@jpfairbanks for some reason, `spectral.jl` is now failing tests. I didn't do anything specific to it; just merged some other code from master in to keep this branch up to date. I tried lowering the tolerance from 1e-8 to 1e-5 but that didn't seem to do it. I also tried changing the `approx` function. I may have to revert that. Any ideas?

**Comment by jpfairbanks** [comment]
Does this need julialang master?
I get errors on Version 0.6.0-dev.1393 
```
INFO: Precompiling module LightGraphs.
ERROR: LoadError: LoadError: syntax: invalid type signature
 in include_from_node1(::String) at ./loading.jl:532
 in include(::String) at ./sysimg.jl:14
 in include_from_node1(::String) at ./loading.jl:532
 in include(::String) at ./sysimg.jl:14
 in anonymous at ./<missing>:2
 in eval(::Module, ::Any) at ./boot.jl:236
 in process_options(::Base.JLOptions) at ./client.jl:248
 in _start() at ./client.jl:335
while loading /home/.julia/v0.6/LightGraphs/src/core.jl, in expression starting on line 1
while loading /home/.julia/v0.6/LightGraphs/src/LightGraphs.jl, in expression starting on line 134
ERROR: Failed to precompile LightGraphs to /home/.julia/lib/v0.6/LightGraphs.ji.
 in compilecache(::String) at ./loading.jl:672
 in require(::Symbol) at ./loading.jl:453
```

**Comment by sbromberger** [comment]
I'm pretty sure it needs -alpha.

**Comment by jpfairbanks** [comment]
I built master as of today and it worked.

There are some deprecation warnings about inner constructors, which I think are tied to changes made in the following commit.
https://github.com/JuliaLang/julia/commit/0190b3a1f1c02b2407c0fcefb6770b29bb6818b2

**Comment by jpfairbanks** [comment]
Well tests failed with GZip.jl`@`master:
```
running /home/.julia/v0.6/LightGraphs/test/persistence/persistence.jl ...
ERROR: LoadError: LoadError: UndefVarError: readall not defined
Stacktrace:
 [1] loadgraphml_mult(::GZip.GZipStream)
```

**Comment by sbromberger** [comment]
Yup. These are the combinatorial laplacian and friends.

**Comment by sbromberger** [comment]
It was working for me as of yesterday's build. :(

**Comment by jpfairbanks** [comment]
So readall got renamed to readstring. I will put a commit on this branch to fix that.

What happened to Tasks and produce/consume?

**Comment by jpfairbanks** [comment]
The next step is to replace produce/consume with channels.

**Comment by sbromberger** [comment]
(@jpfairbanks - I edited your list above.)

**Comment by sbromberger** [comment]
Where is the channels code? (Why is this checked off?)

**Comment by jpfairbanks** [comment]
I thought I made a branch with my commits that should be a part of this PR, but I can't find it.

**Comment by sbromberger** [comment]
> I thought I made a branch with my commits that should be a part of this PR, but I can't find it.

I thought I saw it too, and I was going to steal it. Could you (re)write it?

**Comment by jpfairbanks** [comment]
This commit 017137a10893bd8e24cdb2f9e7465ff91a0add95 has my channels stuff. It is in this PR

**Comment by sbromberger** [comment]
OK, I got it (cherry picked into abstractions). I'm going to close this out since I think the plan is to make the abstractions branch the "official" 0.6 release.

**Pull request closed without merging**
