### PR TITLE
Add DataStructures 0.18 compat

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by YingboMa** [comment]
Should it be LightGraphs.jl 2.0?

**Comment by sbromberger** [comment]
No - this should be applied not to master, but to 1.3.3. We can then merge and release 1.3.4.

**Comment by YingboMa** [comment]
Ah, how to do that? Do I create a new branch?

**Comment by sbromberger** [comment]
Oh, yeah, sorry.

The best way is, in your local copy, to create a new branch off of 1.3.4:
```
git checkout v1.3.4
git checkout -b yingboma/datastructures-0.18
# make changes here
git add -A
git commit -m "bump datastructures"
git push  # follow instructions to push the branch
```
then, on the github site, create a pull request from your branch to 1.3.4.

**Comment by YingboMa** [comment]
Thanks for the instruction!

**Pull request closed without merging**
