### PR TITLE
Articulationpoints rebase

### PR DESCRIPTION
**Pull request by jpfairbanks**
Rebased of #502 #501

### CODE REVIEW

**Comment by sbromberger** [comment]
@jpfairbanks please merge whichever one is current and close the other. Thanks!

**Comment by jpfairbanks** [comment]
I don't have permission to hit the merge button anymore. 😞

**Comment by sbromberger** [comment]
I think I can fix that... one sec

**Comment by sbromberger** [comment]
I show you having write access to the repo. I'll keep checking, but you should have access.

**Comment by jpfairbanks** [comment]
Eh still greyed out. You can just merge it and we can figure out the perms next PR.

**Comment by sbromberger** [comment]
Maybe you need 2FA enabled? I didn't require it, but I can't see any reason you shouldn't be able to merge PRs in LightGraphs. You have write access here and admin on LGE.

**Pull request merged**
