### PR TITLE
Use a Queue in connected_components!

### PR DESCRIPTION
**Pull request by harryscholes**
LightGraphs already depends on DataStructures, so I thought it might make sense to use a `Queue` in `connected_components!`.

Quick benchmarks:

```julia
julia> using DataStructures, BenchmarkTools

julia> function f_queue!(Q)
           for i in 1:1000
               enqueue!(Q, i)
           end
           for i in 1:1000
               dequeue!(Q)
           end
       end
f_queue! (generic function with 1 method)

julia> function f_vector!(Q)
           for i in 1:1000
               push!(Q, i)
           end
           for i in 1:1000
               popfirst!(Q)
           end
       end
f_vector! (generic function with 1 method)

julia> @btime f_queue!(Q) setup=(Q=Queue{Int}())

  2.827 μs (0 allocations: 0 bytes)

julia> @btime f_vector!(Q) setup=(Q=Vector{Int}())
  10.485 μs (9 allocations: 16.31 KiB)
```

### CODE REVIEW

**Comment by sbromberger** [comment]
Could you run benchmarks on the connected components functions using very large graphs? (1m /10m or so)

**Comment by harryscholes** [comment]
I ran a benchmark for the `Vector` and `Queue` versions on random graphs with 1 M and 10 M nodes. The `Queue` is faster than `Vector`, taking 0.83 the time for 1 M nodes and 0.88 the time for 10 M nodes.

```julia
julia> using LightGraphs, DataStructures, BenchmarkTools

julia> import LightGraphs: connected_components!

julia> function connected_components_queue!(label::AbstractVector, g::AbstractGraph{T}) where T
           nvg = nv(g)

           for u in vertices(g)
               label[u] != zero(T) && continue
               label[u] = u
               Q = Queue{T}()
               enqueue!(Q, u)
               while !isempty(Q)
                   src = dequeue!(Q)
                   for vertex in all_neighbors(g, src)
                       if label[vertex] == zero(T)
                           enqueue!(Q, vertex)
                           label[vertex] = u
                       end
                   end
               end
           end
           return label
       end
connected_components_queue! (generic function with 1 method)

julia> n = 1_000_000
1000000

julia> p = 5_000_000
5000000

julia> g = erdos_renyi(n, p)
{1000000, 5000000} undirected simple Int64 graph

julia> @btime connected_components!(label, $g) setup=(label=(zeros(eltype(g), nv(g))));
  366.056 ms (136 allocations: 9.01 MiB)

julia> @btime connected_components_queue!(label, $g) setup=(label=(zeros(eltype(g), nv(g))));
  303.223 ms (2129 allocations: 8.28 MiB)

julia> n = 10_000_000
10000000

julia> p = 50_000_000
50000000

julia> g = erdos_renyi(n, p)
{10000000, 50000000} undirected simple Int64 graph

julia> @btime connected_components!(label, $g) setup=(label=(zeros(eltype(g), nv(g))));
  5.991 s (934 allocations: 129.06 MiB)

julia> @btime connected_components_queue!(label, $g) setup=(label=(zeros(eltype(g), nv(g))));
  5.277 s (20898 allocations: 81.74 MiB)
```

Benchmarking script for reference:
```julia
using LightGraphs, DataStructures, BenchmarkTools
import LightGraphs: connected_components!

function connected_components_queue!(label::AbstractVector, g::AbstractGraph{T}) where T
    nvg = nv(g)

    for u in vertices(g)
        label[u] != zero(T) && continue
        label[u] = u
        Q = Queue{T}()
        enqueue!(Q, u)
        while !isempty(Q)
            src = dequeue!(Q)
            for vertex in all_neighbors(g, src)
                if label[vertex] == zero(T)
                    enqueue!(Q, vertex)
                    label[vertex] = u
                end
            end
        end
    end
    return label
end

n = 1_000_000
p = 5_000_000
g = erdos_renyi(n, p)
@btime connected_components!(label, $g) setup=(label=(zeros(eltype(g), nv(g))));
@btime connected_components_queue!(label, $g) setup=(label=(zeros(eltype(g), nv(g))));

n = 10_000_000
p = 50_000_000
g = erdos_renyi(n, p)
@btime connected_components!(label, $g) setup=(label=(zeros(eltype(g), nv(g))));
@btime connected_components_queue!(label, $g) setup=(label=(zeros(eltype(g), nv(g))));
```

**Comment by sbromberger** [comment]
OK, that sounds like a good plan. Can you resolve the merge conflicts and repush? I'll review/merge when the tests pass. Thanks for your help!

**Comment by simonschoelly** [comment]
Some word of warning, your choice of parameters for erdos_renyi might not be the best, basically you have one really large component, and a few isolated vertices, and nothing else. See: https://en.wikipedia.org/wiki/Giant_component

So it might be better to do some benchmarks with some other graphs.

**Comment by simonschoelly** [comment]
From looking at these benchmarks, the speed up seems to be mostly, because the old code over allocated memory, when increasing the vector size. So a queue could really make sense here, in what is essential a BFS. 

I think we could squeeze out even more performance by moving the allocation of the queue (or vector) out of the outer loop, so that we only create it once. Also, we probably can use `@inbounds` here. Does the queue support disabling of bound checks?

**Comment by sbromberger** [comment]
What if we allocated the queue at the top, and used `empty!` inside the loop?

**Comment by harryscholes** [comment]
@simonschoelly good point about Erdos-Renyi. Which type of random graph would you suggest using here instead?

@sbromberger we could definitely allocated the queue outside the for loop. We wouldn't even need to call `empty!` because the next iteration of the for loop only happens when the queue is empty!

**Comment by harryscholes** [comment]
I tried creating an Erdos-Renyi graph with very low edge probability, which generates a large number of connected components. Allocating the `Queue` outside of the loop provides a massive speed up.

```julia
julia> using LightGraphs, DataStructures, BenchmarkTools

julia> function connected_components_queue!(label::AbstractVector, g::AbstractGraph{T}) where T
           nvg = nv(g)
           Q = Queue{T}()
           for u in vertices(g)
               label[u] != zero(T) && continue
               label[u] = u
               enqueue!(Q, u)
               while !isempty(Q)
                   src = dequeue!(Q)
                   for vertex in all_neighbors(g, src)
                       if label[vertex] == zero(T)
                           enqueue!(Q, vertex)
                           label[vertex] = u
                       end
                   end
               end
           end
           return label
       end
connected_components_queue! (generic function with 1 method)

julia> n = 1_000_000
1000000

julia> p = 1e-6
1.0e-6

julia> g = erdos_renyi(n, p)
{1000000, 501164} undirected simple Int64 graph

julia> sort!(length.(connected_components(g)))
498837-element Array{Int64,1}:
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     ⋮
   542
   570
   580
   591
   605
   605
   610
   687
   710
   765
   914
   921
  1019
  1582
  2542
  2603
  3202
 11745

julia> @btime connected_components!(label, $g) setup=(label=(zeros(eltype(g), nv(g))));
  190.522 ms (1007514 allocations: 62.04 MiB)

julia> @btime connected_components_queue!(label, $g) setup=(label=(zeros(eltype(g), nv(g))));
  122.491 ms (41 allocations: 163.80 KiB)

```

**Comment by simonschoelly** [comment]
Yes, with Erdös-Renyi, a probability < 1/n should give  a lot of components. Would you mind to try putting `@inbounds` in front of `for u in vertices(g)` ? I think that would provide a bit more speedup. Saddly thought, that helps only with the Vector, I checked the source for DataStructures then they don't provide a way, for disabling bound checks on queues.

**Comment by harryscholes** [comment]
Just tried adding `@inbounds`, but there is no obvious speed up. At least not with the graph I used. It can't hurt having it though.

**Comment by sbromberger** [comment]
Do you need another `@inbounds` on the inner for loop, or does it propagate?

**Comment by simonschoelly** [comment]
> Do you need another `@inbounds` on the inner for loop, or does it propagate?

As far as I know, it should propagate.

**Comment by harryscholes** [comment]
I believe it propagates.

I just did a quick search for uses of `popfirst!` in LightGraphs. There are a number of places where queues are implemented using vectors and `popfirst!` e.g.: `has_path`, `shortest_paths`, `spfa_shortest_paths`, `bipartite_map`. We could probably get similar performance gains there as well

**Comment by sbromberger** [comment]
> e.g.: has_path, shortest_paths, spfa_shortest_paths, bipartite_map. We could probably get similar performance gains there as well

If you choose to make PRs for these, please make sure you're using the latest master, as we've got significant changes to shortest paths and other functions.

**Comment by harryscholes** [comment]
Thanks @sbromberger. I'll put together a PR for the other functions shortly

**Pull request merged**
