### PR TITLE
using list constructor instead of push! saves time and allocs

### PR DESCRIPTION
**Pull request by sbromberger**

### CODE REVIEW

**Comment by jpfairbanks** [comment]
Can you use `Set(values(lambda))`?

**Comment by sbromberger** [comment]
> Can you use `Set(values(lambda))`?

I don't think so, if lambda isn't a dict:

`ERROR: MethodError: no method matching values(::Array{Pair{Int64,Int64},1})`

**Comment by sbromberger** [comment]
Also, that travis failure is weird (and is in your code, @jpfairbanks :) ) - mind taking a look?

**Comment by jpfairbanks** [comment]
That is a sporadic failure like #455

**Pull request merged**
