### PR TITLE
Compatibility for DataStructures v0.18, and deprecation fix for find_root

### PR DESCRIPTION
**Pull request by jaakkor2**
This PR is against branch v1.3.3, and passes tests locally.  Fixes https://github.com/JuliaGraphs/LightGraphs.jl/issues/1469.
- Fixes deprecation of `find_root`.
- Adds compatibility to DataStructures v0.18.

### CODE REVIEW

**Comment by sbromberger** [comment]
This doesn't appear to be against 1.3.3 - note the conflicts. You've set your merge target to master.

**Comment by jaakkor2** [comment]
Changed base branch to `sbromberger/1.4.0`.  No conflicts now.

**Comment by sbromberger** [comment]
1.4.0 is defunct. You'll want to base this on 1.3.3.

**Comment by jaakkor2** [comment]
I do not see a branch for 1.3.3.  Is it `stable`?

**Comment by sbromberger** [comment]
It's a tag: https://github.com/JuliaGraphs/LightGraphs.jl/tree/v1.3.3

**Comment by jaakkor2** [comment]
I cannot figure out how to do that 🤔. In the drop down menu I only see branches while the search field suggests that tags should be an option.   The PR branch is created from https://github.com/JuliaGraphs/LightGraphs.jl/tree/v1.3.3.
image

**Comment by sbromberger** [comment]
That is puzzling. If you scroll to the top of that list, is there a "branches / tags" selector?

If not, what I'd recommend trying is this: in your local copy, checkout v1.3.3, then do a `checkout -b jaakor2/fix-find-root`, then make your changes, and then push. See if github will then allow you to apply to v1.3.3.

**Comment by sbromberger** [comment]
On second thought, I think `stable` is where we want this to go. Don't do anything else right now :)

**Review by sbromberger — APPROVED** [review]

**Comment by sbromberger** [comment]
Do me a favor: we don't have CI set up for this branch (yet). Could you paste the output of `]test LightGraphs` from this code? Thanks.

**Comment by jaakkor2** [comment]
Tested with Julia v1.5.1
```
(foo) pkg> test LightGraphs
    Testing LightGraphs
Status `C:\Users\jaakkor2\AppData\Local\Temp\jl_lZpsDf\Project.toml`
  [ec485272] ArnoldiMethod v0.0.4
  [864edb3b] DataStructures v0.18.6
  [d25df0c9] Inflate v0.1.2
  [093fc24a] LightGraphs v1.3.3 `C:\Users\jaakkor2\.julia\dev\LightGraphs`
  [699a6c99] SimpleTraits v0.9.3
  [2a0f44e3] Base64
  [8bb1440f] DelimitedFiles
  [8ba89e20] Distributed
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [1a1011a3] SharedArrays
  [2f01184e] SparseArrays
  [10745b16] Statistics
  [8dfed614] Test
Status `C:\Users\jaakkor2\AppData\Local\Temp\jl_lZpsDf\Manifest.toml`
  [ec485272] ArnoldiMethod v0.0.4
  [34da2185] Compat v3.16.0
  [864edb3b] DataStructures v0.18.6
  [d25df0c9] Inflate v0.1.2
  [093fc24a] LightGraphs v1.3.3 `C:\Users\jaakkor2\.julia\dev\LightGraphs`
  [1914dd2f] MacroTools v0.5.5
  [bac558e1] OrderedCollections v1.3.1
  [699a6c99] SimpleTraits v0.9.3
  [90137ffa] StaticArrays v0.12.4
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8bb1440f] DelimitedFiles
  [8ba89e20] Distributed
  [b77e0a4c] InteractiveUtils
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [44cfe95a] Pkg
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays
  [10745b16] Statistics
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
WARNING: using Traversals.tree in module Main conflicts with an existing identifier.
Test Summary: |  Pass  Total
LightGraphs   | 29671  29671
    Testing LightGraphs tests passed
```

**Comment by sbromberger** [comment]
Awesome. Thanks and sorry for all the extra steps.

**Pull request merged**
