### PR TITLE
WIP: Codecov

### PR DESCRIPTION
**Pull request by somil55**

### CODE REVIEW

**Comment by sbromberger** [comment]
@somil55 - hold off. This is likely a codecov.io issue - see, e.g., 

https://github.com/JuliaGraphs/LightGraphs.jl/blob/0c98eaa22925f294f0c36c8a5ef222d145944780/test/traversals/dfs.jl#L16

but 

https://codecov.io/gh/JuliaGraphs/LightGraphs.jl/src/master/src/traversals/dfs.jl#L63...66

**Comment by somil55** [comment]
sure! I tried all the test and they were passing. It has to be with codecov.

**Comment by somil55** [comment]
@sbromberger Are we aiming for Julia 0.7.0-beta2?

**Comment by somil55** [comment]
sure!

**Comment by somil55** [comment]
#966

**Comment by somil55** [comment]
#966

**Comment by sbromberger** [comment]
Closing - need to make a fresh start.

**Pull request closed without merging**
