### PR TITLE
Use DFS in biconnectivity/visit!

### PR DESCRIPTION
**Pull request by birm**
Early Work in Progress for #1323

### CODE REVIEW

**Comment by alimamdouh212** [comment]
@birm sir, i want to solve this issue, so i wonder if you still interested in this pr.

**Comment by alimamdouh212** [comment]
@birm sir, i want to make my own pr to solve this issue, so i wonder if you are ok with that.

**Comment by birm** [comment]
sure! i can neaten my commits in case you for some reason want to work from this state. otherwise, good luck!

**Comment by birm** [comment]
closed in favor of #1336

**Pull request closed without merging**
